Cargo.lock
Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/block_verifier.rs
crates/astria-conductor/src/executor.rs
crates/astria-conductor/src/telemetry.rs
crates/astria-conductor/src/tendermint.rs
crates/astria-gossipnet/src/network_stream.rs
crates/astria-gossipnet/tests/network.rs
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-sequencer-relayer/src/sequencer.rs
crates/astria-sequencer-relayer/src/validator.rs
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/state_ext.rs

- remove usages of bech32 addresses since they're cosmos-specific
closes #97

maintainence: remove bech32 addresses

---

.github/workflows/docker-build.yml
crates/astria-sequencer/Dockerfile

add dockerfile for sequencer and workflow step

---

crates/astria-conductor/src/config.rs

was complaining if these weren't set :/

fix(conductor): add defaults to cli

---

README.md
crates/astria-conductor/README.md
crates/astria-sequencer-relayer/README.md
crates/astria-sequencer-relayer/src/data_availability.rs
crates/astria-sequencer-relayer/src/network.rs
crates/astria-sequencer/README.md
justfile

- add build instructions
- add instructions for locally running the whole stack
- update crate readmes
closes #132

docs: update readme to have build + run instructions

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

Added Docker hub login as a secret to unable more image pulls.

Adds Docker Hub Login

---

.gitignore
crates/astria-composer/README.md
crates/astria-composer/justfile
crates/astria-composer/local.env.example
crates/astria-composer/src/config.rs
specs/config-standard.md

- documents configuration standard
- updates astria-composer as an example of implementing the standard
Follow up work all listed on #240 tasklist

Configuration standard spec

---

crates/astria-composer/src/composer.rs
crates/astria-composer/src/lib.rs
crates/astria-composer/src/searcher/collector.rs
crates/astria-composer/src/searcher/mod.rs
crates/astria-composer/src/searcher/rollup.rs

Adding more doc comments to underdocumented parts of the composer
This is a result of the documentation workshop in the Colorado onsite
- Adding more doc comments

feat(composer): adding more docs

---

crates/astria-sequencer/README.md
crates/astria-sequencer/src/config.rs

`ASTRIA_SEQUENCER` should be `ASTRIA_SEQUENCER_` - also small doc updates
i ran it

fix(sequencer): fix config

---

.github/workflows/reusable-cargo-version.yml

Fix failing test
Test was failing on anything without a new version indicator, not desired outcome
- set failBuild to false
tests should pass on this PR

ci: matching tag should not fail

---

Cargo.lock
crates/astria-composer/Cargo.toml

The last image cut went funky, this will cut a nice new image.

composer: release new image

---

Cargo.lock
crates/astria-conductor/Cargo.toml

New minor release of conductor.

release(conductor): Release 0.6.1

---

Cargo.lock
crates/astria-composer/Cargo.toml

New minor release of composer.

release(composer): Release 0.2.2

---

crates/astria-conductor/src/client_provider.rs

Reports the error, if any, that the tendermint websocket drivers returns upon exit.
The tendermint websocket driver frequently disconnects, but we are ignoring its return value. We should not do that because it might contain valuable information about why it exited.
- Add error message and backtrace to event emitted after websocket driver exited, but before it returned.
N/A

conductor: report reason for websocket driver exit

---

Cargo.lock
crates/astria-conductor/Cargo.toml

Cutting new release of conductor

release(conductor): 0.7.0

---

crates/astria-composer/src/searcher/rollup.rs

Allow dashes in rollup names passed to composer through the env var `ASTRIA_COMPOSER_ROLLUPS="astria-dusk-1::ws://127.0.0.1:8546/"`
Only allowing alphanumeric characters as rollup chain IDs was overly restrictive. It's nice for human readability and for matching subdomain paths to rollup IDs when deploying to allow dashes.
- Add `-` to the character classes in the group matching chain IDs names
- Add tests
- Mention alphanumeric ascii and dash in example config
Tests have been updated to include dashes.

feat(composer): allow rollup names with dash

---

Cargo.lock
crates/astria-composer/Cargo.toml

Cut new patch release of composer.

release(composer): 0.2.4

---

crates/astria-cli/README.md
crates/astria-composer/src/searcher/executor.rs
crates/astria-proto/README.md

fix: typos

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-sequencer/Cargo.toml

cut new release of conductor and sequencer

chore(conductor, sequencer): release 0.10.1 conductor and 0.6.1 sequencer 

---

.github/workflows/test.yml

- pin foundry version in CI
closes #606

fix(ci): pin foundry version

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml

Updating release cuts of composer, conductor, relayer as breaking change releases.

chore(composer, relayer, conductor): release composer 0.3.0, conductor 0.11.0, relayer 0.9.0

---

crates/astria-sequencer/Cargo.toml

Revert "chore(sequencer): release sequencer 0.7.0"

---

.github/workflows/test.yml

typo in command in CI error message

fix(ci): fix typo in ci error message

---

.github/workflows/test.yml

previous foundry commit is no longer available, changed it to one that is.

fix(ci): change foundry commit in ci

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/sequencer/mod.rs

Removes the sync-completed signal from the sequencer reader.
In the new implementation of syncing there is no need for reporting the sync status back to conductor because the celestia and sequencer readers can run concurrently.
- Remove the sync-completed signal.

refactor(conductor): remove sync-completed signal

---

Cargo.lock
crates/astria-celestia-client/Cargo.toml
crates/astria-celestia-client/src/client.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/sequencer.rs

Issues that I had with logs when testing conductor
https://github.com/astriaorg/astria/pull/691

fix(conductor): trace level for noisy events, no debug logging for celestia client

---

.github/workflows/docker-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/reusable-docker-build.yml
.github/workflows/test.yml

Updates CI jobs to run against the release branch, with correct tags

chore(sequencer): config release-v0.8.x workflows

---

proto/sequencerapis/astria_vendored/tendermint/types/types.proto

Fix broken test on protobuf format
Bad merge broke main proto lint.

fix: fix format of proto

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Cutting new breaking changes. Prep for next network release.

release: composer 0.4, conductor 0.12, sequencer 0.9, relayer 0.10

---

crates/astria-conductor/src/executor/mod.rs
crates/astria-core/src/sequencer/v1alpha1/block.rs
crates/astria-core/src/sequencer/v1alpha1/celestia.rs
crates/astria-sequencer/src/grpc/sequencer.rs

as title says - see https://github.com/astriaorg/astria/pull/701

feat(proto): address comments on #701

---

crates/astria-conductor/src/celestia/mod.rs

Conductor reports if it exhausted its window of permissible Celestia heights.
If conductor exhausted its range of Celestia heights it would simply be quiet. Now it reports that it won't fetch more blobs every time it receives a new Celestia header.
- Emit an event every time a new Celestia header is received and if the range of Celestia heights is exhausted
- Adds convenience methods to make that happen
Just reporting

feat(conductor): report if conductor won't read more Celestia heights

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/ibc/ics20_transfer.rs

chore: bump penumbra deps

---

.github/workflows/build.yml
.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

Running manually was going to build incorrect image tags for many components.

fix(ci): isolate docker builds to specific release 

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

It was still broken, testing this locally is impossible

fix(ci): docker images tagging again

---

crates/astria-conductor/src/sequencer/block_stream.rs

fix wording in a log in conductor.
- clarify conductor log

fix(conductor): clarify conductor log

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/accounts/state_ext.rs

Releases patch fix for sequencer, both as binary and in charts.

chore(sequencer): cut sequencer 0.10.1 release

---

justfile

Updates justfile to provide more flexibility in images used. When no tag is specified, you can simply modify values files to run a single local image, whereas before needed all custom or none.
I want to make it really easy for people to test the components they are editing locally e2e.

chore(ci): improve the flow of local smoke test

---

.github/workflows/docker-build.yml

Updates to utilize a fixed in time version of foundry since newest release broke smoke test.

ci: smoke test fix

---

.github/workflows/docker-build.yml
justfile

Removes the foundry dependency using raw json rpc w/ curl, adds repeating checks for finalization and deposit success.
Flaky smoke tests make submission of PRs frustrating, this should decrease flakiness of the integration test.

fix(ci): less flaky smoke test

---

charts/celestia-local/Chart.yaml
charts/celestia-local/files/scripts/init-bridge.sh
charts/celestia-local/files/scripts/init-celestia-appd.sh
charts/celestia-local/files/scripts/start-bridge.sh
charts/celestia-local/files/scripts/start-celestia-appd.sh
charts/celestia-local/templates/configmap.yaml
charts/celestia-local/values.yaml
charts/hermes/Chart.yaml
charts/hermes/files/config.toml
charts/hermes/templates/_helpers.tpl
charts/hermes/templates/configmaps.yaml
charts/hermes/templates/deployment.yaml
charts/hermes/templates/ingress.yaml
charts/hermes/templates/secretproviderclass.yaml
charts/hermes/templates/service.yaml
charts/hermes/values.yaml
charts/sequencer/values.yaml
dev/values/hermes/local.yml
justfile
taplo.toml

Adds a hermes relayer chart which can be utilized to connect two IBC compatible chains for relaying.
Note: I have not been able to get the local connection working yet but have confirmed against celestia mocha.

feat(charts): hermes chart

---

.github/workflows/release.yml

fixes deployment of protos on main

fix(ci): fix deploy of protos on main

---

.github/workflows/release.yml

Uses correct action that exists

fix(release): charts release fix

---

Cargo.lock
charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml

Release breaking change new versions of conductor and relayer which work together.

release: conductor 0.15.0, relayer 0.13.0

---

charts/celestia-node/Chart.yaml
charts/celestia-node/values.yaml
charts/evm-rollup/Chart.lock
charts/evm-rollup/Chart.yaml

Updates the helm chart for celestia-node with the latest bug fix version.

chore: update celestia-node version

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/templates/deployments.yaml
charts/evm-rollup/templates/ingress.yaml
charts/evm-rollup/templates/secretproviderclass.yaml
charts/evm-rollup/templates/service.yaml
charts/evm-rollup/templates/storageclasses.yaml
charts/evm-rollup/templates/volumes.yaml
charts/evm-rollup/values.yaml

Fixes secret push to match general pattern, updates deployment of most blockscout & faucet resources to only be deployed when used.

feat(chart): secret fix, deployment fix for evm-rollup

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/templates/secretproviderclass.yaml
charts/evm-rollup/templates/volumes.yaml

Variety of chart fixes found while deploying forma:
- gas limit needs the hacky string number treatment
- volumes weren't deploying correctly
- update to not push faucet secret when disabled.

fix(chart): evm volumes fix

---

charts/evm-rollup/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/servicemonitor.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/servicemonitor.yaml

Updates service monitor setup and labels to get monitoring working.

chore(charts): fix service monitor labels

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/servicemonitor.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Fixing the servicemonitor config which referenced a value which does not exist.

fix(charts): fix relayer servicemonitor

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/servicemonitor.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Fixes the labels of sequencer relayer service monitor which referenced a nonexistant helper.

fix(charts): relayer valid service label

---

crates/astria-bridge-withdrawer/justfile

add justfile to run the bridge withdrawer.

feat(bridge-withdrawer): add justfile

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml

Forgot to update a configmap in latest push after release.

fix(charts): conductor configmap fix

---

Cargo.lock
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-core/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml

Removed unused dependencies.
I ran [`cargo udeps`](https://github.com/est31/cargo-udeps) and it found a few unused dependencies.
- Removed unused dependencies.
N/A

chore: remove unused dependencies

---

charts/sequencer/files/cometbft/config/genesis.json
charts/sequencer/templates/_helpers.tpl
charts/sequencer/values.yaml
dev/values/validators/node0.yml
dev/values/validators/node1.yml
dev/values/validators/node2.yml
dev/values/validators/single.yml

Updates chart to use a helper and use single value instead of double value setup.

chore: minor updates to in flight pr chart

---

.github/workflows/build.yml
.github/workflows/docker-build.yml
.github/workflows/release.yml
.github/workflows/reusable-release-cargo.yml
Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Creates releases needed for dusk-8 release, and adds the new bridge withdrawer release.

release: dusk-8 versions

---

Cargo.lock
crates/astria-conductor/Cargo.toml

Missed pushing a PR on previous merge, incorrect semver in previous tag.

release(conductor): fix conductor release version

---

.github/workflows/docker-build.yml

chore: CLI bridge smoke test

---

Cargo.lock
crates/astria-bridge-withdrawer/Cargo.toml

Missed cutting bridge withdrawer in previous PR

release: cut bridge withdrawer release

---

Cargo.lock
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Cutting releases after most recent sprint.

release: biweekly release cut

---

charts/composer/Chart.yaml
charts/composer/values.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/templates/configmaps.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml

Chart updates for newest image cuts

release(charts): update with biweekly image cuts

---

Cargo.lock
crates/astria-cli/Cargo.toml
crates/astria-cli/src/cli/mod.rs

Updates the cli with a new release which supports dusk-10 as default network.

release(cli): new release for dusk-10

---

Cargo.lock
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/accounts/mod.rs
crates/astria-sequencer/src/accounts/query.rs
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/service/mempool.rs

Brief summary of the changes made, ie "what?"
How are these changes tested?
- List out metrics added by PR, delete section if none. 
closes

WIP: refactor account balances state reads as stream

---

dev/values/rollup/preview-env.yaml
dev/values/validators/preview-env.yaml

Brief summary of the changes made, ie "what?"
How are these changes tested?
- List out metrics added by PR, delete section if none. 
closes

fix volume rollupName value

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/mod.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/builder.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs

Changed `sequencer_cometbft_client` and `sequencer_grpc_client` construction so that each can be passed to consumers via cloning.
Both clients were previously constructed ad-hoc from endpoints, which was unnecessary.
- Moved construction of `sequencer_cometbft_client` and `sequencer_grpc_client` up so that each can be passed to its consumers (`Startup` and `Submitter`) via cloning.
closes #1315

chore(bridge-withdrawer): pass GRPC and CometBFT clients to consumers directly

---

charts/composer/Chart.yaml
charts/composer/values.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml

The chart updates missed from last release cycle

release: charts from last iteration

---

charts/composer/Chart.yaml
charts/composer/templates/configmap.yaml
charts/composer/values.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/genesis.json
charts/sequencer/templates/configmaps.yaml
charts/sequencer/values.yaml

Update charts to utilize the v1.0.0-rc.1 images

release(charts): update for v1.0.0-rc.1 image cuts

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Couple of versions in charts which were not set correctly.

fix(charts): minor version issues

---

specs/sequencer-relayer.md

Typo/grammar fixes to relayer doc.
Reviewed the doc to ensure it is up to date with current code.

chore(docs): minor updates to relayer doc

---

crates/astria-cli/src/sequencer/threshold/dkg.rs
crates/astria-cli/src/sequencer/threshold/sign.rs
crates/astria-cli/src/sequencer/threshold/verify.rs

Brief summary of the changes made, ie "what?"
How are these changes tested?
- List out metrics added by PR, delete section if none. 
closes

updates to make workflow work

---

charts/hermes/Chart.yaml
charts/hermes/files/config.toml

fixes` config.toml `template
- remove double bracket
locally against a cluster

fix(charts): packet filter

---

Cargo.lock
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-cli/Cargo.toml
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Cut new binaries for testnet software upgrade.

release: v1.0.0-rc.2

---

crates/astria-core/src/generated/astria.protocol.transaction.v1.rs
crates/astria-core/src/generated/astria.protocol.transaction.v1alpha1.rs
crates/astria-core/src/protocol/transaction/v1/action/mod.rs
proto/protocolapis/astria/protocol/transaction/v1/action.proto
proto/protocolapis/astria/protocol/transaction/v1alpha1/action.proto

fix incorrect comment on `Ics20Withdrawal` `timeout_height`.

fix(core, proto): fix action comments

---

CODEOWNERS
Cargo.lock
crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-composer/CHANGELOG.md
crates/astria-composer/Cargo.toml
crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml
crates/astria-merkle/CHANGELOG.md
crates/astria-merkle/Cargo.toml
crates/astria-sequencer-relayer/CHANGELOG.md
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Release of v1.0 of core binaries

release: v1.0 cut

---

charts/composer/Chart.yaml
charts/composer/values.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/templates/configmaps.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml

Updates all charts to 1.0 images

chore(charts): update to 1.0

---

charts/graph-node/Chart.yaml
charts/graph-node/templates/volumes.yaml

Changes made to get storage updates succesful for graph node.

fix(charts): graph node storage

---

.github/workflows/docker-build.yml

This adds the auctioneer binary to the docker build workflow.
- add the auctioneer to the docker-build github workflow
closes https://github.com/astriaorg/astria/issues/1820

 ci(auctioneer): add auctioneer to docker-build workflow

---

crates/astria-sequencer/src/sequencer.rs

Changed server names to conform to Rust naming conventions.
Per Rust naming conventions [here](https://github.com/rust-lang/rfcs/blob/1c590ce05d676e72e2217845ee054758d3a6df34/text/0430-finalizing-naming-conventions.md?plain=1#L46-L47) acronyms in upper camel case should be treated as words.
- Renamed `RunningABCIServer` to `RunningAbciServer`.
- Renamed `RunningGrpcServer` to `RunningGrpcServer`.
- Removed aliases for the handles to these types.
Passing all tests, no additional tests needed.
closes #1930

chore(sequencer): fix names to conform to Rust naming conventions

---

Cargo.lock
crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-cli/CHANGELOG.md
crates/astria-cli/Cargo.toml
crates/astria-composer/CHANGELOG.md
crates/astria-composer/Cargo.toml
crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/CHANGELOG.md
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Releases all unreleased binary updates

chore: cut releases

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/_helpers.tpl
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Fixes helper in the chart which didn't have matching value types

fix(charts): broken helper in relayer

---

charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl

Fixes a version in the chart which didn't exist.

fix(chart): cometbft version missing v

---

.cargo/audit.toml
crates/astria-conductor/CHANGELOG.md
crates/astria-core/CHANGELOG.md
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/app/test_utils.rs

This is (hopefully) a final merge of `main` into the feature branch, along with the updates to the relevant changelogs.
Preparation for merging the feature branch to `main`.
- Merge `main` (one trivial conflict in `charts/just/deploy.just`)
- Update changelogs for conductor, core and sequencer. Note that I attributed the next available PR number to this one in the changelogs as I expect that to be the merge-to-main PR.  I can update later if that's not the case in the end.
No new tests required.

chore: merge main to feature branch and update changelogs

---

charts/external-ingress/Chart.yaml
charts/external-ingress/values.yaml

The nil entry instead of empty brackets throws off helm expectations, use empty bracket.

chore(charts): external ingress empty brackets

---

crates/astria-conductor/src/celestia/reconstruct.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-core/src/sequencerblock/v1/celestia.rs
crates/astria-core/src/upgrades/v1/upgrades.rs
crates/astria-sequencer/src/upgrades/upgrades_handler.rs
specs/oracle.md

This addresses @SuperFluffy's review comments on #2085.
Minor updates to address review comments (branch is protected, so cannot be directly addressed via a commit to `feat/oracle`)
- Various small updates.
New tests added as requested.

chore(conductor, core): minor updates

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

release: sequencer release 2.0.1

---

Cargo.lock
Cargo.toml
charts/external-ingress/Chart.yaml
charts/external-ingress/values.yaml
charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml
system-tests/sequencer_upgrade_test.py

This is a simple merge of `main`.
This is to allow the feature branch to be merged to `main`.
- Merged `main`.  Conflicts in the following files, but all trivial:
- charts/sequencer/Chart.yaml
- crates/astria-sequencer/CHANGELOG.md
No new tests needed.

chore: merge main branch to oracle feature branch

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/upgrades/custom.upgrades.json
charts/sequencer/files/upgrades/dusk-11.upgrades.json
charts/sequencer/templates/_helpers.tpl
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml
dev/values/validators/aspen.upgrade.yml

Cut image and update chart for sequencer 3.0.0-rc.1 release which includes the aspen upgrade.

release(sequencer): 3.0.0-rc.1 release

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/upgrades/dawn-1.upgrades.json
charts/sequencer/files/upgrades/mainnet.upgrades.json
charts/sequencer/templates/_helpers.tpl
charts/sequencer/templates/configmaps.yaml
charts/sequencer/values.yaml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Create new sequencer 3.0.0 RC release, and a RC chart for the Aspen upgrade.

release(sequencer): sequencer 3.0.0-rc.2 w/ chart

---

Cargo.lock
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/_helpers.tpl
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl
charts/sequencer/templates/configmaps.yaml
charts/sequencer/values.yaml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Create new major release and matching charts for sequencer.

release(charts, sequencer): sequencer v3

---

Cargo.lock
crates/astria-composer/CHANGELOG.md
crates/astria-composer/Cargo.toml

Cut latest release of composer

release: composer 1.1.0
