crates/astria-gossipnet/src/network.rs

- use os allocated port in test
- the test runs in under 1s locally, so I suspect there's something else going on

[wip] fix gossipnet in ci

---

.gitignore
kubernetes-ci/prepull-daemon-set.yml

The latest `pause` image is quite old and does not support arm.
https://github.com/linkerd/linkerd2/issues/7558

Use pause:3.2 image which has arm and amd versions

---

crates/astria-conductor/src/reader.rs
crates/astria-sequencer-relayer/src/da.rs

- check that block hash matches the sequencer block header
- check that the block data hash matches all the txs in the sequencer block
closes #17

feat(conductor): add more checks to `validate_sequencer_namespace_data`

---

.github/workflows/proto.yml
.github/workflows/rust.yml

Fixes #56
This also establishes a pattern we can use elsewhere to limit test runs and builds of dependent images

Buf workflow only run when protos or workflow changes

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

Builds and pushes images for `astria-conductor` and `astria-sequencer-relayer`. 
Images will be pushed to the `astriaorg/conductor` and `astriaorg/sequencer-relayer` package repositories respectively. 
Fixes #42

Add docker container flows

---

.github/workflows/rust.yml
crates/astria-proto/proto/astria/sequencer/v1/block.proto
crates/astria-proto/proto/astria/sequencer/v1/data.proto
crates/astria-proto/proto/astria/sequencer/v1/tx.proto
crates/astria-proto/src/lib.rs

This commit makes `clippy::pedantic` the default
lint group for the repository. Only a few crates
are currently exempt from it. All new crates are
expected to adhere to `clippy::pedantic`.
This commit also ensures that `astria-proto`
does not trigger `clippy::pedantic` warnings:
+ generated code is generally exempt
+ a few doc comment related lints are enabled to make for nicer rust docs from the generated code
+ the conversion methods for `Uint128` are updated to no longer need explicit casts; they expicitly move bytes into the right positions instead.

ci: make pedantic clippy the default

---

crates/astria-conductor/src/driver.rs
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-sequencer-relayer/src/sequencer_block.rs
crates/astria-sequencer-relayer/src/transaction.rs

fixes data hash mismatch:
```
2023-06-16T21:50:03.515068Z  WARN astria_conductor::reader: sequencer block failed validation: data hash stored in block header does not match hash calculated from transactions
at crates/astria-conductor/src/reader.rs:211
```
transactions needed to be hashed first before being merkleized.
closes #105

fix(relayer): fix calculation of data_hash

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/Cargo.toml

version bumps, will allow us to use https://github.com/penumbra-zone/penumbra/pull/2723 when/if it's merged so we can remove the patch

bump tendermint-rs to 0.32, penumbra to 0.54.1 and tower-abci to 0.8.0

---

.dockerignore
crates/astria-conductor/Dockerfile
crates/astria-sequencer-relayer/Dockerfile

This commit installs librocksdb-dev inside the
build image layer and sets the ROCKSDB_LIB_DIR
environment variable so that librocksdb-sys is
build against the pre-compiled artifacts rather
than vendoring rocksdb.
This should significantly speed up build times.
Note that we transitively depend on
`librocksdb-sys:0.8.3+7.4.4` which requires
librocksdb 7.4.4, while debian bookworm provides
librocksdb 7.8.3. This commit assumes that
rocksdb is backward compatible (i.e. 7.8.3 can be used in
place of 7.4.4).
Note that this commit does not yet account for cross compilation on an x86 host targeting aarch64.
Fixes #80

container: link against system rocksdb

---

.github/workflows/rust.yml
crates/astria-sequencer-relayer/src/api.rs
crates/astria-sequencer-relayer/src/lib.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/src/network.rs
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs

This commit adds a `SequencerRelayer` type to
`astria-sequencer-relayer`, which serves as the
single entrypoint to the service. It creates all
constituent tasks from the service config, and
runs them until stopped.
This also lays the groundwork for writing
integration tests against `SequencerRelayer`
using the same codepaths as are used by the
binary.
In future commits all items that are currently
exposed will be made crate-private, except for
the `SequencerRelayer` type itself, config
generation, and telemetry initialization.
Because other workspace crates depend on items
defined within `astria-sequencer-relayer` they
are currently left unchanged.
Closes #85

feat(sequencer-relayer): single entry point

---

crates/astria-conductor/src/execution_client.rs
crates/astria-proto/proto/astria/execution/v1/execution.proto

fix: rename `prev_state_root` to `prev_block_hash`

---

.github/workflows/rust.yml

Rustfmt 1.6.0 has been released and is now part
of rust nightly. This broke CI. This commit sets
CI to a fixed rust nightly release so that this
won't happen again.

chore: update rustfmt to recent nightly

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
crates/astria-celestia-jsonrpc-client/Cargo.toml
crates/astria-celestia-jsonrpc-client/README.md
crates/astria-celestia-jsonrpc-client/k8s/config-maps.yml
crates/astria-celestia-jsonrpc-client/k8s/deployment.yml
crates/astria-celestia-jsonrpc-client/k8s/ingress.yml
crates/astria-celestia-jsonrpc-client/k8s/kustomization.yml
crates/astria-celestia-jsonrpc-client/k8s/namespace.yml
crates/astria-celestia-jsonrpc-client/k8s/scripts/generate-token.sh
crates/astria-celestia-jsonrpc-client/k8s/scripts/init-bridge.sh
crates/astria-celestia-jsonrpc-client/k8s/scripts/init-celestia-appd.sh
crates/astria-celestia-jsonrpc-client/k8s/scripts/start-bridge.sh
crates/astria-celestia-jsonrpc-client/k8s/scripts/start-celestia-appd.sh
crates/astria-celestia-jsonrpc-client/k8s/service.yml
crates/astria-celestia-jsonrpc-client/src/blob.rs
crates/astria-celestia-jsonrpc-client/src/header.rs
crates/astria-celestia-jsonrpc-client/src/lib.rs
crates/astria-celestia-jsonrpc-client/src/rpc_impl/blob.rs
crates/astria-celestia-jsonrpc-client/src/rpc_impl/header.rs
crates/astria-celestia-jsonrpc-client/src/rpc_impl/mod.rs
crates/astria-celestia-jsonrpc-client/src/rpc_impl/state.rs
crates/astria-celestia-jsonrpc-client/src/serde.rs
crates/astria-celestia-jsonrpc-client/src/state.rs
crates/astria-celestia-jsonrpc-client/src/test_utils.rs
crates/astria-test-utils/Cargo.toml
crates/astria-test-utils/src/lib.rs
justfile

This commit replaces `astria-rs-cnc` with the
`astria-celestia-jsonrpc-client` crate.
The only endpoint currently implemented is
`blob.Submit`, which allows atomically submitting
several data blobs under different namespaces.
**NOTE**: This is still WIP but it wasn't set to draft to get CI going (also WIP).

feat: implement celestia json rpc client

---

crates/astria-conductor/src/block_verifier.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/transaction/signed.rs
crates/astria-sequencer/src/transaction/unsigned.rs

golang doesn't have support for this :( required for https://github.com/astriaorg/go-ethereum/pull/24

fix(sequencer): don't use length-delimited proto serialization

---

containerfiles/Dockerfile

This commit installs rocksdb in the final layer
of the generic containerfile because all binaries
are currently linked to librocksdb.
In addition, as it turns out build args are not expanded in `ENTRYPOINT` lines. To get a stable path that can be used as an argument to `ENTRYPOINT`, this commit crates a softlink to `/usr/bin/local/$TARGETBINARY` and uses that instead.

container: install dynamic libs and fix entrypoint

---

Cargo.lock
Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/src/lib.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/src/telemetry.rs
crates/astria-sequencer/Cargo.toml

This commit changes telemetry to output a human readable format only if connected to a tty, and json otherwise. It also allows configuring env filters via command line arguments in addition to environment variables.
This commit was broken out of #150. It was time to upgrade the tracing setup either way, so it made sense to make it a separate PR.

sequencer-relayer: more sophisticated telemetry setup

---

crates/astria-sequencer-relayer/src/types.rs

The call to `SequencerBlockData::verify_block_hash` performs the same calculation as was done to construct the block hash immediately prior.
So `verify_block_hash` is trivially true and can be skipped.
This was observed while writing #150 but had nothing to do with the PR itself, so was broken out.

sequencer-relayer: remove unnecessary hash

---

.github/workflows/proto.yml
crates/astria-proto/proto/astria/execution/v1alpha1/execution.proto

#195 moved us to using better version naming, this re-enables breaking change checker in checks to ensure we don't push breaking versions.
This change is validated via test breaking change [here](https://github.com/astriaorg/astria/actions/runs/5675193625/job/15380066698)

Enable breaking proto checker

---

.github/workflows/reusable-docker-build.yml

Using the GHCR registry cache speeds up docker builds, cutting by about 1/3 with the default github runners. 
By my testing 30m -> 8m for longest build.

ci: cache container image layers in ghcr

---

.github/workflows/reusable-docker-build.yml
.github/workflows/rust.yml

Introduces BuildJet to our GH actions, utilize 8vCPU for docker builds & 4vCPU for tests. This reduces time for all actions to under 5 minutes.

ci: use BuildJet for faster GH Actions

---

crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/transaction/unsigned.rs

This is a breaking change.
The ethereum whitepaper states that on a transaction:
> nonce: A scalar value equal to the number of transactions sent by the sender
And later:
> the transaction nonce is valid (equivalent to the sender account’s current nonce);
As best I can tell cosmos chains treat [sequences similarly](https://github.com/astriaorg/metro/blob/d12705639f68d5e9d0ec6071748a0a0ec36ec7df/pkg/builder/builder.go#L116), and I don't believe we should differ from these implementations.

sequencer: tx nonce must match account nonce

---

.github/workflows/rust.yml
crates/astria-sequencer-client/src/tests/http.rs

`astria-conductor-test` and `sequencer-relayer-test` no longer exist and can be removed from the clippy exludes list.
Also, clippy should be run against all features.

ci: remove unused excludes, use --all-features everywhere

---

.github/workflows/rust.yml
README.md
crates/astria-conductor/Cargo.toml
crates/astria-gossipnet/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

This commit adds a github workflow job to
standardize toml formatting across the
monorepo. Because contributors use different
editors (some with and some without toml
formatting built in), this should help reduce
churn.
https://github.com/tamasfe/taplo version 0.8.1
is downloaded and put into /usr/local/bin and run
with as `taplo format --check`, failing if some
toml files were not formatted.

ci: check toml formatting

---

Cargo.toml
crates/astria-composer/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml

This commit changes the cargo workspace to use resolver version 2. Furthermore, it reduces the tokio features to the ones actually needed in composer, and fixes sequencer-relayer's tendermint-rpc features (which surfaced because of resolver 2).
Unfortunately, there is no good way to enforce (or check) that the `tokio` dependency only uses its minimal set of necessary features. In fact, tokio could be specified just like `tokio = { workspace = true }`. Due to feature unification all necessary features are set through the `astria-sequencer` dependency.

use cargo resolver 2, fix used features

---

crates/astria-celestia-jsonrpc-client/src/lib.rs

This commit provides the `jsonrpc_call` utility method on `astria-celestia-jsonrpc-client::Error` that returns a jsonrpsee `Option<&ErrorObject<'_>>` only if the underlying is an actual jsonrpc error response.
To be used like so:
```rust
match self.client.blob_get_all(req).await {
Ok(rsp) => rsp,
Err(e) => if let Some(jsonrpc_call) = e.jsonrpc_call() {
println!("jsonrpc returned error response: {}", jsonrpc_call.message());
}
```

feat(celestia-client): add utility function to access jsonrpc error

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-composer/env.example
crates/astria-composer/src/config.rs
crates/astria-composer/src/searcher.rs
crates/astria-composer/tests/blackbox/helper/mock_sequencer.rs
crates/astria-composer/tests/blackbox/helper/mod.rs
crates/astria-sequencer/src/accounts/types.rs

- needed so i can merge #206
- reads sequencer private key from env; decided to do this instead of reading from a file since we already have a .env file, so felt a bit duplicative
- also track nonce for this account. note this PR doesn't add handling if a tx is rejected, so if any tx is rejected for some reason the nonce may get out of whack. will open an issue fix this by either resetting the nonce every sequencer block, or re-submitting transactions with the nonce that was rejected
closes  #215

feat(composer): read sequencer private key from env and track nonce

---

crates/astria-sequencer/src/config.rs
crates/astria-sequencer/src/sequencer.rs

This PR changes the storage type we are using in `sequencer`. It is being changed from `penumbra_storage::TempStorage` to `penumbra_storage::Storage`. I also added a config value to define the path of the penumbra database file.
Resolves #254

sequencer: use penumbra's `Storage` instead of `TempStorage`

---

crates/astria-conductor/src/block_verifier.rs
crates/astria-conductor/src/executor.rs
crates/astria-conductor/src/reader.rs
crates/astria-conductor/src/types.rs
crates/astria-sequencer-relayer/src/data_availability.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs

Update `SequencerBlockData`, `SequencerNamespaceData`, and `RollupNamespaceData` to use a `tendermint::Hash` instead of `Vec<u8>`. This cuts down on the amount of type conversions needed when validating and comparing hashes when trying to execute blocks. This also simplifies and fixes the (de)serialization of all types mentioned.

sequencer: use tendermint hash type instead of opaque bytes

---

crates/astria-composer/tests/blackbox/api.rs
crates/astria-composer/tests/blackbox/composer.rs
crates/astria-composer/tests/blackbox/helper/mod.rs

Implement blackbox tests for composer ingesting from rollups. This is the third of three patches to allow composer to read from multiple rollup, see related issues below.
This patch completes the implementation with a test.
- added `tx_from_two_rollups_are_received_by_sequencer`
- adjusted `mount_broadcast_tx_sync_mock` to take an expected chain ID and check it against the one received in the broadcast tx sync request.
N.A. - this is a test.
https://github.com/astriaorg/astria/pull/277
https://github.com/astriaorg/astria/pull/278
https://github.com/astriaorg/astria/pull/282 (the present PR)

composer: test multiple rollups

---

Cargo.toml

- add tastria-sequencer-ypes crate to Cargo.toml
- should have been done before

fix: add astria-sequencer-types crate to Cargo.toml

---

.github/workflows/docker-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/reusable-success.yml
.github/workflows/test.yml

Makes the success a reusable command, and uses sub names for identification
All the success being the same name causing issues with required jobs if all tests haven't finished.
- move to reusable success action
tested on this pr action workflow running

ci: Update to reusable success, nested names

---

crates/astria-sequencer/src/transaction/mod.rs

this is actually not an issue; the calling function of `execute` already does this:
```rust
let mut state_tx = self
.state
.try_begin_transaction()
.expect("state Arc should be present and unique");
transaction::execute(&signed_tx, &mut state_tx)
.await
.context("failed executing transaction")?;
state_tx.apply();
``` 
closes #317

sequencer: remove todo for issue that's done

---

crates/astria-proto/src/proto/generated/astria.execution.v1alpha2.rs

Regenerate rust protobuf code.
https://github.com/astriaorg/astria/pull/344 was merged without running `cargo test -p astria-proto` and subsequently merging the generated rust, leaving the tests broken.
- Run `cargo test -p astria-proto`, check-in the regenerated rust files.
Not applicable. Tests did not pass before, they pass now.

proto: regenerate

---

crates/astria-sequencer/src/app.rs

remove unneeded `AppHash` alias as there was an `AppHash` type with domain separator and `AppHash` alias
closes #348

fix(sequencer): remove unneeded `AppHash` alias

---

Cargo.lock
crates/astria-sequencer-relayer/src/data_availability.rs
crates/astria-sequencer-validation/Cargo.toml
crates/astria-sequencer-validation/src/proof.rs

Replace all untyped errors in sequencer-validation by typed errors.
`sequencer-validation` has to be made a dependency of `sequencer-client`, which only uses typed errors. Therefore `sequencer-validation` must have typed errors (because otherwise `sequencer-client` would be "infected" by eyre, which would require changing all of sequencer-client to also use eyre :-/ ).
- Replace `eyre` reports by typed errors
- Fix `MerkleTree::prove_inclusion` to actually return an error: the docs said it would error, but it actually panicked if `index` was out of bounds.
- Add eyre error context to sequencer-relayer: because the error in it wasn't properly wrapped, changing the sequencer-validation types caused it to no longer compile
Added a test to check for out of bounds inclusion proof index. The …

sequencer-validation: type errors

---

crates/astria-conductor/src/config.rs

This PR refactors how we load values from the environment so that we have more control on which envars are used.
We can now define the `envar_prefix` we want as well as a `test_envar_prefix` so that we have full control over which envar names should be part of the config.
A user's locally loaded environment should not affect test outcomes.
- added `envar_prefix` argument to `from_environment`
- added `test_envar_prefix` to `populate_environment_from_example`
- I fixed the test that was erroneously failing previously.
- You must now pass in an `envar_prefix` to `Config::from_environment`
closes https://github.com/astriaorg/astria/issues/386

Conductor: fix config loading from environment to have more control

---

crates/astria-conductor/src/executor.rs
crates/astria-conductor/src/types.rs

Allow empty blocks to make it to executor
We added a setting for executor to execute empty blocks in astriaorg/astria#373, however we didn't fix that run short circuits before getting there
- update to allow blocks with no transactions be converted
- add an error if problem converting to block subset
Manually tested with dev-cluster

fix(conductor): continue to execution when block subset empty

---

crates/astria-sequencer/src/transaction/mod.rs

Updated the `check_mempool_nonce` to allow all valid nonces through.
The nonce ensure function was written backwards as an if instead of as an ensure
- changed < to >= for nonce validations

fix(sequencer): Nonces can be equal

---

.github/workflows/docker-build.yml
.github/workflows/reusable-run-checker.yml
CODEOWNERS
justfile

Changes when docker builds run, so they don't run on every pull request.
Docker builds take time and compute resources, are often not necessary.
- change docker builds to run on pull requests only when: a) docker build related files changed b) docker-build tag is on PR
- updates codeowners for build/ci related changes
- fix incorrectly named just command
This PR will have a couple changes added to test correct builds run

ci: run docker builds less frequently + minors

---

.github/workflows/lint.yml
.github/workflows/reusable-run-checker.yml
.github/workflows/test.yml
crates/astria-composer/tests/blackbox/api.rs
crates/astria-conductor/README.md
crates/astria-sequencer-utils/README.md
crates/astria-sequencer/README.md
crates/astria-sequencer/TESTNET.md
specs/conductor.md
specs/data-flow-and-verification.md

Markdown CI was not running, this updates to get it running + fixes markdown that was no longer to spec.
Markdown lint has not been running correctly on CI jobs
- Fix glob issue with CI test
- Update all markdown files
- Update tests that were always running
- Markdown changes do not trigger compilation tests
Ensuring this passes, and pushing some broken changes to make sure runs as well

fix(ci): markdown ci fix

---

Cargo.lock
crates/astria-conductor/Cargo.toml

Updates cargo.toml to cut new release of conductor

release(conductor): conductor 0.6.0 release

---

crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs

Replace `Vec::remove(0)` by `Vec::get(0)` to not panic if executor receives empty blocks from the DA reader.
If the data availability reader filtered all blocks resulting in an empty payload, executor would panic.
- Replace `Vec::remove(0)` by `Vec::get(0).cloned()`.
- Move the entire execution logic into a handler and out of the select arm.
Added a test that ensures the the handler passes and leaves the internal executor state unchanged.

conductor: don't panic on empty blocks

---

crates/astria-sequencer/src/config.rs

tests were failing without `--all-features` (they passed on CI because that's enabled)

fix(sequencer): fix tests without `--all-features`

---

Cargo.lock
crates/astria-composer/src/searcher/executor.rs
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/block_verifier.rs
crates/astria-conductor/src/client_provider.rs
crates/astria-sequencer-client/src/lib.rs
crates/astria-sequencer-client/src/tests/http.rs

After losing its websocket connection to sequener conductor now tries to reconnect up to 1024 times with exponential backoff.
Conductor only tried to reestablish its websocket connection to sequencer up to one time, bailing afterwards. This is not enough to overcome network issues, leading to conductor being unnecessarily flaky and bailing too early.
- use exponential backoff to reestablish the sequencer websocket connection (up to 1024 attempts)
- merge the startup and reconnect logic as they are essentially the same thing.
Testing this is tough and not done here. This is tough to implement and was not done here. Issue to track this: https://github.com/astriaorg/astria/issues/482

conductor: reconnect to sequencer websocket with backoff

---

crates/astria-conductor/src/conductor.rs

Log the exit reports of the long running conductor tasks.
The exit messages of the conductor tasks might contain valuable information why they exited. This is important in case there are race conditions between a task exiting (because e.g. its rx channel is closed), and another task delaying its report why it exited.
- Added events when joining tasks after issuing shutdown signals.
No testable changes.

conductor: log task exit

---

.github/workflows/test.yml
containerfiles/Dockerfile

Update Rust from 1.70 to 1.72 in CI and Docker.
1.70 was giving the error
```bash
cargo +1.70 hack check --all --all-features
info: running `cargo check --all-features` on astria-celestia-jsonrpc-client (1/14)
error: Package `astria-utils v0.1.0 (/Users/astria/dev/astria/astria/crates/astria-utils)` does not have feature `figment`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
error: process didn't exit successfully: `/Users/astria/.rustup/toolchains/1.70-aarch64-apple-darwin/bin/cargo check --all-features --manifest-path crates/astria-celestia-jsonrpc-client/Cargo.toml` (exit status: 101)
```

ci: bump rust to 1.72

---

crates/astria-conductor/local.env.example
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/config.rs
crates/astria-conductor/src/data_availability.rs
crates/astria-sequencer-types/src/namespace.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs

Add a setting that allows rollup user to configure the origin of blocks that get sent to the rollup.
Currently Conductor sends all blocks from all sources (sequencer and DA). Rollup user may want to change this functionality and chose to only ingest blocks from DA and/or the sequencer.
replaces #342 because https://github.com/astriaorg/astria/pull/455 got merged
closes #250 
closes #345

conductor: added execution commit level v2

---

crates/astria-composer/src/searcher/executor.rs
crates/astria-sequencer-types/src/namespace.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs

Report the error backtrace when fetching the initial nonce from the sequencer.
Composer only logged the superficial error reporting what failed, but not why.
- log the error source/backtrace when getting the initial nonce from sequencer
- pretty-print the address using display (instead of debug + a format string)
- unrelated: some fixes because clippy started complaining with the bump to 1.72
Not applicable.
Investigating https://github.com/astriaorg/astria/issues/489 revealed that our events were lacking information to understand what's going on.

composer: report cause of failed nonce fetch

---

Cargo.lock
Cargo.toml

Overrides tendermint-rs with a version that has the new reqwest-based client backported from 0.34 to 0.33.
Enabling TLS lead to issues with the hyper-tls (and ultimately rustls) based tendermint client failing to parse the host certificate. The hyper and rustls versions used by tendermint-rs pre-0.34 were very old.
- Enabling TLS lead to issues with the hyper-tls (and ultimately rustls) based tendermint client failing to parse the host certificate. The hyper and rustls versions used by tendermint-rs pre-0.34 were very old.
Tested with composer and the upcoming astria-cli: both are now able to perform http requests against https endpoints and weren't before.
Surpasses https://github.com/astriaorg/astria/pull/494 which was used for …

use fork of tendermint with backported reqwest client

---

crates/astria-conductor/src/client_provider.rs

Websocket clients to sequencer are never returned to the object pool and instead freshly created
Websocket clients were returned to the object pool even though their underlying websocket driver was long dead. This meant that a new driver never received any requests because its clients were never used, while actors using the old clients immediately errored.
- Implement the `deadpool::managed::Manager::recycle` trait method to always return an error.
- Conductor is now able to communicate after a websocket/tcp resets. It was not able before.

conductor: never recycle websocket clients

---

crates/astria-conductor/src/client_provider.rs

Spawns the tendermint websocket driver as a
dedicated task and reports why it exited/failed.
The websocket driver should immediately start
communicating with the remote host, sending keep-alives etc.
Also, the tendermint websocket driver frequently disconnects, but we are ignoring its return value. We should not do that because it might contain valuable information about why it exited.
- Spawn the websocket driver as a task
- Add error message and backtrace to event emitted after websocket driver exited, but before it returned.

conductor: spawn driver as task and report exit

---

crates/astria-conductor/src/client_provider.rs
crates/astria-conductor/src/sequencer/mod.rs
crates/astria-sequencer-client/src/extension_trait.rs

Conductor attempts to subscribe to the sequencer with a constant backoff instead of failing after the first attempt.
Conductor was unnecessarily flaky - instead of trying to resubscribe repeatedly it failed instantly.
- Remove the exit condition from the sequencer reader on a failed resubscription to new blocks
- Try to repeatedly resubscribe to new blocks with a constant backoff of 10 seconds.
Tested on devnet

conductor: resubscribe with backoff instead of failing

---

crates/astria-conductor/local.env.example

very small fix to have the rollup chain id in conductor example env to match composer's example env rollup chain id (both are now "astriachain")

fix(conductor): update rollup chain id in conductor example env to match composer

---

crates/astria-conductor/src/executor/mod.rs

the logging in executor was unclear with regards to height, I thought the rollup height was being incremented even though a block failed execution, but it's actually logging the sequencer block height. updated to clarify that
n/a
closes #507

fix(conductor): clarify logging in executor

---

crates/astria-cli/src/cli/rollup.rs
crates/astria-cli/tests/integration_test.rs

Fixes bug where a list of genesis accounts was not being parsed correctly when they came from an envar.
- Adds `value_delimiter` to `genesis_accounts` argument 
- Added a list of genesis accounts in an envar to the integration test.
closes https://github.com/astriaorg/astria/issues/511

fix(cli): genesis account lists now being parsed correctly from envars

---

crates/astria-cli/src/types.rs

helm likes to turn big integers into scientific notation, so we serialize as a string to ensure proper parsing in helm land
closes https://github.com/astriaorg/astria/issues/526

cli: refactor network_id to be a string on the serialization side

---

crates/astria-cli/src/cli/rollup.rs

Updates the rollup chart in the CLI
Minor changes to chart made to improve remote deployment.
- update rollup chart version from `0.4.2` to `0.4.3`

Update rollup chart

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/client_provider.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/sequencer/mod.rs
crates/astria-conductor/src/sequencer/sync.rs
crates/astria-sequencer-client/src/extension_trait.rs
crates/astria-sequencer-client/src/lib.rs
crates/astria-sequencer-types/Cargo.toml
crates/astria-sequencer-types/src/lib.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs
crates/astria-sequencer-types/src/test_utils.rs

Fetch missing sequencer blocks before forwarding to the executor actor.
If the websocket connection to sequencer drops temporarily (thus not receiving blocks from the `NewBlocks` jsonrpc subscription), blocks for one or more heights might be missed. This is detected by tracking the expected height of the next sequencer block to be forwarded to the executor actor. If the next block taken from the queue of pending blocks has a height greater than the expected height a resync is triggered and the current block rescheduled in front of the queue of regular pending blocks. This patch reuses the sync-mechanism that is run at startup to fetch a contiguous range of missing sequencer blocks. Only after this "re-sync" is completed will regular submission of blocks resume
- Track the height of …

feat(conductor): add re-sync for missed sequencer blocks

---

Cargo.lock
crates/astria-cli/src/cli/rollup.rs
crates/astria-cli/src/commands/mod.rs
crates/astria-cli/src/commands/rollup.rs
crates/astria-cli/src/types.rs
crates/astria-cli/test-utils/Cargo.toml
crates/astria-cli/test-utils/src/lib.rs

Setting more defaults, making less things required.
Trying to simplify the number of things which must be set, while still enabling more power when needed.
- sequencer block height grab from sequencer
- default network id to `1337`
- Add some docs for commands
Running CLI locally + CI on this PR
closes https://github.com/astriaorg/astria/issues/513

feat(cli): grab block height from sequencer + minimize required create inputs

---

crates/astria-cli/src/cli/rollup.rs
crates/astria-cli/src/commands/rollup.rs
crates/astria-cli/src/types.rs

Adds the hostname flag into CLI, and makes the namespace configurable.
We updated charts, and currently deploying to cloud providers requires manual intervention.
- Added the `--hostname` config flag and `ROLLUP_HOSTNAME` env var
- Added the `--namespace` config flag and `ROLLUP_NAMESPACE` env var
- Updated the `astria-cli rollup deployments list` command to list across all namespaces
Updated automated tests.

feat(cli): add hostname + namespace

---

crates/astria-conductor/src/client_provider.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/data_availability.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/main.rs
crates/astria-conductor/src/sequencer/mod.rs
crates/astria-conductor/src/sequencer/sync.rs

This replaces explicit instrument formatting using the `?` and `%` sigils by the `tracing::Value` impl for `dyn std::error::Error` giving nicer tracing events.
So war we were emitting tracing events for errors like `warn!(error.message = %err, error.cause = ?err, "failed to do something");`, which lead to formatted multiline errors that did not match well with normal tracing subscriber formatting. This patch uses the `tracing::Value` implementation for `std::error::Error` trait objects, giving error backtraces in form of a list and. Unfortunately errors have to be explicitly made into trait objects (either through `&err as &dyn Error` or using a binding like `let error: &dyn Error = eyre_report.as_ref()` for eyre reports).
- Replace all tracing events using `%` and `?` sigils for error …

feat(conductor): replace formatted error backtraces by value impl

---

.github/workflows/test.yml

Upgrades the clippy worker from buildjet-4vcpu-ubuntu-2204 to buildjet-8vcpu-ubuntu-2204
Clippy builds are pretty heavy and far slower than the regular rust builds because they run on a smaller machine.
- Changed the clippy job to run on a bigger buildjet instance.

ci: run clippy, doctest tests on buildjet-8vcpu-ubuntu-2204

---

.github/workflows/docker-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/reusable-success.yml
.github/workflows/test.yml
crates/astria-cli/src/cli/mod.rs

Fixes the "success" reusable job which was always passing.
When migrated to reusable version, started always passing. This fixes, the reusable action didn't have access to the `needs` values.
- Pass in success value.
On PR tests

fix(ci): success test proper reporting

---

.github/workflows/test.yml

Always run doctests if normal rust tests are also ran.
Our CI treated doctests as lints, where they are actually full tests and should be run alongside normal rust tests.
- Removed the lint conditional from the doctest job.

ci: doctests are tests and should not be skipped

---

.github/workflows/lint.yml

Adds a ci linting rule which requires PR be named according to [conventional commit standards ](https://www.conventionalcommits.org/en/v1.0.0/#specification)

ci: require conventional commit naming for PRs

---

.github/workflows/lint.yml

Lint would break on main everytime otherwise.

fix(ci): only run title lint on pull requests

---

crates/astria-celestia-client/src/blob_space.rs
crates/astria-celestia-client/src/client.rs
crates/astria-composer/tests/blackbox/composer.rs
crates/astria-conductor/src/block_verifier.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs
specs/data-flow-and-verification.md

similarly to `action_tree_root`, we need to prove inclusion of `chain_ids_commitment` inside `data_hash` and verify it when receiving `SequencerBlockData`.
we need this to prove that no chain IDs were omitted when writing to DA by an untrusted relayer.
- add `chain_ids_commitment_inclusion_proof` to `SequencerBlockData` and `RawSequencerBlockData`
-  implement `chain_ids_commitment` inclusion proof generation in `SequencerBlockData::from_tendermint_block()`
- implement `chain_ids_commitment` inclusion proof verification inside `SequencerBlockData::try_from_raw`
unit tests
- `SequencerBlockData` written to DA must now contain the `chain_ids_commitment_inclusion_proof`
n/a

fix: implement `chain_ids_commitment` inclusion proof generation and verification

---

Cargo.lock

Updating dependencies that were yanked.
CI

fix: dependency update for yanked ahash deps

---

crates/astria-conductor/src/executor/mod.rs
crates/astria-sequencer/justfile
crates/astria-sequencer/src/app.rs

turns out both `prepare_proposal` and `process_proposal` are called for a proposer node. since we moved transaction execution to prepare/process_proposal, when the proposer called both these functions, execution would fail during `process_proposal` since the state was already updated for post-execution.
see summary.
- track if we're the proposer during the block lifecycle in the `App` struct, and if we are, don't execute transactions during `process_proposal` 
local testing

fix(sequencer): run only `prepare_proposal` if proposer

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs

Conductor now uses the initial commitment state that is pulled when Conductor starts to set the initial sequencer block height more accurately so that sync at startup runs faster.
Basic checks were also put in place to prevent out of order blocks from executing when getting passed to `execute_block`.
When starting up, Conductor was syncing from it's block 1 even if blocks have already been executed on the rollup. This is inefficient. With the implementation of the execution api v1alpha2, the latest executed block from the rollup can now be pulled and the sync can start where normal execution left off.
- Added checks to `execute_block` to prevent out of order execution
- Hight of latest soft block is now pulled from rollup and used to set the block height that sync starts at.
Manually …

feat(conductor): added commitment grab to better set sync start height

---

.github/workflows/test.yml
crates/astria-sequencer-relayer/src/api.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs
crates/astria-sequencer-relayer/tests/blackbox/main.rs

Implement all clippy pedantic suggestions for relayer, activate in CI.
These changes were made for consistency. All repositories should be checked with clippy pedantic.
- Run `cargo clippy -- -W clippy::pedantic`, fix all nags
- Remove `astria-sequencer-relayer` from the `--exclude` list in the clippy CI.
All tests still pass. No extra tests are necessary because no structural refactoring took place.
Closes https://github.com/astriaorg/astria/issues/571

chore(relayer): implement clippy pedantic suggestions

---

crates/astria-celestia-client/src/client.rs
crates/astria-celestia-client/src/lib.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/data_availability.rs
crates/astria-sequencer-relayer/src/relayer.rs

Updates `sequencer-relayer` and `conductor` to use the attached sequencer nodes `chain-id` for  blob namespace.
We were using a constant for the namespace, which would mean when reading from a production network that sequencer blobs might need to be filtered further based on chain-id, accessing and filtering data without any savings for cost to submit (still would be seperate relayers). This makes it such that our various chains through regenesis and all won't have to do this filtering
- Sequencer-relayer sequencer blob namespace derived from sequencer block chain ID on header
- Conductor grabs chain id at startup from a block on rpc sequencer.
- Removed the default namespace
CI/CD + manual testing in dev-cluster
- Posted data blobs to celestia will not match from previous releases.

fix(conductor, relayer): use sequencer chain id for sequencer blobs

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml

Cut new releases of conductor + relayer after updating celestia namespace logic.

chore(conductor, relayer): release conductor 0.9.0, sequencer-relayer 0.7.0

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/mod.rs

Replace `Executor::new()` by `Executor::builder()....build()` because the constructor was getting too lengthy.
This uses the type-state pattern to avoid having to check if all required builder fields are set (with the fields all being `Option<T>`). This is more verbose in the executor's type signature and field-setters, but avoids the need for error handling.

refactor(conductor): replace executor constructor by type state builder

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Release cuts, major releases due to fundamental change to the merkle tree shape.

chore(conductor, relayer, sequencer): release 0.10.0 conductor, 0.8.0 relayer, and 0.6.0 sequencer

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
containerfiles/Dockerfile
crates/astria-celestia-client/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/data_availability.rs
crates/astria-proto/Cargo.toml
crates/astria-proto/src/proto/generated/astria.execution.v1alpha1.rs
crates/astria-proto/src/proto/generated/astria.execution.v1alpha2.rs
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs
crates/astria-sequencer-types/Cargo.toml
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/service/mempool.rs
crates/astria-test-utils/src/mock/geth.rs

Bump all dependencies with a special focus on penumbra, celestia, tendermint
PR https://github.com/astriaorg/astria/pull/579 requires a newer version of penumbra, which in turn requires updating prost and tonic (and their build crates), and a new minimum rust version of 1.73 (due to libp2p setting that in https://github.com/libp2p/rust-libp2p/pull/4692 which we transitively depend on).
As this change triggers a cascade of updated dependencies it makes sense to update everything in one go.
- Set all penumbra dependencies to tag v0.63.1
- Update all tendermint dependencies to version 0.34
- Remove the backported tendermint patch to fix certificate resolution
- Set celestia-node-rs to their recent master (which also updates libp2p and hence demands a msrv of 1.73)
- Fix the breakage in the …

chore: bump all dependencies (mainly penumbra, celestia, tendermint)

---

crates/astria-celestia-client/src/blob_space.rs
crates/astria-celestia-client/src/client.rs
crates/astria-conductor/src/block_verifier.rs
crates/astria-conductor/src/data_availability.rs
crates/astria-sequencer-types/src/sequencer_block_data.rs

Enforce invariants when constructing sequencer blobs.
The sequencer blob type `SequencerNamespaceData` that was written to and read from celestia was treated as a dumb container, delegating consistency checks to downstream users (for example, to the `block_verifier` module in `astria-conductor`). In the spirit of making invalid states unrepresentable, this patch introdues a `RawSequencerNamespaceData` as the dumb (de)serialization container, from which a verified `SequencerNamespaceData` can be built. In particular, the following invariants are upheld at construction, rejecting a conversion otherwise (`SMD` stands for `SequencerNamespaceData` and `SMD.field` refers to the `field` of the same):
1. `SMD.header.data_hash` must be set
2. `SMD.block_hash` must match the result of …

refactor: enforce sequencer blob invariants, simplify conductor

---

Cargo.lock
crates/astria-cli/Cargo.toml
crates/astria-cli/src/cli/rollup.rs
crates/astria-cli/src/cli/sequencer.rs
crates/astria-cli/src/commands/mod.rs
crates/astria-cli/src/commands/rollup.rs
crates/astria-cli/src/commands/sequencer.rs

Adds a couple commands (transfer, nonce), provides default sequencer rpc for all, and streamlines the ways to access balance.
Had to interact with the sequencer and needed more commands, found incongruence with defaults provided for rollups and found the balance `get` command to be counter intuitive.
Note that specifically did not remove the balance get command for backwards compatibility, docs.
- provide default sequencer rpc url
- provide `sequencer account balance` command as alternative to `sequencer balance get`
- adds `sequencer account nonce` command
- adds `sequencer transfer` command
Manually tested

feat(cli): improve sequencer command set

---

crates/astria-sequencer/src/app.rs

logging every single tx before executing each of them is bad for logging.
- don't log the entire block's txs

fix(sequencer): fix instrument logging not to log every tx

---

crates/astria-sequencer-types/src/abci_code.rs
crates/astria-sequencer/src/service/mempool.rs

we saw that on devnet, submitting a tx that exceeds the `max_tx_bytes` per block (~22mb) will result in it hanging around the mempool forever, as it cannot end up in a block, and causes all txs to remain pending. this is bad, and we need to ensure txs that are too large don't end up in the mempool to begin with.
the size chosen (250kb) was based on @jbowen93 's comment:
> Celestia has 2MB blocks and I believe we batch up to 5 Astria blocks to Celestia. So if we wanted to be conservative like 250KB, but we could go as high as 400KB.
we can change this later if needed, but this is a good starting point.
- add a check in `CheckTx` that rejects the tx if it's larger than 250kb
devnet (after)
- txs >250kb will be rejected

fix(sequencer): cap tx size at 250kb

---

.github/workflows/test.yml

previous version appeared to have been pulled, causing a 404?? https://github.com/foundry-rs/foundry/tags 
see https://github.com/foundry-rs/foundry-toolchain/issues/35
this updates it to an older version that doesn't look like it will get pulled.

fix(ci): pin foundry to different version

---

Cargo.toml
crates/astria-sequencer/Cargo.toml

astria-proto doesn't require the penumbra-ibc `component` feature (on by default). 
- turn the `component` feature off by default for penumbra-ibc, enable it for sequencer only

chore: update penumbra-ibc features

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/sequencer/mod.rs

This patch adds missing error context to fallible operations.
Errors should not be returned with context.
- Add error context with `wrap_err` where missing
- Rename `get_*` to `calculate_*` methods because that's what they do
- Let `calculate_*`methods returned a tendermint `Height` to avoid moving in and out of types.
No logic changes, tests still pass.
Follow-up to https://github.com/astriaorg/astria/pull/617

fix(constructor): add error context, simplify type conversions

---

crates/astria-conductor/src/executor/mod.rs

Return an error when executing blocks fails because this means the block chain state is no longer reconcilable.
- Return errors rather than just logging them when encountering errors during block execution.
- Refactor shutdown reporting in executor.
No testable changes

fix(conductor): fail hard when executing blocks fails

---

.github/workflows/lint.yml

Adjusts the proto breaking change linter to use the new `proto/` root level directory.
Moving the protobuf spec out of `astria-proto` to `proto` broke the CI job checking for breaking changes. This breakage of CI was expected and this fixes it.
- Change the input to the breaking change proto linter to check against `main:proto/`
Follow-up to https://github.com/astriaorg/astria/pull/629

fix(ci): adjust input to proto breaking change linter after refactor

---

.github/workflows/lint.yml
README.md
justfile
proto/README.md
proto/astria/execution/v1alpha1/execution.proto
proto/astria/execution/v1alpha2/execution.proto
proto/astria/sequencer/v1alpha1/asset.proto
proto/astria/sequencer/v1alpha1/block.proto
proto/astria/sequencer/v1alpha1/celestia.proto
proto/astria/sequencer/v1alpha1/data.proto
proto/astria/sequencer/v1alpha1/merkle.proto
proto/astria/sequencer/v1alpha1/transaction.proto

Cleans up some justfile, updates to check protos against buf, updates readmes,  and adds default formatting of proto files. 
We moved protos, this caused an issue with breaking changes. Additionally we had non consistent proto formatting.
- remove no longer needed just commands
- restructure fmt & lint to take args, add an `all` which is default
- add buf format, run against the repo
- use the buf posted files for breaking changes checks.
- update readmes
CI/CD tests, manual testing commands

ci(proto): add proto formatting, cleanup justfile

---

.github/workflows/build.yml

Last version always ran as dry run, this fixes while still allowing workflow dispatches on custom builds to ensure binaries build
Testing github actions is cursed, and didn't realize wouldn't upload previously.
- makes tag checking generic
- moves cli to it's own build with check for if it should run.
- dry run checked based on tag instead of event
- adds a name

ci(cli): fix archive upload

---

crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/service/consensus.rs

we were ignoring ABCI events (bad). needed to fix this for hermes testing
- return ABCI events emitted in `deliver_tx`
i ran it with hermes, this fixes errors due to no events

fix(sequencer): fix ABCI event handling

---

crates/astria-sequencer/src/sequencer.rs

Spawns the server task with tokio and aborts the server properly when a signal is received.
Added a oneshot channel and created a tokio task inside `run_until_stopped` with a `server_handle.abort()` at the before return.
Ran it and the server shuts down properly.
closes #667

refactor(sequencer): call abort on ABCI server on signal

---

crates/astria-sequencer-utils/src/config.rs
crates/astria-sequencer-utils/src/genesis_parser.rs
crates/astria-sequencer/justfile

utils to set the chain ID in the cometbft genesis.json file.
need it for ibc testing (we need to set the chain id when starting hermes) this makes my life a lot easier, cause otherwise it picks a random chain ID.
- add `--chain-id` to sequencer genesis utils which sets the `chain_id` field in the cometbft genesis file to the given string
unit tests + i ran it (`just run-cometbft` and `cat ~/.cometbft/config/genesis.json`)

feat(sequencer-utils): add `--chain-id` to sequencer genesis utils

---

crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/service/consensus.rs

Updates all consensus API calls to have specifically chosen data in the spans, and omits anything but context of function from children (ie handle has context, the funciton it calls doesn't need it)
Debugging sequencer is hard, spans from handle request on process proposal were unreadable. Similar changes made in sequencer for debugging fix. 
- Update all functions to skip_all with specific fields logged

chore(sequencer): update instrumentation for all consensus & app functions

---

crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-core/src/execution/mod.rs
crates/astria-core/src/execution/v1alpha2/mod.rs
crates/astria-core/src/lib.rs

Defined idiomatic execution types in `astria-core`, refactored and streamlined executor code.
The conversion method for commitment states would panic, it returns an error now and the conversion happens in `astria-core`, similar to the sequencer types.
There was also a lot of unused code in the execution service extension trait, and unnecessary redirection when updating commitment states (single-use functions that make reading the code opaque). All of that has been removed. 
- Defined `Block` and `CommitmentState` in `astria-core` with conversion methods from the raw generated prost types.
- Changed the exection service extension crate to a newtype wrapper on `ExecutionServiceClient<Channel>` (it used to be that, but the newtype wrapper fits better in this instance)
- Removed a few methods …

refactor(conductor): use idiomatic types, streamline some executor code

---

crates/astria-sequencer/src/app.rs

Adds a limit to the amount of sequenced data which is allowed into a single block, important to avoid overflowing celestia + ensuring that we can propogate full blocks successfully.
We had a limit on transaction sizes but not on aggregate of transactions, this adds a basic limit of 256kb for total sequenced data. This size was chosen based on Celestia block size with max of ~5-6 blocks per celestia block completely filled blocks would use up ~60% of 2mb Celestia block size.
- Adds a limitation to execute block transactions to limit the number of bytes that make it into full block.
- This a network upgrade, all future proposals will be rejected if they have too many txs. However, old blocks will still be successfully executed through blocksync.
closes …

feat(sequencer)!: max sequencer bytes per block limit

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Cut new releases for use in new dusk release.
sequencer v0.8.0, conductor v0.11.1, composer v0.3.1, sequencer-relayer v0.9.1

build(sequencer, conductor, composer, relayer): cut releases

---

crates/astria-conductor/src/executor/tests.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/mod.rs
crates/astria-sequencer/src/app.rs

add transaction hashes to match what cometbft/hermes are logging/use internally.
- add `SignedTransaction::sha256_of_proto_encoding()` method
unit test + I ran it and cometbft/hermes get the same tx hashes.
closes https://github.com/astriaorg/astria/issues/476

feat(core): add `SignedTransaction::sha256_of_proto_encoding()` method

---

Cargo.lock
crates/astria-cli/Cargo.toml
crates/astria-cli/src/cli/mod.rs

release new cli version which points to dusk-3
We are launching a new devnet, and cli should point to the correct rpc by default

chore(cli): bump for dusk-3

---

Cargo.lock
crates/astria-cli/Cargo.toml
crates/astria-cli/README.md
crates/astria-cli/src/cli/rollup.rs
crates/astria-cli/src/types.rs

Refactors the cli to serialize the rollup config as yaml to match what is expected in the rollup chart's values.yaml.
Genesis accounts weren't getting funded in RaaS because the shape of values.yaml changed.
- changed generated yaml shape
- updated unit and integration tests
The api of the cli did not change

fix(cli)!: refactor yaml serialization to match format in rollup's values.yaml

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/data_availability/builder.rs
crates/astria-conductor/src/data_availability/mod.rs

Adds a type-state builder to construct a celestia reader.
The `new` constructor was getting unwieldy because it had too many arguments.
- Introduce a `data_availability::Builder` type following the type-state builder pattern 
- Remove the `data_availability::Reader::new` constructor in favor of the builder
No functional changes to celestia reader construction, only shuffling code around.
Part of #691

refactor(conductor): use builder to construct celestia reader

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/data_availability/builder.rs
crates/astria-conductor/src/data_availability/mod.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/src/sequencer/mod.rs
crates/astria-conductor/src/sequencer/sync.rs

Splits the legacy "executor command" channel into separate channels for the celestia and sequencer reader sending their blocks to the executor.
This allows for a cleaner implementation with the celestia/sequencer readers being completely agnostic to each other where before they had to be wrapped in a common enum.
Furthermore it allows separate back pressure on both channels so that frequent sequencer blocks don't flood out celestia blocks (although this is not currently implemented).
- Removed the common "executor command" mpsc channel, replace by two separate mpsc channels.
No functional changes other than using two different channels.

refactor(conductor): use separate channels for celestia, sequencer blocks

---

Cargo.lock
crates/astria-celestia-client/src/client.rs
crates/astria-conductor/Cargo.toml
crates/astria-conductor/local.env.example
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/data_availability/block_verifier.rs
crates/astria-conductor/src/data_availability/builder.rs
crates/astria-conductor/src/data_availability/mod.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-sequencer/Cargo.toml
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/display.rs
crates/astria-telemetry/src/lib.rs

The celestia reader task only forwards blocks to the executor if their heights are in sequential order.
As part of the changed contract the sequencer and celestia readers forward their blocks to the executor only if they are in sequential order of the sequencer heights recorded inside them.
- Introduce a block cache that yields a new block with height H only if it has previously yielded a block with height H-1
- Change the http-based celestia client to websocket
- Remove polling celestia for new blocks at fixed interval times
- Subscribe to new celestia headers, extracting the newest celestia height
- Add a `ReconstructedBlockStream` that acts as a buffered queue fetching celestia blobs at the the height obtained from the header subscription
No explicit tests. This must be tested …

feat(conductor)!: forward firm blocks read from celestia in sequential order

---

crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/celestia/mod.rs

Concurrently fetch objects (block hash, validator set, commit) to verify sequencer blocks reconstructed from celestia.
Block verifier used to sequentially query sequencer for the necessary objects to verify a block derived from celestia blobs. While this saves network IO, it takes 3 times as long to wait for the objects.
- Start 3 concurrent futures to fetch the necessary objects from sequencer to validate blocks derived from celestia blobs.
No substantial changes. Instead of fetching one after the other 3 futures are ran concurrently.

feat(conductor): fetch objects for verifying blocks concurrently

---

crates/astria-conductor/src/block_cache.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/src/executor/track_state.rs
crates/astria-conductor/src/sequencer.rs
crates/astria-core/src/execution/v1alpha2/mod.rs
crates/astria-core/src/sequencer/v1alpha1/block.rs
crates/astria-core/src/sequencer/v1alpha1/test_utils.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs

Refactor executor to the stricter contract, expecting firm (from celestia) and soft (from sequencer) blocks to be in strict sequential order.
Enforcing a contract that the celestia and sequencer readers only forward blocks in strict sequential order of heights makes the executor implementation much simpler.
- executor expects to receive firm/soft blocks in strict sequential order
- soft blocks are dropped if they are too old
- old firm blocks, or soft/firm blocks that lie in the future violate the contract between the executor and {celestia, sequencer}-readers and lead to conductor aborting
- move storage of blocks pending finalization into the `execute_soft` handler
The executor tests have been updated to support various scenarios of receiving old blocks, out of order blocks, new blocks …

refactor(conductor): adapt executor to sequential firm, soft blocks

---

crates/astria-conductor/src/block_cache.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/src/sequencer.rs

Sync the executor commitment state and sequencer reader so that it only fetches and forwards blocks at the current level.
Soft blocks should only be read from the sequencer and forwarded to the executor if the executor expects them. This patch ensures that obsolete heights are not fetched from sequencer (heights that have already been firmly confirmed).
This also lays the groundwork for allowing sequencer syncing and block forwarding to start at a later height than the firm block sync (although not implemented in this patch).
- wrap the executor commitment state in a watch channel
- monitor the executor state in the sequencer reader
- drop obsolete heights from both the block cache and the height reader
This interaction should be tested end to end.
Part of …

feat(conductor): sync executor commitment state with sequencer reader

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-conductor/local.env.example
crates/astria-conductor/src/celestia/builder.rs
crates/astria-conductor/src/celestia/mod.rs

This patch changed blob-fetching to use a http client. The websocket subscription is still used for fetch the latest celestia header (and hence height).
Reusing the same websocket client for jsonrpsee subscriptions and simple methods requires some complex client pool + resetting logic. Using the websocket client for the subscription only and http clients for fetching blocks allows to simplify this significantly.
- Add a http client to the `celestia::Reader`
- fetch celestia blobs using the http client instead of the websocket client
- update the URI scheme of the celestia node API depending on whether the websocket or http clients are to be constructed

feat(conductor): use http client to fetch celestia blobs

---

Cargo.lock
Cargo.toml
containerfiles/Cargo.toml
crates/astria-celestia-client/Cargo.toml
crates/astria-conductor/local.env.example
crates/astria-conductor/src/celestia/builder.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/config.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/src/sequencer.rs
crates/astria-core/Cargo.toml
crates/astria-core/src/execution/v1alpha2/mod.rs
crates/astria-core/src/generated/astria.execution.v1alpha2.rs
proto/astria/execution/v1alpha2/execution.proto
specs/execution-api.md

Adds a genesis info RPC to the executor v1alpha2 API and initializes conductor using it.
Certain information about the rollup should be considered a core part of the rollup definition, but was done through environmental variable configuration making it harder to spin up nodes that follow the same rules.
- Create `GenesisInfo` protos
- Added idiomatic types to `astria-core`
- Remove fields from config that are now derived from genesis info
- Initialize the executor actor in terms of the genesis info and propagate it to the celestia and sequencer readers
Updated executor tests to still pass. Rest has to be tested end-to-end.
- Requires an updated rollup node to implement the genesis info RPCs

feat(conductor, proto): add genesis info RPC, initialize in terms of it

---

crates/astria-cli/src/commands/sequencer.rs
crates/astria-composer/src/searcher/collector.rs
crates/astria-composer/src/searcher/executor/bundle_factory/tests.rs
crates/astria-composer/src/searcher/executor/mod.rs
crates/astria-composer/src/searcher/executor/tests.rs
crates/astria-composer/src/searcher/mod.rs
crates/astria-core/src/generated/astria.sequencer.v1alpha1.rs
crates/astria-core/src/sequencer/v1alpha1/block.rs
crates/astria-core/src/sequencer/v1alpha1/mod.rs
crates/astria-core/src/sequencer/v1alpha1/test_utils.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/action.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/mod.rs
crates/astria-sequencer-client/src/tests/http.rs
crates/astria-sequencer/src/accounts/action.rs
crates/astria-sequencer/src/accounts/ics20_withdrawal.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/authority/action.rs
crates/astria-sequencer/src/mint/action.rs
crates/astria-sequencer/src/proposal/commitment.rs
crates/astria-sequencer/src/sequence.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/transaction/action_handler.rs
crates/astria-sequencer/src/transaction/mod.rs
proto/astria/sequencer/v1alpha1/transaction.proto

as title says. this is so fees can be set per-action instead of per-transaction. 
- move fee asset from `UnsignedTransaction` to `SequenceAction` and `TransferAction` 
- fee asset was only moved to `SequenceAction` and `TransferAction` as other actions don't have any fee payment, so it's unneeded.
unit tests
- `UnsignedTransaction`, `SequenceAction`, and `TransferAction` types are changed.
closes #714

refactor(core)!: move fee asset from `UnsignedTransaction` to `SequenceAction` and `TransferAction` 

---

crates/astria-conductor/src/celestia/builder.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/src/sequencer.rs

Added an `executor::Handle` type to send blocks, read state.
The previous implementation required too much manual plumbing to set up connections to the executor. A handle to a long running task is a more elegant and idiomatic solution. It also allows to ensure at the type-level that a `Handle::wait_for_init -> Handle<StateIsInit>` is called prior to reading its state and sending data to it because all methods to do so are only implemented on `Handle<StateIsInit>`.
- Introduce an `executor::Handle<T>` type to interact with the `Executor`.
- Move all send channels out of the executor and into the Handle
- Introduce `StateIsInit` and `StateNotInit` marker types to ensure the executor state is initialized (which is the case when it read the genesis info and commitment state off its rollup …

refactor(conductor): interact with executor via handle

---

crates/astria-sequencer/src/accounts/component.rs
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/authority/component.rs
crates/astria-sequencer/src/genesis.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/transaction/mod.rs
crates/astria-sequencer/test-genesis-app-state.json

as title says, make modifying IBC clients/connections/channels permissioned. this allows only a specific key (should be the key used by hermes) to send `IbcRelay` actions.
we probably don't want IBC channels being arbitrarily opened at this time.
- add `ibc_sudo_address` to genesis
- store this in state
- only allow `IbcRelay` actions from this address
unit tests
- updates state by adding `ibc_sudo_address`
closes #720

feat(sequencer)!: add `ibc_sudo_address` to genesis, only allow `IbcRelay` actions from this address

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-composer/local.env.example
crates/astria-composer/src/config.rs
crates/astria-composer/src/lib.rs
crates/astria-composer/src/main.rs
crates/astria-composer/src/searcher/executor/tests.rs
crates/astria-composer/tests/blackbox/helper/mod.rs
crates/astria-conductor/local.env.example
crates/astria-conductor/src/config.rs
crates/astria-conductor/src/main.rs
crates/astria-sequencer-client/Cargo.toml
crates/astria-sequencer-relayer/local.env.example
crates/astria-sequencer-relayer/src/config.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs
crates/astria-sequencer/local.env.example
crates/astria-sequencer/src/config.rs
crates/astria-sequencer/src/main.rs
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/lib.rs

Export trace data as opentelemetry, replacing the tracing json and pretty-print formatting subscribers.
We want to export our trace data in a formalized way, targeting observability platforms that understand the opentelemetry protocol (OTLP).
If the opentelemetry-otlp has hard-coded env vars that are always read at runtime to configure it. These are (see https://github.com/open-telemetry/opentelemetry-rust/blob/4e80e3a2ebf96a166917b169f7d27e44e83cd3da/opentelemetry-otlp/src/span.rs#L30-L42):
+ `OTEL_EXPORTER_OTLP_ENDPOINT`: to set the OTLP endpoint
+ `OTEL_EXPORTER_OTLP_TRACE_ENDPOINT`: to set the trace OTLP endpoint (taking precedence over the general one)
+ `OTEL_EXPORTER_OTLP_TRACE_TIMEOUT`: to set the timeout for the backend to process span batches
+ …

feat(telemetry)!: use opentelemetry

---

Cargo.lock
Cargo.toml
crates/astria-celestia-client/src/client.rs
crates/astria-celestia-client/src/metrics_init.rs
crates/astria-sequencer-relayer/src/metrics_init.rs
crates/astria-sequencer-relayer/src/relayer.rs
crates/astria-telemetry/Cargo.toml

Upgraded the metrics + exporter crates to latest versions.
Previous version of metrics crate had dependency restrictions which were in conflict with cnidarium. This has been fixed.
- upgrade to metrics 0.22.1
- upgrade metrics-prometheus-exporter to 0.13.1
- update metrics usages to work with newest releases.
closes https://github.com/astriaorg/astria/issues/748

chore: upgrade metrics to latest

---

.github/workflows/reusable-run-checker.yml
Cargo.lock
crates/astria-telemetry/Cargo.toml

Updates docker builds to run anytime cargo.lock changes to ensure new dependencies and linkages don't break docker, and fixes current issue with docker builds by disabling unused feature in prometheus exporter.
Docker builds are broken in main, due to a deeply nested openssl dependency.
- Only use required features of prometheus exporter
- Update to run docker builds during PR anytime Cargo.lock changes.
Docker build CI

fix(ci): fixes docker builds

---

crates/astria-composer/local.env.example
crates/astria-composer/src/config.rs
crates/astria-composer/src/main.rs
crates/astria-composer/src/searcher/executor/tests.rs
crates/astria-composer/tests/blackbox/helper/mod.rs
crates/astria-conductor/local.env.example
crates/astria-conductor/src/config.rs
crates/astria-conductor/src/main.rs
crates/astria-sequencer-relayer/local.env.example
crates/astria-sequencer-relayer/src/config.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs
crates/astria-sequencer/local.env.example
crates/astria-sequencer/src/config.rs
crates/astria-sequencer/src/main.rs
crates/astria-telemetry/src/lib.rs

Adds pretty printing to stdout to all services.
The move to OTEL in https://github.com/astriaorg/astria/pull/727 lead to excessively noisy stdout. While useful as a backup mechanism in deployments, it makes it difficult for humans to read.
- add the `pretty_print` and `set_pretty_print` methods to the telemetry builder; if enabled, trace data will be written in a human readable format instead of JSON formatted OTEL traces.
- add the `<service>_PRETTY_PRINT` env var and config to all services taking the values `true` or `false` to enable/disable pretty printing.
- document the new env var and the `NO_COLOR` env var which disables ANSI escape characters from being emitted (makes sharing logs easier)
All services were started with the new env var set. The services were emitting …

feat!: add pretty-printing to stdout

---

crates/astria-core/src/generated/astria.sequencer.v1alpha1.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/action.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/fee_asset_change.rs
crates/astria-sequencer/src/lib.rs
crates/astria-sequencer/src/state_ext.rs
crates/astria-sequencer/src/transaction/mod.rs
proto/sequencerapis/astria/sequencer/v1alpha1/transaction.proto

as title says, implement ability to update fee assets using sudo key.
need to be able to update the assets allowed for fee payment while the chain is running.
- add `FeeAssetChangeAction` which represents the addition or deletion of an authorized fee asset
- ensure that at least one asset has to be allowed for fee payment (should we make it impossible to delete the default asset? probably?)
unit tests
closes #731

feat(sequencer): implement ability to update fee assets using sudo key

---

crates/astria-conductor/src/celestia/mod.rs

Updates to keep the client alive so that the subscription is kept alive.
Websocket connection was terminated after retry return, causing subscription to fail.
- Return both subscription + client when subscribing to celestia headers.
Built and manually run in dev-cluster

fix(conductor): keep wsclient alive

---

.github/workflows/build.yml
.github/workflows/docker-build.yml
.github/workflows/reusable-build.yml
.github/workflows/reusable-docker-build.yml

Enables workflow dispatches to build old tags for docker and binaries with newer workflows, fixes the binary to build composer correctly.
We didn't build composer correctly last release, want to cut on that tag, and want some flexibility when workflow files don't work as intended.
- fix binary build
- add ability to docker & binary builds to checkout old refs.
Will need to be tested after approval

fix(ci): build composer, and allow builds on old tags

---

.github/pull_request_template.md

Update the PR template to list out metrics added.
We now support adding metrics cleanly in the monorepo and adding them is notable for PRs.
- Modify issue template

chore(ci): add metrics to pr template

---

crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs

Check that the host response to `astria.execution.v1alpha2.ExecuteBlock` fulfills the contract (namely, that the number in the response is +1 the current number tracked by conductor).
Conductor implicitly checked the contract by enforcing that the blocks received from sequencer and/or celestia have the expected rollup block number. There was no test however that the execution API server (i.e. the rollup node) responds with the expected block number. This lead to confusing error logs.
- Assert that the host response to the `astria.execution.v1alpha2.ExecuteBlock` RPC is as expected.
Added unit tests to check that the assertion is correct.

feat(conductor): assert host fulfills execution API contract

---

crates/astria-sequencer-relayer/src/metrics_init.rs
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/read.rs
crates/astria-sequencer-relayer/src/relayer/write.rs

Adds metrics to relayer.
Some metrics were not ported when refactoring relayer in https://github.com/astriaorg/astria/pull/769, some other metrics did not make sense where they were.
- Add new metrics to relayer
- 
- `astria_sequencer_relayer_blobs_per_celestia_tx`
- `astria_sequencer_relayer_celestia_submission_latency`
- `astria_sequencer_relayer_sequencer_block_fetch_failure_count`
- `astria_sequencer_relayer_sequencer_height_fetch_failure_count`

fix(relayer): add metrics

---

Cargo.lock
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/local.env.example
crates/astria-sequencer-relayer/src/api.rs
crates/astria-sequencer-relayer/src/config.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/helper.rs
crates/astria-sequencer-relayer/tests/blackbox/main.rs

Lets sequencer-relayer bind to a configurable socket address (instead of localhost + a configurable port).
It is best practice to provide a socket address which a service is supposed to bind so that an operator can specify any IP range and network interface, and not restrict their choice to the loopback device. Coincidentally, this makes it work with ipv6 without needing any extra work.
- Add the `api_addr` field of type `String` to the sequencer relayer config
- Add corresponding `ASTRIA_SEQUENCER_RELAYER_API_ADDR` to example config env file
- Remove `rpc_port` from config and `ASTRIA_SEQUENCER_RELAYER_RPC_PORT` from example config env file
- Update API server constructors, tests
Added a test to check readyz and degraded healthz.
- Changed sequencer-relayer configuration

feat(relayer)!: provide address, not port, to serve API requests

---

Cargo.lock
Cargo.toml
crates/astria-core/src/sequencer/v1alpha1/transaction/action.rs
crates/astria-sequencer/Cargo.toml

Updated to latest penumbra dependencies, and updated one crate identified with `cargo audit`

chore: update dependencies

---

README.md
crates/astria-core/README.md
proto/README.md
tools/protobuf-compiler/README.md

astria-proto repo was renamed to astria-core in https://github.com/astriaorg/astria/pull/644 . This PR addresses the corresponding README changes to change `astria-proto` to `astria-core`
The [https://github.com/astriaorg/astria/tools/protobuf-compiler/README.md](https://github.com/astriaorg/astria/tools/protobuf-compiler/README.md) includes the path which points to where the generated code for the protobufs resides. It points to a stale `astria-proto` link which can be confusing to new developers looking at the codebase. The other README changes come as a result of this observation. 
- Updates to READMEs
No need of testing
No need of metrics
No breaking changes
closes

chore(core): Update docs to reference astria-core instead of astria-proto

---

Cargo.lock
crates/astria-core/src/generated/astria.sequencer.v1alpha1.rs
crates/astria-core/src/sequencer/v1alpha1/account.rs
crates/astria-core/src/sequencer/v1alpha1/asset.rs
crates/astria-core/src/sequencer/v1alpha1/block/mod.rs
crates/astria-core/src/sequencer/v1alpha1/celestia.rs
crates/astria-core/src/sequencer/v1alpha1/mod.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/action.rs
crates/astria-core/src/sequencer/v1alpha1/transaction/mod.rs
crates/astria-sequencer-client/src/extension_trait.rs
crates/astria-sequencer-client/src/tests/http.rs
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/api_state_ext.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/asset/state_ext.rs
crates/astria-sequencer/src/authority/state_ext.rs
crates/astria-sequencer/src/bridge/init_bridge_account_action.rs
crates/astria-sequencer/src/bridge/state_ext.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/ibc/ics20_transfer.rs
crates/astria-sequencer/src/ibc/state_ext.rs
crates/astria-sequencer/src/proposal/commitment.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-telemetry/src/display.rs
proto/sequencerapis/astria/sequencer/v1alpha1/block.proto

various fixes https://github.com/astriaorg/astria/pull/787 instead of review comments:
+ prefer `into_parts` instead of `into_values`, and `*Parts` types with public fields into of tuples
+ rename `header -> cometbft_header` to make the difference to the new `SequencerHeader` type explicit
+ prefer `#[source]` over `#[from]` in thiserrors (`From::from` with `?` was not used anyway).
+ replace all `Err(anyhow!())` with `bail!`
+ prefer non-allocation hex-encoding vs `hex` crate
+ bump borsh to stable version 1
+ make public fields private
+ make implicit allocations explicit

review fixes for #787

---

crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/submission.rs

Warns if pre- and post-submission files are inconsistent, but doesn't exit and instead starts relaying from the state recorded in the post-submission file.
Sequencer-relayer refuses operation if pre- and post-submission files provided via env vars are inconsistent. This inconsistency happens if a submission was started but not completed. As sequencer-relayer lacks graceful shutdown, this is guaranteed to happen on a ragular basis.
For most expected operations this patch means that a double-submission from the last state might occur, which is a cost we are willing to accept.
Note that if sequencer-relayer gets killed while *writing* either file and the file getting corrupted, then relayer will refuse operation on a subsequent restart.
- Warn if the pre-submission and post-submission states …

feat(relayer): warn if submission tracking is inconsistent, but continue operation

---

crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/tests.rs

Simplifies mapping Celestia heights to Sequencer heights by adding the source Celestia height to final type that contains the reconstructed sequencer block information. Fixes an assertion (and panic) being triggered by making it unecessary.
Conductor kept a map of `sequencer_height -> celestia_height` to track which blobs contained which sequencer height. This implementation was unnecessary and error prone, and ultimately out-of-sync with the rest of the Celestia reader. It's select-loop contained an `assert!` macro intended to tie assumptions about height-progress together and ultimately revealed a bug.
Instead of keeping an extra map, the Celestia heights can be flattened directly into the objects that are reconstructed from the blobs read off of Celestia. This makes the assertion …

fix(conductor): simplify mapping Celestia heights to Sequencer heights

---

Cargo.lock
Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/block_cache.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-sequencer-relayer/Cargo.toml

Updates the celestia reference height even when the execution channel is full
During large syncs the channel gets full of blocks to execute from celestia and then with smaller variance heights especially would exit the window since the window wasn't being updated on scheduled block updates.
- Add logs about sequencer blocks received from Celestia
- Update the reference base for celestia variance window correctly.
Run manually via dev-cluster

fix(conductor): update reference celestia height correctly

---

Cargo.lock
Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/block_cache.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-sequencer-relayer/Cargo.toml

Actually updates the next height that the block stream should fetch, and updates the referenced celestia height when block is scheduled.
Rust primitives don't have `must_use`, so, `u64::checked_add` into `Option::expect` did nothing, hence we never updated the next height the block was supposed to fetch. When the executor buffer was full, blocks are scheduled for execution but the execution buffer didn't update execution upon completion so variance window would be inaccurately closed.
- Assign the incremented height to fetch
- Make the bounds-checks for Celestia variance be inclusive of the limit
- update celestia base reference on schedule block completion.
- Add tests 
Added tests for determining the next height before/after incrementing it.
Fixes a bug introduced in …

fix(conductor): update increment celestia height to fetch

---

crates/astria-composer/src/searcher/executor/mod.rs

Updates the timer when clicked over and bundle is empty.
Once an empty bundle was encountered we would log endlessly, hitting OOM, and loop quickly killing CPU cycles. We should have been resetting the timer.
- Reset timer after empty bundle time.
Manually tested with k8s in dev-cluster and metrics server to observer resource consumption.

fix(composer): reset timer when bundle empty

---

containerfiles/Dockerfile

Bumps cargo chef to 0.1.66 in base container image.
Cargo chef fixed how it prepares its recipe when supplying the `--bin` argument. Because our crates are nested under `./crates` we needed to provide a path to the binary crate. It can now figure it out itself.
- Update base container image to `cargo-chef:0.1.66-rust-1.76.0-bookworm`
- Update containerfile to supply `--bin` option with just the crate name (no path)
Container image is still built by docker.

chore(ci): bump cargo chef to 0.1.66

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/sequencer/reporting.rs
crates/astria-conductor/src/sequencer/snapshots/astria_conductor__sequencer__reporting__tests__snapshots-2.snap
crates/astria-conductor/src/sequencer/snapshots/astria_conductor__sequencer__reporting__tests__snapshots.snap
crates/astria-core/src/sequencer/v1/mod.rs

Ensures that rollup IDs are serialized as strings.
The serde derivation for `RollupId` was missing a `serde(transparent)` attribute. This means that, for JSON, rollup IDs were not serialized has `"<hex-of-32-bytes>"` but as `{ "inner": "<hex-of-32-bytes>" }`.
This in turn caused the JSON-serialization of some structs used for reporting received blocks from sequencer to fail, causing a panic in the tracing stack (as it assumes that `Display` formatting won't fail).
- Add `serde(transparent)` attribute on `RollupId`
- Add snapshot tests to reporting types
Added snapshot tests for types used in conductor tracing (that's where we saw the failed display formatting and subsequent panic).

fix(conductor): serialize rollup IDs as strings so telemetry doesn't crash

---

crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/src/api.rs
crates/astria-sequencer-relayer/src/relayer/builder.rs
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs

Adds graceful shutdown to relayer.
Because relayer did not previously respond to SIGTERM, it would eventually just get killed off (for example by kubernetes after 30s). This could potentially lead to situations where relayer would try to submit blocks to Celestia right before shutdown, potentially leaving its state tracking file in a bad state.
- Add a SIGTERM listener to sequener-relayer, initiating a shutdown of all its services.
- The relayer task proper will immediately exit its event-loop and wait until its last submission is complete.
- Sequencer-Relayer itself waits 25 seconds for its relayer service to finish, hard-killing it otherwise
- The API task is issues an explicit shutdown signal last and has 4s to finish, before being killed.
This should be tested end to end by sending …

feat(relayer): implement graceful shutdown

---

crates/astria-sequencer/src/api_state_ext.rs

found a bug :/
- `get_sequencer_block_by_hash` to push to vec instead of indexing at index that doesn't exist
unit tests

fix(sequencer): fix bug in `get_sequencer_block_by_hash`

---

.github/workflows/reusable-docker-build.yml

Fixes tagging which was always disabled.
startsWith takes the searched string and then the search term, was inverted.

fix(ci): docker build tagging for releases

---

Cargo.lock
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/utils.rs
crates/astria-sequencer-relayer/src/utils.rs

Fixes conductor panicking during shutdown.
Conductor was using a tokio `LocalSet` together with an `Rc` to run its shutdown logic. This was entirely unnecessary and panicky (since the `Rc` was cloned into multiple tasks, which was obviously wrong).
Note that this PR does not address conductor ignoring `SIGTERM` during initialization.
- Simplify the awkward `LocalSet` + `Rc` to shutdown conductor tasks
- Simplify reporting task failure and exist
This needs to be tested end to end (since conductor receives an external signal).
Closes #828

fix(conductor): don't panic while shutting down

---

crates/astria-sequencer/src/state_ext.rs

First set of state-ext unit tests. In total there are seven files which need tests:
- `astria-sequencer/src/state_ext.rs`
- `astria-sequencer/src/accounts/state_ext.rs`
- `astria-sequencer/src/asset/state_ext.rs`
- `astria-sequencer/src/authority/state_ext.rs`
- `astria-sequencer/src/bridge/state_ext.rs`
- `astria-sequencer/src/ibc/state_ext.rs`
This PR just tests the `src/state_ext.rs` file. I will add more commits / PRs for the others after getting feedback on this one.
It is good to have unit tests to ensure that the database works as intended. 
Unit tests for the functionality in the file `src/state_ext.rs` were added.
:)

test(sequencer): add unit tests for src/state_ext file

---

justfile

This fixes three cases in the justfile where dependencies were not being built as part of the relevant steps.
When running `just deploy [sequencer|rollup|dev-rollup]` the required dependencies were not being built due to the commands being appended with `| true`.  This was intended to silence the output of the commands, but resulted in the commands failing silently.  I believe that's down to `true` returning `0` well before the helm command has completed, causing helm to receive a `SIGPIPE` signal and exiting with error.
The `| true` instances were replaced with `> /dev/null`.  It seems that my editor has stripped trailing whitespace too.
Manual testing only.  There is a smoke test where these could be added, but currently the smoke test explicitly calls the required `helm dependency …

fix: justfile updates to build dependencies

---

crates/astria-sequencer/src/accounts/state_ext.rs

Second set of state-ext unit tests. In total there are seven files which
need tests:
- ~`astria-sequencer/src/accounts/state_ext.rs`~ (this PR)
- `astria-sequencer/src/asset/state_ext.rs`
- `astria-sequencer/src/authority/state_ext.rs`
- `astria-sequencer/src/bridge/state_ext.rs`
- `astria-sequencer/src/ibc/state_ext.rs`
This PR just tests the `src/accounts/state_ext.rs` file.
It is good to have unit tests to ensure that the database works as
intended.
Unit tests for the functionality in the file `src/accounts/state_ext.rs` were
added.
:)

test(sequencer): add unit tests for src/accounts/state_ext

---

charts/README.md

Add information on the Sequencer and EVM rollup endpoints in the README.md of the dev-cluster charts in the `charts` directory.
When launching applications which are built on top of the shared sequencer like Composer. We require the URL of the shared sequencer RPC which requires some digging into k8s ingresses to get. 
This PR explicitly adds it to the doc.
- Update the docs to include the sequencer and evm rollup endpoints.
no testing required since these a documentation changes.
https://github.com/astriaorg/astria/issues/886
closes

chore(docs): Add sequencer RPC and EVM rollup RPCs/WSS endpoints in docs

---

charts/README.md

Fix doc for running a smoke-test in the `charts` directory.
The doc should be `just run-smoke-test` instead of `just run smoke-test`
- Update the docs
By running `just run-smoke-test` and ensuring that it is successfully triggered.

fix(docs): Fix doc for running a smoke test

---

crates/astria-sequencer/src/authority/state_ext.rs

Fourth set of state-ext unit tests. In total there are seven files which
need tests:
- ~`astria-sequencer/src/accounts/state_ext.rs`~
- ~`astria-sequencer/src/asset/state_ext.rs`~
- ~`astria-sequencer/src/authority/state_ext.rs`~ (This PR)
- `astria-sequencer/src/bridge/state_ext.rs`
- `astria-sequencer/src/ibc/state_ext.rs`
This PR just tests the `src/authority/state_ext.rs` file.
It is good to have unit tests to ensure that the database works as
intended.
Unit tests for the functionality in the file `src/authority/state_ext.rs` were
added.
:)

test(sequencer): add unit tests for src/authority/state_ext

---

crates/astria-sequencer/src/ibc/state_ext.rs

Fifth set of state-ext unit tests. In total there are seven files which
need tests:
- ~`astria-sequencer/src/accounts/state_ext.rs`~
- ~`astria-sequencer/src/asset/state_ext.rs`~
- ~`astria-sequencer/src/authority/state_ext.rs`~ 
- `astria-sequencer/src/bridge/state_ext.rs`
- ~`astria-sequencer/src/ibc/state_ext.rs`~ (This PR)
This PR just tests the `src/ibc/state_ext.rs` file.
It is good to have unit tests to ensure that the database works as intended.
Unit tests for the functionality in the file `src/ibc/state_ext.rs` were added.
:)

test(sequencer): add unit tests for src/ibc/state_ext

---

crates/astria-sequencer/src/bridge/state_ext.rs

Sixth set of state-ext unit tests. In total there are seven files which
need tests:
- ~`astria-sequencer/src/accounts/state_ext.rs`~
- ~`astria-sequencer/src/asset/state_ext.rs`~
- ~`astria-sequencer/src/authority/state_ext.rs`~ 
- ~`astria-sequencer/src/bridge/state_ext.rs`~ (This PR)
- ~`astria-sequencer/src/ibc/state_ext.rs`~
This PR just tests the `src/bridge/state_ext.rs` file.
It is good to have unit tests to ensure that the database works as intended.
- Unit tests for the functionality in the file `src/bridge/state_ext.rs` were added.
- Fixed issue in `get_deposit_nonce()` where the returned bytes were not formatted correctly.

test(sequencer): add unit tests for src/bridge/state_ext

---

crates/astria-sequencer/src/accounts/state_ext.rs

Updates instrumentation of account state to be human readable hex instead of arrays.
Logs were byte arrays which are not useful for debugging.
- Update to use display traits, and skip all
Part of fixing #897

chore(sequencer): logging as human readable for account state

---

.github/workflows/reusable-run-checker.yml
.github/workflows/scheduled.yml
.github/workflows/test.yml

This adds `cargo audit` to the CI pipeline.
This is useful to catch issues published to [RUSTSEC](https://rustsec.org/).
Added a job to test.yml to run it.  I used the instructions from [`audit-check`](https://github.com/rustsec/audit-check) (as recommended by `cargo-audit` [here](https://github.com/rustsec/rustsec/blob/main/cargo-audit/README.md#using-cargo-audit-on-github-action)), but chose to not restrict the check to run only if `Cargo.[toml|lock]` are modified, since `cargo audit` can start warning on a given dependency at any time.  We could probably change to follow their suggestion fully, i.e. run audit nightly and otherwise only run on changes to those two files, but I'll leave that up to SRE to decide :)
Note that we currently have three audit warnings, but they're all deemed …

ci: add cargo audit

---

.github/workflows/docker-build.yml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml

Updates the rollup chart to support latest release of Geth.
Geth was updated to support bridge transactions & locking to specific bridges on EVM.
- Update geth genesis, and version.
Running smoke test

chore(charts): update rollup for new geth version

---

crates/astria-core/src/generated/astria.sequencer.v1.serde.rs
tools/protobuf-compiler/src/main.rs

The protobuf compiler tool also generates `serde::Serialize` impls for some sequencer types needed to mock conductor.
The grpc mocking crate introduced in https://github.com/astriaorg/astria/pull/872 requires gRPC request and response objects to implement `serde::Serialize`. This PR generates the code necessary to mock a sequencer server used by conductor in blackbox tests.
- Update proto compiler tool to emit `serde::Serialize` and `serde::Deserialize` implementations for:
- `astria.sequencer.v1.FilteredSequencerBlock`
- `astria.sequencer.v1.GetFilteredSequencerBlockRequest`
- `astria.sequencer.v1.Proof`
- `astria.sequencer.v1.RollupTransactions`
n/a only generating cod

feat(core): generate pbjon impls for sequencer types needed to mock conductor

---

crates/astria-sequencer/src/api_state_ext.rs

Pulls the `Hex` utility into `api_state_ext` to not rely on `astria-telemetry`.
Using utilities from `astria-telemetry` to format database keys is a bad idea. That was introduced in https://github.com/astriaorg/astria/pull/793. This patch moves that functionality from telemetry to sequencer proper, living closer to where the keys are actually crated.
- Copy the `astria_telemetry::display::Hex` newtype wrapper to `sequencer::api_state_ext`.
No change in functionality, unit tests should still run.

chore(sequencer): no telemetry for formatting db keys

---

crates/astria-core/src/generated/astria.composer.v1alpha1.rs
crates/astria-core/src/generated/astria.execution.v1alpha1.rs
crates/astria-core/src/generated/astria.execution.v1alpha2.rs
crates/astria-core/src/generated/astria.primitive.v1.rs
crates/astria-core/src/generated/astria.sequencer.v1.rs
tools/protobuf-compiler/Cargo.lock
tools/protobuf-compiler/Cargo.toml
tools/protobuf-compiler/src/main.rs

Generate type names for all Rust protobuf types.
Prost introduced the the `Name` trait to allow referring to protobuf messages by their full name. It's useful being able to refer to the full protobuf name (instead of just its Rust type) in observability and tests.
- Updated the proto compiler tool to also emit `impl prost::Name for <proto_type>`
n/a Only generating code

feat(core): generate names for protobuf rust types

---

CODEOWNERS

Add @Fraser999 to CODEOWNERS.
We need better infra configuration on selecting individual reviewers for specific PRs. In the absence of that this patch is adding a new CODEOWNER so that approval rights are more distributed.
- Add @Fraser999 to CODEOWNERS

ci: add Fraser999 to codeowners

---

Cargo.lock
crates/astria-celestia-client/src/client.rs
crates/astria-composer/src/executor/mod.rs
crates/astria-composer/tests/blackbox/grpc_collector.rs
crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/reporting.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-core/Cargo.toml
crates/astria-core/src/sequencer/v1/asset.rs
crates/astria-core/src/sequencer/v1/mod.rs
crates/astria-sequencer-relayer/src/relayer/write/conversion.rs
crates/astria-sequencer/src/api_state_ext.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/lib.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/state_ext.rs
crates/astria-sequencer/src/utils.rs
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/display.rs

All tracing events that report byte slices now use base64 encoding instead of hex.
This applies especially to rollup IDs, sequencer addresses, and sequencer asset IDs.
Google's Protobuf to JSON mapping prescribes base64 be used when encoding byte slices. So far the astria codebase was arbitrarily using hex encoding, but this requirement justifies unifying everything to base64.
- change the display formatting for rollup IDs, sequencer addresses, asset IDs from hex to base64
- remove the `display::hex` utility form `astria-telemetry`
- update all instances that used `display::hex` to use `display::base64` instead
- make the rocks db key construction involving asset IDs independent of the asset ID `Display` impl (always use hex instead)
These changes should be entirely cosmetic. If they are …

feat: replace hex by base64 for display formatting, emitting tracing events

---

crates/astria-grpc-mock/src/mock.rs

Added `Mock::mount` and `Mock::mount_as_scoped` methods on mocks.
Similar to wiremock, these methods are useful to chain construction and mounting mocks in one go. These were useful in https://github.com/astriaorg/astria/pull/917
- Added `Mock::mount` and `Mock::mount_as_scoped` convenience methods to mount mocks on mock servers.

feat(grpc-mock): utility methods for mounting mocks

---

.github/workflows/test.yml

Added the `--all-targets` flag to `cargo hack check` to ensure tests can also be built outside the workspace.
While implementing https://github.com/astriaorg/astria/pull/889 it was found that sequencer-relayer tests can only be run from the repository root but not from the crate directory itself. The CI job that is supposed to ensure this failed because it was not running with the right flags.
- Added `--all-targets` flag to `cargo hack check` in the rust test github workflow.
- 
Closes https://github.com/astriaorg/astria/issues/893

feat(ci): ensure all crate targets can be built outside the workspace

---

crates/astria-sequencer/src/api_state_ext.rs

Seventh set of state-ext unit tests. In total there are seven files which
need tests:
- ~`astria-sequencer/src/api_state_ext.rs`~ (This PR)
- ~`astria-sequencer/src/accounts/state_ext.rs`~
- ~`astria-sequencer/src/asset/state_ext.rs`~
- ~`astria-sequencer/src/authority/state_ext.rs`~ 
- ~`astria-sequencer/src/bridge/state_ext.rs`~
- ~`astria-sequencer/src/ibc/state_ext.rs`~
This PR just tests the `src/api_state_ext/state_ext.rs` file.
It is good to have unit tests to ensure that the database works as intended.
Unit tests for the functionality in the file `src/api_state_ext/state_ext.rs` were added.
:)

test(sequencer): add unit tests for src/api_state_ext

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/deployments.yaml
charts/evm-rollup/templates/statefulsets.yaml
charts/evm-rollup/templates/storageclasses.yaml
charts/evm-rollup/templates/volumes.yaml
dev/values/rollup/dev.yaml

Moves geth rollup & blockscout into statefulsets to enable simple upgrades, fixes local storage for testing locally.
When upgrading geth nodes realized that updating geth version with deployments will never succeed. Ended up having to resync the whole geth node which over time will become expensive. Moving to statefulset enables cleaner upgrades.
- StatefulSets for geth & blockscout
- Fixed local storage for rollup for testing 
Run locally and manually trigerred helm upgrades to make sure they go through.

fix(charts): use statefulsets appropriately for rollup

---

Cargo.lock
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
crates/astria-conductor/Cargo.toml
crates/astria-conductor/local.env.example
crates/astria-conductor/src/celestia/builder.rs
crates/astria-conductor/src/celestia/latest_height_stream.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/config.rs

Replaces the websocket subscription to get the latest Celestia heights by a HTTP fetch running periodically.
Websocket adds complexity for questionable gain. Tests in particular are much more complex to set up, but also for normal operation disconnects and resubscriptions need to be handled explicitly because websocket does not have a reconnect mechanism.
This PR essentially comes full circle, removing every last trace of websocket again.
- Replace the websocket subscription by an interval stream + HTTP fetch (not calling this GET because this is still JSONRPC dong a POST)
- Removes the `ASTRIA_CONDUCTOR_CELESTIA_NODE_WEBSOCKET_URL` config
- Adds the `ASTRIA_CONDUCTOR_CELESTIA_BLOCK_TIME_MS` config which takes an integer representing the duration in milliseconds between two successive …

refactor(conductor)!: use HTTP to periodically poll Celestia heights 

---

Cargo.lock
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/api_state_ext.rs
crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/state_ext.rs

set revision number from chain id in `init_chain` 
we need to set the chain's revision number from the last number of the chain id, if applicable. otherwise, it's set to 0. see https://ibc.cosmos.network/main/ibc/overview#ibc-client-heights
- set revision number from chain id in `init_chain` by parsing final integer of chain id if it's in the form `name-<revision-number>`
unit tests

fix(sequencer): set revision number from chain id in `init_chain`

---

crates/astria-sequencer/src/app.rs

This PR makes the 'did I propose this' check in `process_proposal()` more robust by caching the proposer's address in `prepare_proposal()`. Changed the check from a bool to checking if the cached proposing address matches the proposal's creator.
The sequencer's app logic shouldn't execute transactions in `process_proposal` if it was the app that proposed the transactions in `prepare_proposal` (as re-executing the transactions will fail due to how we manage state). The previous check was only a `bool` that was set in `process_proposal` and Zellic pointed out that this check could pass incorrectly if the proposed proposal timed out and a new proposal was proposed by someone else.
The proposing address is managed by cometbft and can …

fix(sequecer): is_proposer check now considers proposer's address

---

crates/astria-cli/src/cli/sequencer.rs
crates/astria-cli/src/commands/mod.rs
crates/astria-cli/src/commands/sequencer.rs

Adds commands for the following sequencer actions:
- `ValidatorUpdate`
- `SudoAddressChange`
- `IbcRelayerChange`
- `FeeAssetChange`
- `Mint`
Needed in general for testing sequencer.
Adding CLI commands for all of the above actions.
Tested via sending commands using the CLI. 
Example of commands: 
```
astria-cli sequencer sudo validator-update --validator-public-key xxx --power 8 --private-key xxx
astria-cli sequencer sudo sudo-address-change --address xxx --private-key xxx
astria-cli sequencer sudo ibc-relayer add --address xxx --private-key xxx
astria-cli sequencer sudo fee-asset remove --asset nria --private-key xxx
astria-cli sequencer sudo mint --to-address xxx --amount 120 --private-key xxx
```
closes #879

feat(cli): add authority commands

---

charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/config.toml
charts/sequencer/files/scripts/init-cometbft.sh
charts/sequencer/templates/configmaps.yaml
charts/sequencer/templates/secretproviderclass.yaml
charts/sequencer/templates/statefulsets.yaml
charts/sequencer/values.yaml
dev/values/validators/single.yml

Adds SecretProvider to CometBFT, and configures for use for private key files. Additionally updates such that config updates will propograte through on update, without overriding the data directory.
Way back when I had trouble getting this all to work, and once I found something that copied I stopped touching. This resulted in a bad configuration where private keys had to be in values files. Also required manual inteverention on node to update config.toml files. This fixes those.
- Secret providers for private keys
- config file changes propogate at update.
Run locally with storage enabled, ensured directories outside /cometbft can work for private keys, still need to test on cluster for secret provider.

fix(charts): cometbft support for secrets

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-composer/src/collectors/geth.rs
crates/astria-composer/src/collectors/grpc.rs
crates/astria-composer/src/collectors/mod.rs
crates/astria-composer/src/composer.rs
crates/astria-composer/src/executor/mod.rs
crates/astria-composer/src/executor/tests.rs
crates/astria-composer/src/grpc.rs

Implements graceful shutdown for Composer components. 
Composer has 3 main components:
1. Geth Collectors
2. Grpc Server/Collector
3. Executor
Currently, we do not have any sort of graceful shutdown for these Components. This PR implements it.
When a Geth Collector shuts down, we do the following:
1. We need to unsubscribe to the websocket stream
2. We need to set the status of the geth collector to false(not connected)
For the Grpc Server, we just pass in a future which resolves when a shutdown signal is passed to the server by running it as `serve_with_incoming_shutdown`. 
When an Executor shuts down, we do the following:
1. Close the `serialized_rollup_transactions` channel to avoid receiving transactions. 
2. Set Executor status to false(not connected).
3. Drain any remaining bundles …

feat(composer): add graceful shutdown

---

CODEOWNERS

Updating the split up into more groups. I have updated the groups within github to autoassign a member from the group when added in a round robin fashion. So this will auto assign, and if one person is in multiple assigned groups selected that will count for all. I've also removed myself from the assignment pool queue for rust reviewers.
We want to declutter inbox and more more concrete assignment. 
- More granular code ownership settings, pushing most to groups.

chore: update codeowners w/ teams

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/ingress.yaml
charts/sequencer-faucet/Chart.yaml
charts/sequencer-faucet/templates/ingress.yaml
charts/sequencer/Chart.yaml

Update to only use either the annotation of the spec definition of ingress class name. 
Dev encountered this error while deploying charts:
```
Error: INSTALLATION FAILED: 2 errors occurred:
* Ingress.extensions "node0-sequencer-grpc-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
* Ingress.extensions "node0-sequencer-rpc-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```
Smoke test

fix(charts): only use one of annotation and spec for ingress

---

CODEOWNERS

Since codeowners update only people with * have been being added, I believe I needed to reverse order of file

fix: codeowners order

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

Updating so that external PRs can pass, and to allow docker builds to be specified on non-main builds
External PR improving docker builds couldn't pass CI, this is a fix for that and for some PRs which we might want to run docker builds on which are merges into other PRs.

fix(ci): docker runs should pass for external prs

---

dev/values/validators/single.yml

I accidentally enabled storage which can cause slowness and test failures. This disables it by default.

fix(ci): disable storage for dev values

---

CODEOWNERS

Changed order since the bottom of codeowners takes precendence, added some files which were defaulting to top level owners to specific groups.

chore(ci): CODEOWNERS updates

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

This moves the Docker image builds to [Depot](https://depot.dev), where they can be done on native Intel and Arm CPUs with persistent layer cache across builds.
I sent our [benchmark-astria results](https://github.com/depot/benchmark-astria/actions/runs/8647400279/job/23708761387) over to @joroshiba that shows how Depot can build all these images in ~46 seconds for a fully cached build. He asked if we could open a PR to help with the cutover.
- `reusable-docker-build.yml` is updated to use [`depot/build-push-action`](https://github.com/depot/build-push-action), which takes all the same parameters with the addition of a `project` property to route the image build to a specific project in Depot.
- `reusable-docker-build.yml` contains a new permissions block so that you can authenticate to …

Refactor Docker builds to use Depot for zero emulation builds + persistent cache

---

Cargo.lock
crates/astria-celestia-client/src/lib.rs
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/block_cache.rs
crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/celestia/builder.rs
crates/astria-conductor/src/celestia/convert.rs
crates/astria-conductor/src/celestia/fetch.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/reconstruct.rs
crates/astria-conductor/src/celestia/reporting.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/tests/blackbox/firm_only.rs
crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-conductor/tests/blackbox/helpers/mod.rs
crates/astria-conductor/tests/blackbox/main.rs
crates/astria-core/src/sequencer/v1/test_utils.rs
crates/astria-core/src/sequencerblock/v1alpha1/celestia.rs

Fixes conductor so it works in the presence of duplicate sequencer blobs or rollup blobs fetched from Celestia.
Duplicate sequencer block information can end up on Celestia. If a single Sequencer block ends up as a duplicate at the same Celestia height (for example, because two Sequencer nodes both relayed to Celestia), then Conductor can potentially stop functioning correctly because of code present as of commit [`cd38d1d5458fd561696590417b647f1844d328f2`](https://github.com/astriaorg/astria/blob/cd38d1d5458fd561696590417b647f1844d328f2/crates/astria-conductor/src/celestia/mod.rs#L586-L589):
```rust
ensure!(
rollup_blobs.len() <= 1,
"received more than one celestia rollup blob for the given namespace and height"
);
```
This causes Conductor to drop reconstruction of a Sequencer block …

fix(conductor): robust Celestia blob fetch, verify, convert

---

crates/astria-sequencer/justfile
crates/astria-sequencer/scripts/testnet.sh

Updated the sequencer's justfile and testnet.sh script to work again with latest version of sequencer.
TODO: have someone test on their linux machine. I had to edit the script to work on a mac and tried to make the commands work on both but I'm unsure if I did it right.
`just run-testnet` : to run testnet locally 
`just clean-testnet` : to cleanup testnet

chore(sequencer): update justfile and testnet script

---

crates/astria-composer/src/executor/bundle_factory/mod.rs
crates/astria-composer/src/executor/bundle_factory/tests.rs
crates/astria-composer/src/executor/tests.rs
crates/astria-core/src/primitive/v1/mod.rs

Account for the length of fee_asset_id while estimating the sequence action size in composer.
In Composer, we create bundles with the incoming txs collected from the gRPC and Geth collectors. 
These bundles have to be appropriately sized so that we don't end up sending a tx to the sequencer which is much bigger than the block size or the max tx size accepted by the sequencer. 
To do this, we have a variable `ASTRIA_COMPOSER_MAX_BYTES_PER_BUNDLE` which is the max bytes allowed in a bundle. 
Currently, this was not considering the length of the fee_asset_id field of a SequenceAction. When a large inflow of txs are sent to the composer which causes the bundles to be completely filled, the submission of the bundle to the sequencer fails because the unaccounted fee_asset_id fields cause the tx …

fix(composer): account for fee asset id while estimating sequence action size

---

crates/astria-sequencer/src/authority/action.rs
crates/astria-sequencer/src/authority/state_ext.rs

Before this PR it was possible for sudo to accidentally cause consensus failures via removing non-existing validators from the validator set. For a single validator setup, sudo could also error by removing the only validator. We need to filter this on the app side because for some reason cometBFT will error/shut down if it receives these bad requests. 
- Added to the ActionHandler's stateful checks for validator updates to make sure we don't error.
Ran a local testnet with multiple validators and ensured that removing non-existing validators no longer causes consensus failures. 
```
just run-testnet
./target/debug/astria-cli sequencer sudo validator-update \
--validator-public-key c39892c49c819491c3552c1a95337d7324a45b25dd0aa397efb706bae8648dac \
--power 0 \
--private-key …
```

fix(sequencer): do not allow sudo to cause consensus failures

---

Cargo.lock

Updated the version of `rustls`.
The version currently used has had [RUSTSEC-2024-0336](https://rustsec.org/advisories/RUSTSEC-2024-0336) issued against it.
Ran `cargo update -p rustls` to increase the version.
Ran normal test suite, no additional tests added.

fix: cargo audit warning

---

Cargo.lock
crates/astria-composer/src/executor/mod.rs
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/display.rs

We switched to using base 64 everywhere, but tx hashes for cometbft should be hex.
When grabbing txs from CometBFT RPCs you need the hex string of the transaction, so logging out base64 is pretty useless unfortunately.
- Add telemetry hex back in
- Use hex telemetry encoding for the transaction hash logs in composer.
CI

fix(composer): use tx hash as hex again

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Cut releases of the core components for initial dusk-5 release. Note that sequencer-relayer is not required and can catch up after further testing of new changes.

release: sequencer 0.11, conductor 0.14, composer 0.6, relayer 0.12

---

crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/transaction/mod.rs

Sequencer's stateful check wasn't ensuring that a transaction's entire fee consumption was covered by the balance, it was only checking per individual action. Now the stateful check will err if there aren't enough funds for the whole transaction.
We were checking this already in the mempool, but this check will cover the edge case of an account's earlier transaction consuming funds in the same block. 
Added unit test.
closes #786

fix(sequencer): stateful check now ensures balance for total tx

---

.github/workflows/reusable-run-checker.yml

Fix CI test which would run anytime there were changes that were not in the vendored  proto directory.

fix(ci): only run proto on actual proto changes

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/templates/secretproviderclass.yaml
charts/sequencer-relayer/templates/statefulset.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Adds support for using a secret provider to the sequencer-relayer chart
These changes are being made to make this component consistent with others that have already implemented this.
- Add `SecretProviderClass`
- Update the `Values.config.celestiaAppPrivateKey` to be in the correct format
- Update ConfigMaps to reference the updated secret
- Update StatefulSet to optionally pull from secretProvider or devContent value
- Ensure `helm template` actually renders without error
- Deploy to local dev-cluster with `Values.secretProvider.enabled=false`
- Will need to still coordinate + deploy to dev with `Values.secretProvider.enabled=true` assuming the secrets have been created

Relayer secret provider

---

charts/celestia-local/Chart.yaml
charts/celestia-local/files/scripts/start-bridge.sh
charts/celestia-local/templates/deployment.yaml
charts/celestia-local/templates/service.yaml
charts/celestia-local/values.yaml
charts/celestia-node/Chart.yaml
charts/celestia-node/files/scripts/start-node.sh
charts/celestia-node/templates/statefulset.yaml
charts/celestia-node/values.yaml
charts/evm-rollup/Chart.lock
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/templates/statefulsets.yaml
charts/evm-rollup/values.yaml
charts/hermes/Chart.yaml
charts/hermes/templates/configmaps.yaml
charts/hermes/values.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
dev/values/hermes/local.yml
dev/values/rollup/dev.yaml
dev/values/validators/node0.yml
dev/values/validators/node1.yml
dev/values/validators/node2.yml
dev/values/validators/single.yml
justfile

Upgrades all our charts to utilize latest releases, including updates celestia-node. Additionally removes the token server from celestia-node & celestia-local which is not needed now that we submit directly to app. Some secret information has been moved from the core chart into the dev values to avoid someone actually deploying with these values in production. 
New releases of core services are cut, this upgrades the charts to support those.
Local testing of setitngs with charts both in dev mode and not. CI smoke test for dev-mode.
- Charts are upgraded, new releases that are major updates

release: chart upgrades for new releases

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/templates/secretproviderclass.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Removes the unused `secretObjects` in relayer chart, and the `configmap` which is unused when `secretProvider` is enabled
Secret objects are used for loading into k8s secrets and env vars, this is not something we are doing for the relayer chart as the secret is only accessed directly as a file. 
- disable configmap when secret provider enabled
- remove `secretObjects` from the provider.
CI/CD, and changes have been manually made to deployments for devnet.

fix(chart): secretObject when no env var usage

---

crates/astria-sequencer/src/app.rs
crates/astria-sequencer/src/sequencer.rs
crates/astria-sequencer/src/service/consensus.rs

set current app hash properly when creating app
this was causing issues if the node was restarted as the app hash would be empty, and this is written to state in ibc begin_block, causing an app hash mismatch on the next synced block
- set current app hash properly when creating app
local testnet with 4 validators and restarting one node, previously failed, now it works

fix(sequencer): set current app hash properly when creating app

---

Cargo.lock
crates/astria-composer/Cargo.toml
crates/astria-composer/src/collectors/geth.rs
crates/astria-composer/src/collectors/grpc.rs
crates/astria-composer/src/collectors/mod.rs
crates/astria-composer/src/executor/bundle_factory/mod.rs
crates/astria-composer/src/executor/mod.rs
crates/astria-composer/src/lib.rs
crates/astria-composer/src/main.rs
crates/astria-composer/src/metrics_init.rs

This PR setups and instruments metrics with Composer.
Composer currently doesn't track any metrics. We require metrics in production for observability and alerting.
- Metrics setup for Composer crate
More changes detailed in the `Metrics` section
Tested these changes by launching composer against messenger rollup and bombarding messenger rollup with txs. The metrics were accurate w.r.t to the load composer received.
- `transactions_dropped`: A counter of the  transactions dropped by the Collectors labelled per rollup id and collector type. This can be due to the Executor channel being closed or the channel has timed out.
- `transactions_received`: A counter of transactions received by the collectors labelled by rollup id and collector type
- `transactions_dropped_too_large`: A counter of …

feat(composer): add initial set of metrics

---

crates/astria-sequencer/src/service/consensus.rs

Zellic suggested that we panic the sequencer on consensus failures instead of silently sending them to cometbft. There isn't any error handling in cometbft so doing this makes sense and gives us more info for debugging.
Made the request handler panic in the sequencer on abci requests that shouldn't fail. 
Ran the sequencer locally with planned failures. 
closes #1004

fix(sequencer): panic sequencer instead of cometbft on erroring abci consensus requests

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml

Latest changes to astria-geth have added/changed genesis configs which breaks the existing charts
we want charts to work
- update `astriaBridgeAddresses` structure.
- remove `astriaBridgeAllowedAssetDenom`
- add `astriaFeeCollectors`
- add `astriaEIP1559Params`
using repo smoke tests

fix(charts): update evm rollup charts for new genesis configs

---

justfile

Updated justfile to match CI.
The justfile `_lint-proto` target has fallen out of sync with the actual proto packages.
Fixed this to match [the checks performed in CI](https://github.com/astriaorg/astria/blob/cb2a35ecafb46bada1ccbeac9086ff0f48119faf/.github/workflows/lint.yml#L27-L46).
Ran `just lint proto` locally.

Update justfile to match CI

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
crates/astria-sequencer/Cargo.toml

Reverts astriaorg/astria#1032
https://github.com/astriaorg/astria/pull/1017 was incorrectly labelled as non breaking.

Revert "release(sequencer): sequencer 0.11.1"

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/configmaps.yaml
charts/sequencer/values.yaml

Adds service name to OTEL data.
By default service name is `unnamed` this can be configured via env var but wasn't done previously.
- Adds `OTEL_SERVICE_NAME` to astria chart configs.

feat(charts): add otel service names

---

crates/astria-sequencer-relayer/src/metrics_init.rs
crates/astria-sequencer-relayer/src/relayer/celestia_client/mod.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs

Added a metric to the relayer to give visibility of the current highest sequencer block stored on Celestia.
It will be useful to avoid having to search the logs for this info.
Added the new metric (see below).  Also dropped the log level of a couple of somewhat noisy `debug!` log lines.
No formal tests added.  Viewed the metrics of a running relayer to ensure the new metric was as expected.
- Added `astria_sequencer_relayer_sequencer_submission_height`.

feat(sequencer-relayer): add metric recording highest sequencer block submitted

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/service.yaml
charts/evm-rollup/templates/servicemonitor.yaml
charts/evm-rollup/templates/statefulsets.yaml
charts/sequencer/Chart.yaml
charts/sequencer/templates/service.yaml
charts/sequencer/templates/servicemonitor.yaml
charts/sequencer/templates/statefulsets.yaml

Shortens the  port names which were too long, making it impossible to enable metrics.

fix(charts): shorten metric port names

---

crates/astria-conductor/src/config.rs
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-conductor/tests/blackbox/helpers/mod.rs
crates/astria-conductor/tests/blackbox/soft_and_firm.rs

Conductor fetches blocks from the rollup node if they are not in its cache.
During initialization and when set to firm-and-soft commitment mode, Conductor issued a `BatchGetBlocks` RPC to the rollup. When the delta between firm and soft commitments was too large, this could be a request for 50k and more elements, putting a lot of pressure on the rollup node or failing outright because the request exceeded the default 4MB limit for gRPC requests.
This patch replaces this pre-fetch in favor of an already existing fallback logic: if conductor finds a Celestia block with the next desired firm-number, it either looks up the corresponding rollup block in its cache, or requests it from the rollup. It then updates the rollup's commitment state.
- Remove `BatchGetBlocks` logic from conductor …

refactor(conductor): fetch missing blocks as necessary

---

crates/astria-conductor/src/celestia/fetch.rs

Fixes celestia-blob-fetch logic to also retry on request timeout.
jsonrpsee has a dedicated request timeout error variant that is different from the underlying transport failing. We have to take it into account when determining whether to retry a blob fetch or not.
- added `jsonrpsee::core::Error::RequestTimeout` to the list of errors for which conductor retries fetching celestia blob
Needs to be tested in a dev environment. Very difficult to reproduce the actual jsonrpsee error.

fix(conductor): retry blob fetch on request timeout

---

crates/astria-core/src/generated/astria.protocol.transactions.v1alpha1.rs
crates/astria-core/src/protocol/transaction/v1alpha1/action.rs
crates/astria-sequencer/test-genesis-app-state.json
proto/protocolapis/astria/protocol/transactions/v1alpha1/types.proto

update ics20 withdrawal to have a memo field as we'll need it for bridging (and good to have in general)
- update ics20 withdrawal to have a memo field
n/a
- `Ics20Withdrawal` now contains a `memo` field

feat(proto): update ics20 withdrawal to have a memo field

---

charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/genesis.json
crates/astria-sequencer/src/accounts/component.rs
crates/astria-sequencer/src/app/test_utils.rs
crates/astria-sequencer/src/app/tests_app.rs
crates/astria-sequencer/src/app/tests_execute_transaction.rs
crates/astria-sequencer/src/bridge/component.rs
crates/astria-sequencer/src/genesis.rs
crates/astria-sequencer/src/ibc/component.rs
crates/astria-sequencer/src/sequence/component.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/transaction/mod.rs
crates/astria-sequencer/test-genesis-app-state.json

instead of having hard coded default fee values, the fees now must be set in the genesis file. this makes it more explicit as to how the network is configured.
related to https://github.com/astriaorg/astria/issues/1003
- update genesis app state to contain required fees
- set these fees in state in `init_chain`
unit tests
- genesis app state must now contain fees
related to https://github.com/astriaorg/astria/issues/1003

feat(sequencer)!: add fees to genesis state

---

crates/astria-sequencer/src/ibc/ics20_transfer.rs

prefixes were not being converted correctly for bridge locks, i refactored the ibc prefix conversion to be in its own function and added unit tests for all cases.
found while testing incoming ibc transfers to a bridge account, the denom was not being prefixed before being compared to the allowed asset ID for the bridge account.
- put all conversion from packet denom -> converted ibc'd denom into its own `convert_denomination` function
- this is now called before everything else in `execute_ics20_transfer`, so the correct converted denom should be used
unit tests + tested it with a bridge lock via ibc

fix(sequencer): fix ibc prefix conversion

---

crates/astria-sequencer-relayer/src/metrics_init.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs

Changes various *per_tx metrics gauges into histograms.
Making the *per_tx metrics into histograms will allow summing over all Celestia submissions and will give a running total of bytes, blobs, and blocks submitted to Celestia.
- Changed `astria_sequencer_relayer_blobs_per_celestia_tx` from `gauge` to `histogram`
- Changed `astria_sequencer_relayer_blocks_per_celestia_tx` from `gauge` to `histogram`
- Removed `astria_sequencer_relayer_total_blob_data_size_for_astria_block`
- Added histogram `astria_sequencer_relayer_bytes_per_celestia_tx`
Metrics need to be tested by observing them.
- Added histogram `astria_sequencer_relayer_bytes_per_celestia_tx`
- Changed metric types, removed a metric, added a metric (see above)

metrics(relayer)!: make per submission gauges into histograms

---

crates/astria-composer/src/main.rs
crates/astria-conductor/src/main.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer/src/main.rs
crates/astria-telemetry/src/lib.rs

Register metrics for a service through a callback on the telemetry builder.
`astria_telemetry::Config` should be the central entry point to configure telemetry and metrics. Before this patch the metrics provider, buckets, and global labels were set through config, but actual metrics specific outside of it. With this patch this is done in one step.
- add `Config::register_metrics` on telemetry builder
- change all services to pass their initialization function to it. 
Must be observed in a dev cluster.

feat(telemetry): register metrics via callback

---

crates/astria-sequencer-relayer/src/relayer/write/conversion.rs

Inverts the compression ratio calculation.
It's normal to express a compression ratio as uncompressed:compressed, but were reporting it as the inverse of this in logs and metrics (despite the metric's description claiming it was uncompressed:compressed).
As per summary.
Added a unit test.
No new metric added, but the value of `astria_sequencer_relayer_compression_ratio_for_astria_block` should now generally be > 1 rather than < 1.

chore(sequencer-relayer): change compression ratio calculation

---

crates/astria-conductor/src/sequencer/block_stream.rs
crates/astria-conductor/src/sequencer/mod.rs

Conductor no longer exits if it can't observe the initial height of the Sequencer network.
When having soft commitments enabled, Conductor attempted to read the current height of the Sequencer network during initialization. If this failed, Conductor would immediately exit rather than retry. In the Astria dev environment this would happen repeatedly because Conductor's startup is much faster than Sequencer.
This changes removes this initial height-read entirely because it is not necessary.
- Remove reading the current height of the Sequencer network during initialization
- Change the latest observed sequencer height in the internal block stream to be optional: the stream will now only start producing blocks once a height was externally recorded
This change should be transparent to all …

fix(conductor): don't exit on bad Sequencer connection

---

crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/sequencer/mod.rs

Conductor now respects shutdown signals it receives during init.
Conductor's task ignored shutdowns while still initializing. This meant that Conductor would hang for up to 30 seconds.
- refactor conductor's constituent long-running tasks to separate initialization and running
- listen for the shutdown signal in all of conductor's tasks
Run conductor with endpoints that hang indefinitely and sending it SIGTERM. Observe that conductor shuts down quickly.
The main operation of conductor is unaffected on the happy path: all blackbox tests run to completion.
A proper test for the shutdown logic will be implemented in a follow-up refactor similar to https://github.com/astriaorg/astria/pull/889

feat(conductor): respect shutdown signals during init

---

Cargo.lock
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Releases of composer 0.7.0, conductor 0.16.0, sequencer-relayer 0.14.0, and sequencer 0.12.0. These changes all work together, for use of initial dusk-6 network.

release: dusk-6 releases

---

crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/main.rs
crates/astria-conductor/tests/blackbox/firm_only.rs
crates/astria-conductor/tests/blackbox/helpers/mod.rs
crates/astria-conductor/tests/blackbox/main.rs
crates/astria-conductor/tests/blackbox/shutdown.rs
crates/astria-conductor/tests/blackbox/soft_and_firm.rs
crates/astria-conductor/tests/blackbox/soft_only.rs

Removes the signal handler from the `Conductor` type, replacing it with a handler that allows shutting it down explicitly.
There is no way to test if a service shuts down properly in Rust integration test if the only way to terminate it is to send a SIGTERM. Providing an explicit `shutdown` method allows for testing its shutdown logic independently of OS/runtime specific signal handling.
- Introduce a new `Conductor::spawn` method that spawns conductor on the tokio runtime and returns a `Handle` to the running task.
- Add a `Handle::shutdown` method to explicitly shut down conductor.
- Move setup of the unix signal handler from `Conductor::run_until_blocked` into `fn main` and use the new handle.
- Test Conductor shutdown on every blackbox test.
All blackbox tests now invoke the Conductor …

refactor(conductor): perform signal handling in binary and test shutdown logic

---

crates/astria-composer/src/main.rs
crates/astria-conductor/src/main.rs
crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer/src/main.rs
crates/astria-telemetry/src/lib.rs

Calls `opentelemetry::global::shutdown_tracer_providers` upon exiting services
Because OTLP is pushed-based, users must ensure that all spans are flushed and sent to the OTLP endpoint.
Note that `opentelemetry::global::shutdown_trace_providers` is a blocking operation and can potentially stall a service from exiting. We must observe if this actually ends up being a problem in practice.
- Add a drop guard as the return value of `astria_telemetry::Config::try_init`, which in turns calls `opentelemetry::global::shutdown_trace_providers` on drop
Happens outside of testable code. Must be observed on devnet/in production.

fix(telemetry): ensure tracer providers are shut down in all services

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/deployments.yaml

Fixes the deployment of the faucet, previously using secret provider had a missing the `token` default value, fix to use updated secret deployment.
* now uses `Values.config.faucet.privateKey.secret.key` as token value when secretProvider is enabled

fix(charts): faucet deployment fix

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
crates/astria-sequencer/Cargo.toml

New release of sequencer for dusk-7 with fees going to sudo address, chart updates to support it.

release(sequencer): sequencer 0.13.0

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml

Chart limits for conductor & composer were too low, and we have a new geth image with less noisy logs

chore(charts): update evm chart to have better default request limits

---

crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs

This adds retry logic to all execution API gRPCs from Conductor to the rollup.
If there was a hickup when communicating with the rollup, conductor would fail immediately. This adds retry logic all execution API calls. Because this cannot yet be done at the transport level due to type-level constraints on tonic and tower, this patch adds retries at the application leve.
- Add retry logic to every execution v1alpha2 API call
- Introduce a `ExecutionApiRetryStrategy` implementing `tryhard::BackoffStrategy`
- The following gRPC tonic status codes will be retried:
- Cancelled
- Unknown
- DeadlineExceeded
- NotFound
- ResourceExhausted
- Aborted
- Unavailable
- DataLoss
Add unit tests for the all codes. The happy-path blackbox tests are unaffected.
closes …

feat(conductor): add retry to execution API gRPCs

---

crates/astria-sequencer/justfile

fix `just run-cometbft` command in justfile
astria-sequencer-utils changed with a recent PR
-  fix `just run-cometbft` command
i ran the command

fix(sequencer): fix `just run-cometbft` command

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/tests/blackbox/firm_only.rs
crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-conductor/tests/blackbox/soft_and_firm.rs
crates/astria-conductor/tests/blackbox/soft_only.rs
crates/astria-core/src/execution/v1alpha2/mod.rs
crates/astria-core/src/generated/astria.execution.v1alpha2.rs
crates/astria-core/src/generated/astria.execution.v1alpha2.serde.rs
proto/executionapis/astria/execution/v1alpha2/execution.proto

Updates the execution api to have celestia base height as a part of commitment instead of genesis, requiring rollups to track the base celestia height as it increases. This enables conductor on resync to move much faster.
https://github.com/astriaorg/astria-geth/pull/22 contains an implementation which works with this PR.
Conductor resync needs to grab all data from genesis for the rollup currently, even if much of that data is previously executed.
- Change execution API to have celestia base height on commitment
- Update conductor logic to update celestia base height to that of most recent firm commitment found in.
Manually tested running linked PR in dev cluster, updated blackbox tests.
- Execution API breaking change, rollout will require a new image for any rollup utilizing.

feat(conductor, proto)!: celestia base heights in commitment state

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml

Due to submission order needs, switched dev tag to pr branch, this switches it back to latest.

chore(chart): change evm back to latest on dev

---

crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/tests/blackbox/firm_only.rs
crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-conductor/tests/blackbox/helpers/mod.rs
crates/astria-conductor/tests/blackbox/soft_and_firm.rs

Conductor drops sequencer metadata items retrieved from Celestia if their height has already been executed/committed.
Conductor would try and unnecessarily verify Sequencer metadata retrieved from Celestia, putting a lot of pressure on the Sequencer node. Because Conductor is stateless, it fetches all Celestia blobs for the sequencer and rollup namespaces starting from the `celestia_base_block_height` configured the rollup. It would then verify all sequencer metadata items retrieved in this way against the Sequencer, even if the metadata was for old blocks (meaning blocks with a height below the next firm height expected by the rollup).
- Check the Sequencer height of each sequencer metadata item received from Celestia against the next expected firm height; drop the item without …

feat(conductor): skip outdated block metadata

---

crates/astria-merkle/src/audit.rs

Gently refactors the audit API to remove a source of panics.
Originally mentioned in the zelic audit, the option-unwrapping performed in the audit API was not necessary.
- remove an unnecessary optional from the audit leaf builder.
All tests still pass, no functionality was changed.

refactor(merkle): remove source of panics in audit API

---

.github/workflows/docker-build.yml

Adds image build for bridge withdrawer to `evm-bridge-withdrawer` package.

chore(ci): build bridge withdrawer images

---

crates/astria-core/src/generated/astria.protocol.bridge.v1alpha1.rs
crates/astria-core/src/generated/mod.rs
crates/astria-core/src/protocol/bridge/mod.rs
crates/astria-core/src/protocol/bridge/v1alpha1/mod.rs
crates/astria-core/src/protocol/mod.rs
crates/astria-sequencer-client/src/extension_trait.rs
crates/astria-sequencer-client/src/tests/http.rs
crates/astria-sequencer/src/bridge/mod.rs
crates/astria-sequencer/src/bridge/query.rs
crates/astria-sequencer/src/bridge/state_ext.rs
crates/astria-sequencer/src/service/info/mod.rs
crates/astria-sequencer/src/transaction/mod.rs
proto/protocolapis/astria/protocol/bridge/v1alpha1/types.proto

implement `bridge/account_last_tx_hash` abci query which returns the last executed tx from the given bridge account.
required for the bridge withdrawer's sync logic (or rather, makes it much simpler to implement).
- if a bridge account makes a tx, store this tx hash in the nonconsensus storage.
- implement `bridge/account_last_tx_hash` abci query which queries the nonconsensus storage for this tx hash given some address. 
- TODO: we can make this a config value, so only nodes that are configured to store this data store it. 
unit tests
closes #1107

feat(sequencer): implement `bridge/account_last_tx_hash` abci query

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/transaction/mod.rs

bump penumbra dep to latest tagged release
we were on a non-tagged commit before
- bump penumbra dep to latest tagged release
closes  #964

chore: bump penumbra deps

---

specs/sequencer-relayer.md

Adds a document specifying details of the sequencer-relayer.
This doc was previously missing.
- Added doc.
N/A
Note that discussions or edits could be made on [the HackMD copy of this doc](https://hackmd.io/rpyleM5_T0ak8VrR9qnUXQ?both) rather than on this PR.

chore(docs): add sequencer-relayer doc to specs

---

crates/astria-bridge-withdrawer/src/withdrawer/ethereum/generated/astria_bridgeable_erc20.rs
crates/astria-bridge-withdrawer/src/withdrawer/ethereum/generated/astria_withdrawer.rs
crates/astria-bridge-withdrawer/src/withdrawer/ethereum/generated/astria_withdrawer_interface.rs
crates/astria-bridge-withdrawer/src/withdrawer/ethereum/mod.rs

fixes the linting of bridge contract bindings.
the existing generated rust bindings for the bridge smart contracts do not comply with our linting standards.
- add `#[rustfmt::skip]` to the generated bindings module in `withdawer::ethereum`
- add the relinted generated files
closes #1169

fix(bridge-withdrawer): skip linting generated contract code

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
crates/astria-sequencer-relayer/local.env.example
crates/astria-sequencer-relayer/src/config.rs
crates/astria-sequencer-relayer/src/relayer/builder.rs
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/helpers/mock_sequencer_server.rs
crates/astria-sequencer-relayer/tests/blackbox/helpers/test_sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/main.rs

This changes the relayer to relay all blocks regardless of which validator proposed them.
We had functionality to allow providing a validator secret key to the relayer and an option to only relay blocks proposed by that validator.  The functionality wasn't being used anywhere, so it has been removed.
- Removed configuration options (see below) and supporting code.
N/A
- Removed env var `ASTRIA_SEQUENCER_RELAYER_VALIDATOR_KEY_FILE`.
- Removed env var `ASTRIA_SEQUENCER_RELAYER_RELAY_ONLY_VALIDATOR_KEY_BLOCKS`.
Closes #1010.

chore(sequencer-relayer)!: remove functionality to restrict relaying blocks to only those proposed by a given validator

---

.cargo/audit.toml
.github/workflows/reusable-docker-build.yml
Cargo.lock

Ignore RustSec warning.
We get a non-critical warning when running `cargo audit`: [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139).
When running `cargo tree -i -p=ansi_term` we can see that `ansi_term` is a dependency of `dylint` and `tracing-subscriber` v0.2.  While `tracing-subscriber` v0.3 doesn't depend upon `ansi_term`, we can't easily upgrade to that version as several of our dependencies do not support v0.3.  Also, `dylint`'s latest version still depends upon `ansi_term`.
Given that the RustSec report doesn't suggest any concrete problems with `ansi_term` and how difficult it will be to move away from this dependency, I have just ignored this warning in CI.
We also have a further audit warning about v0.1.29 of `jobserver` being yanked, so I have updated that …

fix: ignore RUSTSEC-2021-0139

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/statefulsets.yaml
charts/evm-rollup/templates/storageclasses.yaml
charts/evm-rollup/values.yaml

Add a `purgeMempool` flag to the rollup config which will force purge the geth mempool on startup if set to true.
- Started local dev cluster w/ storage enabled and `purgeMempool` disabled.
- Forced two (2) queued tx in mempool by sending tx with higher nonce than account's current nonce
- Checked 2 queued tx were in mempool using `txpool_status` rpc call (✅ passed)
- Deleted geth pod to force it to restart
- Checked 2 queued tx were in mempool using `txpool_status` rpc call (✅ passed)
- Enabled `purgeMempool` and updated helm chart
- Deleted geth pod to force it to restart
- Checked pending and queued tx were 0 using `txpool_status` rpc call (✅ passed)

feat(charts): option to purge geth mempool

---

crates/astria-core/src/protocol/abci.rs
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/mempool.rs
crates/astria-sequencer/src/metrics.rs
crates/astria-sequencer/src/service/mempool.rs

This PR adds to the App's mempool a way to signal to CometBFT when transactions should be removed from the CometBFT mempool. 
The CometBFT and App mempools currently get transactions that fail to execute stuck in them. This is because when a transaction fails to execute in `prepare_proposal()`, it doesn't get removed from the CometBFT mempool. CometBFT only clears out transactions if they either fail `handleCheckTx()` or are included in a block. Because of this, CometBFT will re-add the failed transaction to the App mempool during its `handleCheckTx()` maintenance, which will cause it to be fed to `prepare_proposal()` again.
We also need a way for full nodes to clear out these invalid transactions. Since these nodes don't run `prepare_proposal()`, we need an additional way, like a tx TTL, …

feat(sequencer): add ttl and invalid cache to app mempool

---

specs/conductor.md

Updates the outdated and incorrect conductor spec to its current implementation.
The old spec was horribly out of date and contained implementation details that are not necessary to understanding its high level functionality. The spec in this document is a first pass and barebones. Flow charts will be added in a followup PRs.
- update `specs/conductor.md`
Not applicable.

doc(conductor): update outdated spec

---

README.md
crates/astria-bridge-withdrawer/build.rs

Corrected the file paths in the withdrawer build script.
The wrong paths were being specified when emitting `cargo:rerun-if-changed`.  This caused the build to always be out of date, meaning rebuilding would always trigger a recompile, even if no sources changed.  It was visible by running `cargo b && cargo b -v` in the withdrawer folder, where the output would include:
```txt
Dirty astria-bridge-withdrawer v0.1.0 (/home/fraser/Rust/astria/crates/astria-bridge-withdrawer): the file `crates/astria-bridge-withdrawer/ethereum/src/AstriaWithdrawer.sol` is missing
Compiling astria-bridge-withdrawer v0.1.0 (/home/fraser/Rust/astria/crates/astria-bridge-withdrawer)
``` 
- Corrected the file paths and added assertions that the specified files exist.
- Added an extra instruction in the main …

fix(astria-bridge-withdrawer): use correct file paths in build script

---

Cargo.lock
crates/astria-core/Cargo.toml
crates/astria-core/src/bridge.rs
crates/astria-core/src/serde.rs
crates/astria-sequencer/src/ibc/ics20_transfer.rs

implement `Ics20TransferDepositMemo` format and handling for incoming ics20 transfers to bridge accounts, which requires the memo be of a specific format instead of assuming the entire memo is the destination chain address.
the memo being just a destination chain address is not good for UX and could lead to error.
- implement `Ics20TransferDepositMemo` type which contains the destination `rollup_address`
- add stateless check that the `FungibleTokenPacketData` (which is the ics20 transfer packet itself) is not empty or too long
-  parsing and handling of the memo for incoming ics20 transfers
unit tests
- the validation of the ICS20 memo is different, so this will break previously sent ICS20 transfers to bridge accounts.

feat(sequencer)!: implement `Ics20TransferDepositMemo` format for incoming ics20 transfers to bridge accounts

---

crates/astria-core/src/generated/astria.primitive.v1.rs
crates/astria-core/src/generated/astria.primitive.v1.serde.rs
crates/astria-core/src/primitive/v1/mod.rs
proto/primitives/astria/primitive/v1/types.proto

Removes the non-bech32m address bytes field.
The change introduced in https://github.com/astriaorg/astria/pull/1124 is a breaking change that ripples through the rest of the Astria stack. While in principle we can keep the non-bech32m address around for backward compatibility, in practice it's cleaner to regenesis.
- Remove `astria.primitive.v1.Address.inner`, reserving its number and name.
Updates and removed all unit tests. All blackbox tests that use addresses in some form still work.
Since this is protobuf breaking it is also network breaking.

chore(core, proto)!: remove non-bech32m address bytes

---

crates/astria-sequencer-relayer/src/main.rs
crates/astria-sequencer-relayer/src/relayer/builder.rs
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/helpers/test_sequencer_relayer.rs

This fixes a bug whereby the relayer hangs during shutdown due to the submitter task not being instructed to shut down.
Bugfix.
- Rather than cloning a single cancellation token, we now have the following hierarchy:
- `SequencerRelayer::new` constructs a `ShutdownHandle` which wraps the top-level cancellation token.  This handle is held as a member variable of `SequencerRelayer` and is used to cancel all relayer child tasks if the API task exits. A clone of the `ShutdownHandle`  is also held in `main` and is used to cancel all tasks if a `SIGTERM` is received.
- A child of `ShutdownHandle`'s token is provided to the relayer task, named `relayer_shutdown_token`.  It is never actively cancelled - only ever via the parent token.
- A child of `relayer_shutdown_token` is provided to the …

fix(sequencer-relayer): avoid hanging while waiting for submitter task to return

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml

Update the evm chart to utilize the newest version of geth with breaking genesis changes before merging into main with geth repo.

chore(chart): update evm chart for new prefix field

---

crates/astria-core/src/crypto.rs
crates/astria-core/src/primitive/v1/mod.rs

it's unclear/difficult of how an external user can construct an address given a verification key (i ran into this while updating hermes). this adds a `verification_key` method to the `Address::builder` to easily construct an address. also added `From` the ed25519 consensus types for the crypto module types.
much better for ux, updating hermes would be painful without these.
- adds a `verification_key` method to the `Address::builder` to easily construct an address
-  added `From` the ed25519 consensus types for the crypto module types.
n/a

feat(core): implement with verification key for address builder and crypto improvements

---

crates/astria-core/src/crypto.rs

revert `From` ed25519_consensus types for crypto mod
We want to minimize the surface of our public astria-core API when it comes to foreign (third party) types.

fix(core): revert `From` ed25519_consensus types for crypto mod

---

charts/deploy.just
charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/config.toml
charts/sequencer/files/cometbft/config/genesis.json
charts/sequencer/values.yaml
dev/values/validators/all.yml
dev/values/validators/node0.yml
dev/values/validators/node1.yml
dev/values/validators/node2.yml
dev/values/validators/single.yml

Updates all charts to use latest releases for dusk-8, and updates to the latest CometBFT release.
New releases for services were cut.
- Update all chart versions for astria releases, migrate dev mode to standard behaivior.
- Update to CometBFT 0.38.8
- Update default sequencer chart to not have any dev dependent fields filled out.
running smoke test locally, plus CI runs

chore(chart)!: dusk-8 chart version updates

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml

Updates the chart to support new version of geth in https://github.com/astriaorg/astria-geth/pull/34 which updates a genesis parameter name.

chore(charts): update for new geth update

---

Cargo.lock
crates/astria-sequencer/Cargo.toml

Includes changes to abci query for assets to enabled bridge withdrawer usage.

release(sequencer): 0.14.1 patch release

---

crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/metrics.rs

decode failure was being recorded instead of the correct execution failure metric.
decode failure is no longer used anywhere so it was removed
- see summary
unit tests

fix(sequencer) fix wrong metric and remove unused metric

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/convert.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/tests.rs
crates/astria-core/src/bridge.rs
crates/astria-core/src/snapshots/astria_core__bridge__test__bridge_unlock_memo_snapshot.snap

Moves the bridge-unlock memo out of `astria-bridge-withdrawer` and into `astria-core`.
This type needs to be publicly readable for `astria-cli` and other consumers.
- Move the `BridgeUnlockMemo` type to `astria_core::bridge`
- Change the public memo fields from ethers types to native Rust types
- Encode the contained transaction hash as base64
- Provide snapshot tests
bridge-withdrawer tests still pass.
The transaction hash field in the memo being encoded as `base64` is a breaking change for bridge-withdrawer.

refactor(core, bridge-withdrawer)!: move bridge-unlock memo to core

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/statefulsets.yaml

`geth v1.14.0` introduced changes to archive node configurations, now need to set `--state.scheme=hash` to enable archive node

fix: rollup archive node configurations

---

crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-core/src/generated/astria.execution.v1alpha2.serde.rs
crates/astria-core/src/generated/astria.primitive.v1.serde.rs
crates/astria-core/src/generated/astria.sequencerblock.v1alpha1.serde.rs
crates/astria-core/src/generated/celestia.blob.v1.serde.rs
crates/astria-core/src/generated/cosmos.auth.v1beta1.serde.rs
crates/astria-core/src/generated/cosmos.base.abci.v1beta1.serde.rs
crates/astria-core/src/generated/cosmos.base.node.v1beta1.serde.rs
crates/astria-core/src/generated/cosmos.base.tendermint.v1beta1.serde.rs
crates/astria-core/src/generated/cosmos.crypto.multisig.v1beta1.serde.rs
crates/astria-core/src/generated/cosmos.tx.v1beta1.serde.rs
crates/astria-core/src/generated/tendermint.p2p.serde.rs
crates/astria-core/src/generated/tendermint.types.serde.rs
tools/protobuf-compiler/src/main.rs

Use `lowerCamelCase` for protobuf message field names mapped to JSON object keys.
The Protobuf to JSON mapping prescribes that protobuf message fields must use `lowerCamelCase` when mapped to JSON object keys. The protobuf-compiler tool was erroneously preserving the Rust field names which re `snake_case`.
- Remove `pbson_build::Builder::preserve_proto_field_names` from its build chain
- Regenerate serde `Serialize` and `Deserialize` impls for all protobuf Rust types
- Fix Conductor test mocks to use the correct case
All tests still run.
This is neither network breaking nor service breaking because the Astria stack only uses protobuf (not its JSON counterparts) on the wire. However, this is still marked as breaking due to external consumers being affected.

feat(core)!: lowerCamelCase for protobuf json mapping

---

crates/astria-conductor/tests/blackbox/helpers/mod.rs

Avoid panicking if a test is already panicking.
The Conductor test environment is checking if it shut down cleanly for every test. If not, it's panicking to signal that the test should fail.
However, if a test was already failing (panicking) due to another bad condition, this lead to the test being immediately aborted without printing any useful diagnostics.
This patch fixes this by only panicking if the test is not already panicking, and issuing a debug level message otherwise.
- Change the `Drop` impl for the conductor test environment to only panic if the test is not already panicking.
This is to fix bad tests not providing useful information, which was encountered while writing another PR.

fix(conductor): don't panic during panic

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/convert.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/tests.rs
crates/astria-core/src/generated/astria.protocol.transactions.v1alpha1.rs
crates/astria-core/src/protocol/transaction/v1alpha1/action.rs
crates/astria-sequencer/src/app/tests_breaking_changes.rs
crates/astria-sequencer/src/app/tests_execute_transaction.rs
crates/astria-sequencer/src/bridge/bridge_unlock_action.rs
proto/protocolapis/astria/protocol/transactions/v1alpha1/types.proto

Changes the memo field of bridge unlock actions from `bytes` to `string`.
IBC convention is to format all memos as json and encode as `string` rather than `bytes` when sending them over the wire. The `astria.protocol.transactions.v1alpha1.Ics20Withdrawal.memo` field is also `string`, so this change brings `astria.protocol.transactions.v1alpha1.BridgeUnlockAction.memo` in line.
- Change `astria.protocol.transactions.v1alpha1.BridgeUnlockAction.memo` from `bytes` to `string`
All tests are updated and pass.
This constitutes a breaking protobuf-change (as flagged by `buf`) but very likely neither a deployment nor network breaking change:
+ `bytes` and `string` are wire-compatible (from a protobuf point of view)
+ `sequencer` only passes the memo field through
+ `bridge-withdrawer` will be …

feat(core, proto)!: make bridge unlock memo string

---

Cargo.lock
crates/astria-sequencer-utils/Cargo.toml
crates/astria-sequencer-utils/tests/parse_blob.rs

This PR fixes a bug in the `parse_blob` tests.
The existing tests use `colour::force_no_colour()` to avoid `sequencer-utils` from generating coloured output in order to make the snapshots more legible.  However, setting that actually has no effect (under the hood, `colour` was deciding to not use coloured output due to `io::stdout().is_terminal()` returning `false`).
By updating to `colour` v2.1.0 this becomes apparent, as that version also takes the `TERM` env var into account.  `TERM` is set to a value other than `dumb`, so coloured output is emitted.
- The fix is to set the `NO_COLOR` env var for the subprocess, as this has highest priority in disabling coloured output.
The tests broken after updating `colour` now pass.

fix(sequencer-utils): fixes issue in `parse_blob` tests

---

charts/sequencer/Chart.yaml
charts/sequencer/templates/statefulsets.yaml
charts/sequencer/values.yaml
dev/values/validators/all.yml

Adds resource request and limit defaults + lower for local dev values.
Want to ensure sequencer and cometbft get adequate resources

fix(charts): add resources for sequencer/cometbft

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/convert.rs

specify bridge address in withdrawer actions so that the actions will still be accepted by the sequencer even if the withdrawer address for the account is different than the bridge address (assuming the withdrawer signer is the correct key ofc)
we want to support withdrawer addresses that differ from bridge addresses
- specify bridge address in withdrawer actions
unit tests
closes #1241

fix(withdrawer): support withdrawer address that differs from bridge address  

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/convert.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/mod.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/tests.rs
crates/astria-bridge-withdrawer/src/lib.rs
crates/astria-core/src/bridge.rs
crates/astria-core/src/serde.rs
crates/astria-core/src/snapshots/astria_core__bridge__test__bridge_unlock_memo_snapshot.snap
crates/astria-core/src/snapshots/astria_core__bridge__test__ics20_withdrawal_from_rollup_memo_snapshot.snap
crates/astria-sequencer/src/ibc/ics20_transfer.rs

Ensures that bridge-withdrawer does not use a rollup address as a sequencer refund address.
Bridge-withdrawer was using an address on the ethereum rollup as the sequencer refund address in the actions it was submitting to sequencer. That was wrong.
- add a field `rollup_refund_address` to `Ibc20WithdrawalFromRollupMemo` to make its purpose clear
- In bridge-withdrawer, set `refund_address` to the bridge account always (`refund_address` and `bridge_address` are now the same).
- Sequencer now assumes that for refunds of ics20 withdrawals initiated by a rollup `FungibleToketPacketData.sender` is now the bridge address to which funds should be refunded. This is consistent with the change above.
- Remove field `Ibc20WithdrawalFromRollupMemo.brigde_address` as it is no longer necessary.
Tests …

fix(core, bridge, sequencer)!: dismabiguate return addresses

---

crates/astria-cli/src/cli/bridge.rs
crates/astria-cli/src/cli/mod.rs
crates/astria-cli/src/cli/sequencer.rs
crates/astria-cli/src/commands/bridge/collect.rs
crates/astria-cli/src/commands/bridge/mod.rs
crates/astria-cli/src/commands/bridge/submit.rs

Adds a subcommand to submit previously collected withdrawal events.
https://github.com/astriaorg/astria/pull/1261 provides a subcommand to listen to and collect withdrawal events that come form a rollup's astria contracts. This patch now provides the ability to also submit the events.
- Added a `bridge submit-withdrawals` subcommand to `astria-cli`
- Renamed `bridge collect-withdrawal-events` to `bridge collect-withdrawals`
- Adjusted the object written and read to be a json object `rollup_height -> [actions]`.
TBD

feat(cli): add bridge cmd to submit withdrawal events

---

charts/deploy.just

Add back in the missing just commands

fix: cli commands in just file

---

.github/workflows/docker-build.yml
Cargo.lock
charts/deploy.just
crates/astria-cli/Cargo.toml
crates/astria-cli/src/cli/bridge.rs
crates/astria-cli/src/cli/mod.rs
crates/astria-cli/src/cli/sequencer.rs
crates/astria-cli/src/commands/bridge.rs
crates/astria-cli/src/commands/bridge/collect.rs
crates/astria-cli/src/commands/bridge/mod.rs
crates/astria-cli/src/commands/bridge/submit.rs
crates/astria-cli/src/commands/mod.rs
crates/astria-cli/src/main.rs

Adds `bridge collect-withdrawals` and `bridge submit-withdrawals` subcommands to `astria-cli`.
The worker service `astria-bridge-withdrawer` is a closed system that collects withdrawal event from the rollup and submits them to the sequencer in a closed loop. But it can be desirable to inspect the withdrawal events generated by the bridge contracts, and then submit them manually. This functionality is now provided by `astria-cli`.
- Add subcommands `bridge collect-withdrawal-s` to `astria-cli`, which has two different modes of operation, depending on whether `--to-rollup-height` is set:
- if set, it fetches all blocks between `--from-rollup-height` and `--to-rollup-height` (inclusive), converts them to seuquencer actions, and then writes them to a file.
- if not set, it fetches blocks from …

feat(cli): add cmd to collect withdrawal events and submit as actions

---

charts/deploy.just

Uses a temporary file instead of writing to the workspace during smoke tests.
It's bad practice to pollute the workspace when running tests. This change writes the output to a temporary file instead, and ensures that it is cleaned up after exit.
- Update the `run-smoke-cli` recipe in `charts/deploy.just` to write to a temporary generated by `mktemp` (without arguments to not run into differences between Darwin/BSD and GNU/Linux)
- Use a trap to clean up the temporary on `EXIT`.
Run `just run-smoke-cli`, observe that the workspace is clean.

chore(test): use a temporary file to not pollute the workspace

---

Cargo.lock

Updated the `bytes` and `ics23` crates.
The version of `bytes` we currently use has been yanked due to [a bug](https://github.com/tokio-rs/bytes/pull/718).  Running `cargo audit` exposed this as an allowed warning.
We also got a report of an issue with the `ics23` crate and a recommendation to update to v0.11.3.
- Ran `cargo update -p bytes` and `cargo update -p ics23`.
No additional tests required.

chore: update `bytes` and `ics23` crates

---

crates/astria-bridge-withdrawer/src/main.rs

Handle errors from constructing the service and emit an error.
The service was set up to panic instead of emitting an error code and and message if initialization failed. 
- Handle errors returned by service init rather than panicking and emit an event.
closes [#1278](https://github.com/astriaorg/astria/issues/1278)

fix(bridge-withdrawer): don't panic on init

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Update EVM-Rollup Geth `devTag` after #1291 and astria-geth [#38](https://github.com/astriaorg/astria-geth/pull/38).
#1291 relied on astria-geth PR [#38](https://github.com/astriaorg/astria-geth/pull/38) for `evm-rollup` chart. Now that both PRs have been merged, the `devTag` can be updated to `latest`.
- Updated geth `devTag` to `latest` in `evm-rollup` `values.yaml`. 
- Updated `evm-rollup` and `evm-stack` versions.
Passing e2e tests.

chore(chart): Update EVM-Rollup Geth devTag

---

.gitignore

Removed a gitignore entry that had no relevance to the repo.

chore: remove spurious entry in gitignore

---

crates/astria-core/src/crypto.rs

Ensures that ed25519_consensus is not part of the public `astria-core` API.
The definition `struct astria_core::crypto::Error(#[from] ed25519_consensus::Error)` leaks `ed25519_consensus::Error` into the public API of `astria-core`. This patch removes the `#[from]` attribute and updates a few lines by explicit constructors, `map_err(Error)`.
* Remove the `From<ed25519_consensus::Error> for crypto::Error` impl, removing `ed25519_consensus` from `astria-core`'s public API. 
This is a breaking change in `astria-core` but not in any of our services. Because we don't yet publish `astria-core`, this is not a breaking change at this moment but would be breaking in the future.
Closes https://github.com/astriaorg/astria/issues/1221

chore(core): remove ed25519_consensus from public API

---

.github/workflows/lint.yml
charts/deploy.just
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/evm-stack/values.yaml
crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs
crates/astria-bridge-withdrawer/tests/blackbox/helpers/test_bridge_withdrawer.rs
dev/values/rollup/dev.yaml

Fixes bridge withdrawer code which was broken + CI test setup issue which allowed broken test to get in.
We were not using the latest bridge withdrawer code correctly, this fixes that + fixes the code which broke main CI tests

fix(charts, bridge): fix ci test

---

.github/workflows/docker-build.yml
charts/celestia-local/Chart.yaml
charts/celestia-local/templates/statefulsets.yaml
charts/deploy.just
charts/ibc-test.just
justfile

Updates the `charts/celestia-local` to spin up `celestia-appd` in a stateful set. Executes the ics20 transfer inside the celestia-app container inside the set.
https://github.com/astriaorg/astria/pull/1285 updates the ibc ics20 transfer test to require `celestia-appd` and an initialized celestia keystore to be present on the machine running the test. This is undesirable because it pollutes the host environment and creates potential for collisions. Turning `celestia-local` from a kubernetes deployment to a stateful set allows executing the ics20 transfer from inside the container.
- Rename `charts/celestia-local/templates/deployment.yaml -> charts/celestia-local/templates/statefulsets.yaml`
- Changes `kind: Deployment -> kind: StatefulSet` in that file
- Update recipes in …

refactor(ci): execute ics20 test from statefulset celestia container

---

charts/composer/Chart.yaml
charts/composer/templates/configmap.yaml
charts/composer/templates/deployment.yaml
charts/composer/templates/secretproviderclass.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/templates/servicemonitor.yaml
charts/evm-faucet/Chart.yaml
charts/evm-faucet/templates/deployment.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-faucet/Chart.yaml
charts/sequencer-faucet/values.yaml

Changes to production templates of the charts, namely secrets, volumes, configmap and deployment
Production deployments through GCP provider has small template errors
- composer secret private key naming
- evm-bridge-withdrawer condition
- sequencer-faucet now uses fixed image
- evm-faucet condition and secret naming
- evm-rollup otel values templating
- deployed a local kubernetes cluster with all services
- this changes were originally made while deploying dusk-9 production network
closes #1358

chore(charts): fix charts production templates

---

Cargo.lock
crates/astria-sequencer/.gitignore
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/test_utils.rs
crates/astria-sequencer/src/app/tests_app.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/mempool/benchmarks.rs
crates/astria-sequencer/src/mempool/mod.rs
crates/astria-sequencer/src/mempool/transactions_container.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/service/mempool.rs

This is effectively an update to the existing PR #1323.
While reviewing #1323, it seemed more expedient to open a PR against it rather than adding many GH comments (this was discussed with @Lilyjjo).
As always, there are more changes here than I initially expected.  The main thrust of the changes was to try and use the type system to avoid certain classes of errors, and to make things a little more canonical where possible.
- At a high level, there are now separate types dealing with pending txs and parked txs: `PendingTransactionsForAccount`, `PendingTransactions`, `ParkedTransactionsForAccount` and `ParkedTransactions`.  For the ones dealing with a single account, much of their logic is common, so a trait `TransactionsForAccount` was introduced to express that shared logic.  For the …

feat(sequencer): various updates to mempool PR

---

charts/celestia-local/Chart.yaml
charts/celestia-local/values.yaml
charts/celestia-node/Chart.yaml
charts/celestia-node/values.yaml
charts/evm-rollup/Chart.lock
charts/evm-rollup/Chart.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

celestia-node image update to v0.14.1 which fixes memory leaks
Image used per celestia-node is outdated
- celestia-node image `v0.13.4 -> v0.14.1`
locall kubernetes cluster with all services deployed and firm blocks confirmed

Chore: Upgrade celestia-node to v0.14.1

---

crates/astria-conductor/src/celestia/fetch.rs

Updated `fetch_blobs_with_retry()` to accept [Celestia Node v0.15.0](https://github.com/celestiaorg/celestia-node/releases/tag/v0.15.0)'s new `GetAll()` return format. This will still work with Node v0.14.1 as well.
celestia-node v0.15.0 now returns an empty list of blobs for `GetAll` if blobs are not found, which broke our current `jsonrpsee` error handling in conductor.
- Updated `fetch_blobs_with_retry()` to accept the `ParseError` that Json RPC now throws when there are no blobs fetched.
E2E tests working

fix(conductor): update for celestia-node v0.15.0

---

Cargo.lock
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/tests/blackbox/helpers/test_sequencer_relayer.rs
crates/astria-sequencer-relayer/tests/blackbox/main.rs

This is a straight swap of [`isahc`](https://github.com/sagebind/isahc) in place of `reqwest` in the relayer's blackbox tests.  Other than a single timeout being increased, no logic was changed.
Blackbox tests were failing on macOS due to the poor performance of the `reqwest` messages.  The timeout for a `GET` was set to 100ms, and using `reqwest` I was seeing times around 120ms.  By swapping to `isahc`, times dropped to 2ms.
- Swapped `isahc` in place of `reqwest` in the realyer's blackbox tests.
- Increased the timeout on a flaky test from 2s to 10s (the test occasionally takes just over 2s, less than 3s from several attempts locally).
- Added `[lints.rust]` to the relayer's manifest to squash some warnings.
No new tests required, existing ones now pass on macOS.
Closes #1354.

fix(relayer): change `reqwest` for `isahc` in relayer blackbox tests (ENG-699)

---

crates/astria-core/src/sequencerblock/v1alpha1/block.rs

Shortened `try_from_block_info_and_data()` to remove clippy exception.
Migration from `Vec<u8>` to `Bytes` in #1319 introduced some new code which put `SequencerBlock::try_from_block_info_and_data` over the line limit. 
- Created helper function to return  `rollup_transactions_root` and `rollup_ids_root` from a iterator on `data`.
closes #1357

refactor(core): shorten `try_from_block_info_and_data()`

---

crates/astria-sequencer/src/bridge/state_ext.rs
crates/astria-sequencer/src/ibc/ics20_withdrawal.rs

Fixes ics20 withdrawals by actually taking funds from the provided bridge address.
Prior to this change, funds were always taken from the signer of the `astria.protocol.v1alpha1.Ics20Withdrawal` action, even if its `bridge_address` field was set.
- Uses `astria.protocol.v1alpha1.Ics20Withdrawal.bridge_address` to take funds in an ics20 withdrawal if set (and if it passes bridge checks)
- Remove unnecessary state accesses to check if enough funds are present: just try to decrease them. If they fail, then the entire action fails.
All present tests have been updated to check if the correct withdrawal target is found.
There should be tests for the entire `Ics20Withdrawal::check_and_execute` flow. However, adding an ibc channel and port does not seem to be currently possible because …

fix(sequencer)!: take funds from bridge in ics20 withdrawals

---

Cargo.lock
crates/astria-core/src/protocol/abci.rs
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/test_utils.rs
crates/astria-sequencer/src/app/tests_app.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/mempool/benchmarks.rs
crates/astria-sequencer/src/mempool/mod.rs
crates/astria-sequencer/src/mempool/transactions_container.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/service/mempool.rs

This rewrite makes our mempool similar to Geth's/Reth's with per-account transaction storage and maintenance. This rewrite tracks 'pending' transactions that are ready to execute, and 'parked' transactions that could be ready for execution in the future on a per-account basis.
This rewrite adds minor new functionality from the previous mempool and changes the mempool interface. Was co-written with @Fraser999.
Prior to this rewrite, the mempool was not in a state to be improved upon. All transactions, ready to execute or not, were being stored together in a giant queue. This structure didn't allow for mempool optimizations such as performing mempool upkeep on a per account basis-- instead the only option was to loop through all transactions on the per-block maintenance upkeep. 
This file …

feat(sequencer): rewrite memool to have per-account transaction storage and maintenance 

---

.github/workflows/build.yml
.github/workflows/docker-build.yml
.github/workflows/release.yml
.github/workflows/reusable-docker-build.yml

Updates the image build to work on a specific tag when binary name and image name don't match
The `astria-bridge-withdrawer` binary is pushed to an `evm-bridge-withdrawer` docker package and the tag used is `bridge-withdrawer-v<semantic version>` for releases. This is potentially suboptimal but has already been done. Our image build script doesn't work with this setup.
- update image build to consider `binary-name` without `astria` prefix and take a separate `package-name` for most instances these are the same but for when they are not it supports it. There is also a `binary-prefix` which can be set to provide more flexibility for the future.
CI/CD tests
closes https://github.com/astriaorg/astria/issues/1373

fix(ci): enable bridge withdrawer building with tag

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/tests/blackbox/helpers/mock_cometbft.rs
crates/astria-composer/src/executor/tests.rs
crates/astria-composer/tests/blackbox/geth_collector.rs
crates/astria-composer/tests/blackbox/grpc_collector.rs
crates/astria-composer/tests/blackbox/helper/mock_sequencer.rs
crates/astria-composer/tests/blackbox/helper/mod.rs
crates/astria-core/src/generated/mod.rs
crates/astria-core/src/protocol/account/mod.rs
crates/astria-core/src/protocol/transaction/mod.rs
crates/astria-core/src/sequencerblock/v1alpha1/block.rs
crates/astria-sequencer-client/src/extension_trait.rs
crates/astria-sequencer-client/src/tests/http.rs
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/service/info/mod.rs
crates/astria-sequencer/src/service/mempool.rs
crates/astria-sequencer/src/transaction/query.rs

Updates the generated path names to match the actual proto dependency name.
Prost makes assumptions on how modules will be imported, where the proto and rust generated code modules match, but does not auto generate the module. We had a mismatch of singular -> plural in two places this resolves that. 
- updates generated rust `account` and `transaction` modules to `accounts` and `transactions`
test suite

fix(proto): fix import name mismatch

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/ibc/ics20_transfer.rs
crates/astria-sequencer/src/ibc/ics20_withdrawal.rs

Bumps penumbra deps to no longer use penumbra-specific key.
The `penumbra_ibc::component::packet::IBCPacket<Unchecked>::send_packet_check` attempts to read a timestamp stored under a penumbra specific key which we never write. This was an oversight in penumbra and recently fixed.
Unblocks e2e testing.
https://github.com/penumbra-zone/penumbra/issues/4812 
https://github.com/penumbra-zone/penumbra/pull/4822

fix(sequencer): bump penumbra dep to fix ibc state access bug

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/_helpers.tpl
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Allow setting an override tag for astria-geth image.
preview environment setup with changes for both astria-geth and the monorepo can't work without setting the astria-geth image for automation to pickup 
- added an overrideTag value which will set a specific `astria-geth` image
Tested vs a preview enviornment
#1400

chore: preview environment with astria-geth changes

---

charts/sequencer-faucet/Chart.yaml
charts/sequencer-faucet/templates/configmap.yaml
charts/sequencer-faucet/templates/deployment.yaml
charts/sequencer-faucet/values.yaml

Updates `sequencer-faucet` chart to support the changes made to the sequencer faucet image for bech32m compatibility.
With the introduction of bech32m prefixed addresses, an update to the sequencer faucet was required. This PR updates the `sequencer-faucet` helm chart to use the new faucet.
* ADDED `SEQUENCER_FAUCET_MINUTE` - rate limit on requests, default `1 day`
* ADDED `SEQUENCER_ADDRESS_PREFIX` - sequencer prefix address, default `astria`
* ADDED `SEQUENCER_NATIVE_DENOM` - asset to transfer upon request, default `nria`
Tested locally against the latest kubernetes cluster

Chore(Charts): seq-faucet bech32m chart update

---

charts/deploy.just
crates/astria-cli/src/commands/bridge/collect.rs

Adds a flag `--force`/`-f` to `astria-cli bridge collect-withdrawals` to overwrite the output target if it exists.
When running the [smoke CLI test](https://github.com/astriaorg/astria/blob/acff940abd2dd9857e038323ed6eb8aa88016a87/charts/deploy.just#L342-L435) a temporary file is created to pass to `astria-cli bridge collect-withdrawals`, which immediately fails because it refuses to overwrite an existing file. This patch adds a flag to overwrite it.
- Add a flag `-f/--force` to the `astria-cli bridge collect-withdrawals` subcommand to overwrite the file passed to it
This fixes a broken test.
Partially addresses https://github.com/astriaorg/astria/issues/1392

fix(cli, tests): add force flag to overwrite withdrawal target path

---

charts/deploy.just
charts/ibc-test.just

Fail smoke tests eagerly if one command fails.
Smoke test scripts kept executing even though some of their commands failed. This patch uses the bash built-in `set -e` to immediately exit tests with non-zero exit code.
- Use `set -e` in all smoke tests.
This correctly fails tests if the conditions don't apply (tested offline and verified in CI).
Partially addresses https://github.com/astriaorg/astria/issues/1392.
This patch will fail CI until after https://github.com/astriaorg/astria/pull/1393 is merged.

fix(test): fail smoke test scripts eagerly if a command fails

---

charts/deploy.just

Fixes the conditionals that determine whether a smoke test passes.
Many smoke tests incremented a fetch-counter as long as it was `counter < max`, but the test was for `counter > max`, which was never reached, and hence the test passed succesfully even though it actually failed. This was easily overlooked because so far the tests make use of the posix-compatible `[ $counter -lt $max_counter ]` and `[ $counter -gt $max_counter]`. But since all tests require bash this patch changes it to use `(( ))`.
- Change all smoke test scripts to use the the bashism `(( $counter < $max_counter ))` for incrementing the counter, and `(( $counter >= $max_counter ))` to check for failure.
This correctly fails tests if the conditions don't apply (tested offline and verified in CI).
Partially addresses …

fix(test): use correct conditions to dermine smoke test success

---

crates/astria-core/src/generated/astria.protocol.genesis.v1alpha1.rs
crates/astria-core/src/generated/astria.protocol.transactions.v1alpha1.rs
crates/astria-core/src/generated/mod.rs
tools/protobuf-compiler/src/main.rs

The module structure for the generated rust code was messed up and didn't match the protobuf package definitions. That messed up type references created by prost.

fix(core): restructure modules to match proto

---

crates/astria-sequencer/src/benchmark_utils.rs

Recent changes to the mempool broke the benchmarks.  This PR fixes that.
Specifically, the benchmarks tests were failing in two ways: the limit on number of parked txs per account was causing the addition of txs to fail, and the pending nonce was returning `None` in the tests.
This was all due to the current account nonce being provided as 0, but the txs started from nonce 1, meaning they weren't eligible for adding to the pending queue.
- Ensure the txs all end up in the pending queue by having the txs start from nonce 0.
Ran the benchmark and observed the full suite passing.
Closes #1384.

fix(sequencer): update mempool benchmarks (ENG-733)

---

crates/astria-composer/src/collectors/geth.rs
crates/astria-composer/src/executor/mod.rs
crates/astria-composer/src/lib.rs
crates/astria-composer/src/utils.rs

Shortened and streamlined geth and executor `run_until_stopped()` functions to get rid of clippy exceptions and ensure events are emitted within spans.
#1326 removed instrumentation on these `run_until_stopped()` functions, which revealed a clippy warning for too many lines. Additionally, this made it so that logging inside these functions would not be emitted within any span.
- Delegated many tasks to helper functions with instrumentation.
- Created new `utils` module to house a shared `report_exit_reason()` function.
- Moved `ensure_chain_id_is_correct()` and `get_latest_nonce()` to `init()` (previosuly `pre_run_checks()`)
Passing all tests.
Part of #1321

refactor(composer): streamline geth and executor `run_until_stopped`

---

crates/astria-bridge-contracts/src/lib.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs
crates/astria-cli/src/commands/bridge/collect.rs

Brief summary of the changes made, ie "what?"
- Separate the errors for getting logs from the conversion errors
- Conversion returns a `Result<Vec<Result<Action, WithdrawalConversionError>>, GetWithdrawalLogsError> ` instead of `Result<Vec<Action>, GetWithdrawalActionsError>`
- Handle failed conversions in the cli and withdrawer crates
- Unit tests for the conversions will be added in a subsequent PR: 
- This fixes the bug described in #1251, where a single withdrawal which fails to be converted to an action will cause the entire rollup block's batch of withdrawals to fail, causing the withdrawer to be stuck.
closes #1251

fix(cli, bridge-withdrawer): dont fail entire block due to bad withdraw event

---

crates/astria-conductor/src/celestia/fetch.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/src/conductor.rs
crates/astria-conductor/src/executor/channel.rs
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/sequencer/mod.rs

Added instrumentation to `astria-conductor`
Adding instrumentation to all async calls will aid in tracing since spans will be emitted even if no events happen under them.
- Added instrumentation to all async function calls that are not long-lived.
- Added instrumentation on some non-async functions that utilize logging such that logging occurs within a span.
- Removed instrumentation on `run_until_stopped()` functions.
- Minor refactoring of `run_until_stopped()` functions to ensure logging occurs within spans.
Part of #1321

chore(conductor): Add instrumentation

---

charts/celestia-local/Chart.yaml
charts/celestia-local/files/scripts/init-celestia-appd.sh
charts/celestia-local/files/scripts/start-bridge.sh
charts/celestia-local/templates/configmap.yaml
charts/celestia-local/values.yaml
charts/celestia-node/Chart.yaml
charts/celestia-node/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

`celestia-app` and `celestia-node` version bump to support lateset `mocha-4` upgrade
celestia mocha-4 testnet went through an upgrade, devnets rollups are not getting firm blocks duo to it. 
- changes flag `keyring.accname` -> `keyring.keyname`
- adds fee field for genTx
- bumps celestia images
- locally vs latest components, confirmed getting firms
- will run on devdev before merging

chore(charts): bump celestia versions

---

.github/workflows/docker-build.yml

Added missing test.
The CI target `docker` should depend upon `ibc-bridge-test`.
- added missing test
N/A

chore(ci): include `ibc-bridge-test` in `docker` CI target

---

crates/astria-core/src/crypto.rs
crates/astria-sequencer/src/app/tests_app.rs
crates/astria-sequencer/src/authority/mod.rs
crates/astria-sequencer/src/benchmark_utils.rs

Added a lazily-initialized field `address_bytes` to `VerificationKey`.
Testing showed that `address_bytes` was called multiple times on a given `VerificationKey` (up to 11 times in some cases).  Each time the key's bytes were being hashed, so this change ensures that hashing only happens once for a given verification key instance.
Note that this was implemented previously in #1111 and was then reverted in #1124.  However, when reverted, the manual impls of `PartialEq`, `Eq`, `PartialOrd`, `Ord` and `Hash` were left as-is, as were the unit tests for these.  Hence this PR doesn't need to make any changes to these trait impls or tests.
- Added `address_bytes: OnceLock<[u8; ADDRESS_LEN]>` to `VerificiationKey`.
No new tests required.  
Closes #1351.

chore: memoize `address_bytes` of verification key

---

crates/astria-sequencer-relayer/src/api.rs
crates/astria-sequencer-relayer/src/relayer/celestia_client/builder.rs
crates/astria-sequencer-relayer/src/relayer/celestia_client/mod.rs
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/read.rs
crates/astria-sequencer-relayer/src/relayer/submission.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs
crates/astria-sequencer-relayer/src/sequencer_relayer.rs

Added instrumentation to `astria-conductor`
Adding instrumentation to all async calls will aid in tracing since spans will be emitted even if no events happen under them.
- Added instrumentation to all async function calls that are not long-lived.
- Removed instrumentation on long-lived functions.
- Minor refactoring of `run()` functions to ensure logging occurs within spans.
Part of #1321

chore(sequencer-relayer): Add instrumentation

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/storageclasses.yaml
charts/evm-rollup/templates/volumes.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Changes to the value used for naming in volumes and storage
The volume and storage class has a bug for production deployment where rollup name is not being set properly
- use templated global rollup name value instead of old one
- removes unused blockscout storage and volume
run locally, against devdev
This unblocks an issue with preview environments

chore(charts): rollupName templates

---

Cargo.lock
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-cli/Cargo.toml
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Regular 2 week release cuts, includes breaking changes to sequencer, bridge-withdrawer, patch updates for composer, conductor and cli.

release: end of iteration release cuts

---

Cargo.lock
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/grpc/slinky.rs
crates/astria-sequencer/src/slinky/oracle/state_ext.rs

Extensions on `cnidarium::StateRead` should implement a stream rather than allocate and collect into datastructures.

refactor(sequencer): use streams for fetching slinky data from state

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Update geth tag to `latest` for https://github.com/astriaorg/astria-geth/pull/42
#1410 required changes to `astria-geth`, which necessitated changing the geth dev tag to be the specific PR number. Now that the geth PR is merged, we can bump the tag.
- Changed `evm-rollup` geth dev tag to `latest` and bumped chart versions.

chore(chart): update geth tag

---

dev/argocd/pr-preview-envs/sequencer-appset.yaml

Updates a required pull-request label in order to create a preview env for the sequencer component
There was a typo in the manifest configuration.
- Changed `evm` to `sequencer` as a required PR label for creating preview environments.
These were manually applied to the existing argocd dev instance

fix(ci): typo for required field in sequencer preview-env

---

.github/workflows/docker-build.yml
.github/workflows/reusable-docker-build.yml

We have a workflow docker build which specifies a component but that was only building that component if the tag passed in was also a target tag.

fix: build docker when workflow explicitly includes component

---

crates/astria-sequencer/src/transaction/mod.rs

The error message for stateless checks on `BridgeUnlock` actions incorrectly states `BridgeLock` as the failing error.
- change the error message that wraps the stateless check for `BridgeUnlock` actions
closes #1465

fix(sequencer): Fix incorrect error message from BridgeUnlock actions

---

.github/workflows/reusable-docker-build.yml
dev/argocd/pr-preview-envs/evm-appset.yaml
dev/argocd/pr-preview-envs/sequencer-appset.yaml

Updates preview environment manifests to use the exact commit sha when referencing artifacts to deploy (docker images). Also adds links in the GUI back to the PR and commit.
This is to ensure that any subsequent updates to a PR will always result in the preview env looking for the rebuilt image (tagged with full commit hash) rather than assuming a cached one might be valid (e.g. tagged with PR number).This change is in addition to setting the imagePullPolicy to Always to make the configuration explicit.
- Update github action to tag docker images with the full commit hash
- Manually tested by applying the preview environment manifests on dev cluster and creating a new PR to verify images were tagged correctly and that ArgoCD pulled the correct image.

fix(ci): use commit SHA instead of PR number preview-env images

---

crates/astria-core/src/primitive/v1/asset/denom.rs
crates/astria-core/src/protocol/test_utils.rs
crates/astria-core/src/sequencerblock/v1alpha1/block.rs
crates/astria-sequencer-utils/src/blob_parser.rs
crates/astria-sequencer/src/accounts/mod.rs
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/address/state_ext.rs
crates/astria-sequencer/src/api_state_ext.rs
crates/astria-sequencer/src/app/tests_app/mod.rs
crates/astria-sequencer/src/app/tests_block_fees.rs
crates/astria-sequencer/src/app/tests_breaking_changes.rs
crates/astria-sequencer/src/app/tests_execute_transaction.rs
crates/astria-sequencer/src/assets/state_ext.rs
crates/astria-sequencer/src/bridge/bridge_lock_action.rs
crates/astria-sequencer/src/bridge/state_ext.rs
crates/astria-sequencer/src/ibc/ics20_transfer.rs
crates/astria-sequencer/src/ibc/ics20_withdrawal.rs
crates/astria-sequencer/src/ibc/state_ext.rs
crates/astria-sequencer/src/transaction/checks.rs
crates/astria-sequencer/src/utils.rs
crates/astria-telemetry/src/display.rs

Fixes incorrect addresses in ics20 refunds, and fixes/adds source vs sink zone detection of received/refunded asets.
This PR started with the goal of using `Ics20WithdrawalFromRollup.rollup_return_address` when emitting ics20 deposit events instead of the rollup's bridge address (which for the rollup was quite meaningless).
However, because the original logic was overly convoluted, this patch evolved into a refactor which subsequently revealed 2 more bugs.
- Refactor ics20 logic: split up `execute_ics20_transfer` into two functions `receive_tokens` and `refund_tokens`
- Fix deposit events being emitted with the packet sender/bridge address as the receiving address on the rollup: instead use `Ics20WithdrawalFromRollup.rollup_return_address` which is the address originally supplied and …

fix, refactor(sequencer): refactor ics20 logic

---

.cargo/audit.toml
crates/astria-telemetry/src/metrics/builders.rs

Ignore RustSec warning.
We get a non-critical warning when running `cargo audit`: [RUSTSEC-2024-0370](https://rustsec.org/advisories/RUSTSEC-2024-0370).
When running `cargo tree -i -p=proc-macro-error` we can see that `proc-macro-error` is a dependency of `borsh` which is already at the latest version.
Given that the RustSec report doesn't suggest any concrete problems with `proc-macro-error` and how difficult it will be to move away from this dependency, I have just ignored this warning in CI.
- Ignore RustSec warning in `.cargo/audit.toml`.
- Also fixed a typo causing a compiler warning.
Ran `cargo audit` locally.

fix: ignore `RUSTSEC-2024-0370`

---

crates/astria-sequencer/src/main.rs

Added `astria_eyre::install()` call to `main.rs`.
https://github.com/astriaorg/astria/pull/1387 switched the sequencer from `anyhow` to `eyre` usage, but did not install the `astria-eyre` error hook.
Added `astria_eyre::install()` call to `main.rs`.
closes #1551

fix(sequencer): install astria-eyre hook

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/mod.rs

Added error context to sequencer GRPC client construction.
https://github.com/astriaorg/astria/pull/1510/files#r1766478324
- Added helper function for constructing the sequencer GRPC client and switched from using `Endpoint::new()` to `connect_lazy()`.
- Added error context to sequencer GRPC client construction.
closes #1527
closes #1542

chore(bridge-withdrawer): better grpc client construction

---

crates/astria-sequencer/src/service/mempool.rs

We were using `e.to_string` to provide error messages in `CheckTx` responses. This results in dropping the context that the error objects carry around, only providing the top level error. This uses `anyhow`'s `format!("{e:#}")` to format the error with its context.
For example, the following snippet:
```rust
use anyhow::anyhow;
use astria_eyre::anyhow_to_eyre;
fn main() {
let _ = astria_eyre::install();
let anyhow_err = anyhow!("anyhow 0").context("anyhow 1");
let combined = anyhow_to_eyre(anyhow_err)
.wrap_err("astria eyre 0")
.wrap_err("astria eyre 1");
println!("err context: {combined:#}");
}
```
Will produce the following output:
```
err context: {"0": "astria eyre 1", "1": "astria eyre 0", "2": "anyhow 1", "3": "anyhow 0"}
```
- changed all instances of `e.to_string()` to …

fix(sequencer): provide context in checktx response log

---

.github/workflows/docker-build.yml
charts/deploy.just
charts/ibc-test.just
justfile

Adds a image build for the cli tool, and updates the justfiles to utilize it.
There are two workflows which this fixes: 1) Users running the repo locally and running smoke tests could encounter issues by not having the cli installed or not having it updated. Now we just need to have docker. Additionally, we have been needing to build the `just-cli` for each of our smoke test runs. Instead all can now rely on the docker image.
- Starts creating a new CLI image
- Updates the smoke tests to utilize CLI image in place of installing the cli
- Update docker build scripts to make it easier to use a local image locally
CI/CD on this PR
closes #1475

ci(cli): astria-cli image for smoke tests

---

.github/workflows/reusable-build.yml

We accidentally broke the reusable build script with a poorly formatted workflow file in https://github.com/astriaorg/astria/pull/1523/ this fixes it.

fix(ci): workflow file issue

---

crates/astria-cli/src/commands/sequencer.rs
crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/conductor/inner.rs
crates/astria-core/src/protocol/memos/snapshots/astria_core__protocol__memos__v1alpha1__tests__ics20_transfer_deposit_memo_snapshot.snap
crates/astria-core/src/protocol/memos/snapshots/astria_core__protocol__memos__v1alpha1__tests__ics20_withdrawal_from_rollup_memo_snapshot.snap
crates/astria-core/src/protocol/memos/v1alpha1.rs
crates/astria-core/src/protocol/transaction/v1alpha1/mod.rs
crates/astria-core/src/protocol/transaction/v1alpha1/snapshots/astria_core__protocol__transaction__v1alpha1__tests__signed_transaction_hash.snap
crates/astria-eyre/src/lib.rs
crates/astria-sequencer/src/address/state_ext.rs
crates/astria-sequencer/src/api_state_ext.rs
crates/astria-sequencer/src/authority/action.rs
crates/astria-sequencer/src/bridge/query.rs
crates/astria-sequencer/src/bridge/snapshots/astria_sequencer__bridge__state_ext__tests__storage_keys_have_not_changed-2.snap
crates/astria-sequencer/src/bridge/snapshots/astria_sequencer__bridge__state_ext__tests__storage_keys_have_not_changed-3.snap
crates/astria-sequencer/src/bridge/snapshots/astria_sequencer__bridge__state_ext__tests__storage_keys_have_not_changed-4.snap
crates/astria-sequencer/src/bridge/snapshots/astria_sequencer__bridge__state_ext__tests__storage_keys_have_not_changed.snap
crates/astria-sequencer/src/bridge/state_ext.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/mempool/mod.rs
crates/astria-sequencer/src/mempool/transactions_container.rs
crates/astria-sequencer/src/proposal/commitment.rs
crates/astria-sequencer/src/sequence/action.rs
crates/astria-sequencer/src/sequence/state_ext.rs
crates/astria-sequencer/src/service/consensus.rs
crates/astria-sequencer/src/service/info/mod.rs

A trivial rename of some modules.
It's canonical to name unit test modules as `tests`.  We currently have a mixture of `test` and `tests` throughout the codebase.
- Renamed all `test` modules to `tests`.  No actual tests were changed.

chore: rename all modules named `test` to `tests`

---

crates/astria-conductor/tests/blackbox/soft_and_firm.rs

Fixed flaky conductor restart test.
`soft_and_firm::conductor_restart_on_permission_denied` would sometimes fail due to receiving the firm block first.
- Added short delay to firm block response so the conductor will always receive the soft block first.
Test now passing.
closes #1566

fix(conductor): fix flaky restart test

---

.github/workflows/docker-build.yml
charts/ibc-test.just

Increases ibc-bridge-test and hermes deployment timeouts
The ibc-bridge-test fails occasionally, lacking time to setup hermes clients.  
Increased timeouts both in github workflow and kubectl
closes #1586

fix(ci): ibc bridge test timeout

---

containerfiles/Dockerfile

Fixes container images to use the `$TARGETBINARY` build param as the name of the binary run in the image entrypoint.
Before this patch, the containerfile entrypoint used a symlinked `/usr/local/bin/entrypoint` as the entrypoint, which caused the name of the binary to be `"entrypoint"`. This itself was to workaround to the `ENTRYPOINT` command not allowing for variables in exec form. This patch instead creates an ad-hoc script which itself executes `$TARGETBINARY`, and uses this script as the entrypoint.
Together with the script using `exec` and the exec form of `ENTRYPOINT` the expected binary (and process) name are used.
Taking `astria-cli`'s help message as an example:
Before:
```
Get the balance of a Sequencer account
Usage: entrypoint sequencer balance get [OPTIONS] <ADDRESS>
``` …

fix(docker): use target binary build param as name of image entrypoint

---

README.md
charts/README.md

Updates default cluster endpoints and paths

chore(docs): endpoints

---

charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/_helpers.tpl
charts/sequencer-relayer/templates/prometheusrule.yaml
charts/sequencer-relayer/templates/service.yaml
charts/sequencer-relayer/templates/servicemonitor.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Fixes prometheus rules and metrics templates for both `sequencer` and `sequencer-relayer` charts
ServiceMonitors for alerting and monitoring is missing on sequencer-relayer chart
- adds service monitor and prometheus rules templating for sequencer-relayer
- fixes sequencer app labels 
locally, dusk-10
-enables metrics and alerts on sequencer, sequencer-relayer charts
closes #1597

fix(charts): sequencer prometheus rules  

---

.github/workflows/scheduled.yml
.github/workflows/test.yml

This is an upgrade of the `audit-check` package used in CI for running `cargo audit`.
This upgrade includes [a fix](https://github.com/rustsec/audit-check/pull/20) for an issue where `audit-check` would not respect the committed `Cargo.lock` file.
- Upgrade `audit-check`.

chore(ci): upgrade audit-check

---

crates/astria-sequencer/src/app/test_utils.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/mempool/mod.rs
crates/astria-sequencer/src/mempool/transactions_container.rs

Switched the method of constructing transactions from a constructor to a builder pattern. 
We're about to add more relevant transaction fields (ActionGroup type, valid block number), and this change will make it possible to add these extra fields without having to change all of the other tests. 
The changes are contained to the unit tests to `crates/astria-sequencer/mempool/transaction_container.rs`. All unit tests still pass.

refactor(sequencer): use builder pattern for transaction container tests

---

.github/code-freeze-filter.yaml
.github/workflows/code-freeze.yml
crates/astria-sequencer-relayer/src/main.rs

Adds functionality to block PRs into sections of code under code freeze within the CI workflow
We are moving towards mainnet & undergoing audits. During past audits we have not had a firm mechanism to ensure we are not making changes to code under audit. This provides a stopper, but can be overriden still.
- New CI workflow that checks for changes to code frozen pathways, fails and adds errors to those files as well as building an error summary. Using the `override-freeze` tag disables the check and changes reports to warnings.
Ran against this PR with multiple changes, tested both adding and removing the label to override.

ci: code freeze through github actions

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
dev/values/rollup/dev.yaml

BridgeSenderAddress now configured per bridge
Follow up on production deployment, bridgeSenderAddress should be configurable per bridge account. This PR adjusts evm-rollup chart to support such change.
- remove `astriaBridgeSenderAddress`
- update `astriaBridgeAddresses`
non breaking, genesis template changes. set `global.dev=false` to run older versions
against dusk-10, locally

chore(charts): genesis template to support latest changes

---

crates/astria-sequencer/src/mempool/transactions_container.rs

Simplified logical statements in `transaction_priority_comparisons_should_be_consistent_nonce_diff()`.
Previously there was an allow for `clippy::nonminimal_bool`. The reasoning behind it was to match documented behavior. This change is meant to explicitly state the expected behavior while still simplifying the boolean expressions. This is in response to this comment: https://github.com/astriaorg/astria/pull/1561#discussion_r1778613519
- Simplified boolean expressions and moved the non-simplified versions to the comments where applicable to provide context on the documented behavior.
closes #1583

chore(sequencer): simplify boolean expressions in `transaction container`

---

crates/astria-core/src/protocol/transaction/v1alpha1/action_group/mod.rs
crates/astria-core/src/protocol/transaction/v1alpha1/action_group/tests.rs
crates/astria-core/src/protocol/transaction/v1alpha1/mod.rs

This PR makes empty transactions (i.e. no actions) invalid. 
Transactions with no actions cost nothing and could be used to clog the mempool and blocks. In the future if we want a dummy transaction to aid in removing actions via nonce replacement, we could do a noop action like a zero balance transfer. 
Made empty transactions invalid during the `UnsignedTransaction` construction process. 
Unit test was added.
Empty transactions are no longer valid. 
closes #1607

feat(sequencer)!: make empty transactions invalid 

---

crates/astria-core/src/generated/astria.bundle.v1alpha1.rs
crates/astria-core/src/generated/astria.bundle.v1alpha1.serde.rs
crates/astria-core/src/generated/astria.sequencerblock.v1alpha1.rs
crates/astria-core/src/generated/astria.sequencerblock.v1alpha1.serde.rs
crates/astria-core/src/generated/mod.rs
proto/executionapis/astria/bundle/v1alpha1/bundle.proto
proto/executionapis/astria/bundle/v1alpha1/optimistic_execution.proto
proto/sequencerblockapis/astria/sequencerblock/v1alpha1/optimistic_block.proto

This adds the protobuf definitions for optimistic block stream and the bundle stream.
The Auctioneer will auction off a bundle slot which will be placed at the top of the rollup block deterministically during execution. The APIs in this PR are used to drive the bundle auction (detailed in [this document](https://www.notion.so/astria-org/20240919-Status-Update-1066bd31a90c80b68bb2ea9b898645d0)). At a high level:
The Auctioneer receives blocks optimistically from the sequencer in order to maximize the auction duration.
While the auction is running, the Auctioneer receives orders from the rollup node that have been validated against the optimistic block.
After a block is committed, the Auctioneer will submit the highest paying bundle for inclusion by the sequencer.
1. The Sequencer will …

feat(proto): add bundle and optimistic block apis

---

charts/hermes/Chart.yaml
charts/hermes/files/config.toml
charts/hermes/templates/_helpers.tpl
charts/hermes/templates/deployment.yaml
charts/hermes/templates/prometheusrule.yaml
charts/hermes/templates/service.yaml
charts/hermes/templates/servicemonitor.yaml
charts/hermes/values.yaml

Fixes hermes related monitoring service with Prometheus scraping and adds prometheus rules template for alerts.
hermes monitoring service is misconfigured and alerts are yet to be implemented.
adds `serviceMonitor` and `prometheusRule` templates enabling data scraping and alerts with prometheus.
also fixes current service porting and default image and labels.
against dusk-10, locally
enables `hermes-relayer` metrics scraping

fix(charts): hermes monitoring and prometheus rules 

---

Cargo.lock

Updated the version of `futures-util`.
Running `cargo audit` yields a non-critical warning that futures-util v0.3.30 has been yanked.
Ran `cargo update -p futures-util` to increase the version.
Ran normal test suite, no additional tests added.

chore: cargo audit warning

---

crates/astria-cli/src/utils.rs

Ensuring checkTx passes before waiting for inclusion
When using `submit_transaction_sync` method, cli should exit on `checkTx` error code. Currently, cli first waits for inclusion which will never happen as the transaction failed `checkTx`
closes #1635

fix(cli): ensure checkTx passes before waiting for inclusion

---

charts/composer/Chart.yaml
charts/composer/templates/_helpers.tpl
charts/composer/templates/deployment.yaml
charts/composer/templates/service.yaml
charts/composer/templates/servicemonitor.yaml
charts/composer/values.yaml
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/templates/_helpers.tpl
charts/evm-bridge-withdrawer/templates/prometheusrule.yaml
charts/evm-bridge-withdrawer/templates/service.yaml
charts/evm-bridge-withdrawer/templates/servicemonitor.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Fixes prometheus rules and metrics templates for `geth`, `conductor`, `bridge-withdrawer` and `composer` charts
ServiceMonitors for alerting and monitoring is missing on charts
- adds service monitor and prometheus rules templating for composer, conductor and bridge-withdrawer
- fix service labels and selectors for all charts
- adds default labels
against dusk-10
- enables metrics and alerts on rollup apllications
closes #1600

fix(charts): rollup application monitoring

---

crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/tests_app/mod.rs

Changes the comparison when deciding if we need to re-execute a proposal to use the validator address and the timestamp as identifiers, to enable horcrux sentry nodes to not have app hash clashes. 
When running horcrux all sentry nodes act as the same validator and all nodes create a new proposal, but the signer only signs one of them. This creates issues since all sentry nodes except the signed node will not reexecute the proposal since it was created by their validator address even though the proposals are different. Timestamps are used to add additional fingerprinting to this without adding high computation cost.
- Utilize timestamp as part of identifying whether to clear and execute proposal in prepare proposal
A validator reported this issue when running testnet, and similar changes …

fix(sequencer): fix app hash in horcrux sentries

---

crates/astria-composer/src/collectors/grpc.rs
crates/astria-composer/tests/blackbox/grpc_collector.rs
crates/astria-core/src/execution/v1alpha2/mod.rs
crates/astria-core/src/generated/astria.composer.v1alpha1.rs
crates/astria-core/src/generated/astria.composer.v1alpha1.serde.rs
crates/astria-core/src/generated/astria.sequencerblock.v1alpha1.rs
crates/astria-core/src/generated/astria.sequencerblock.v1alpha1.serde.rs
crates/astria-core/src/primitive/v1/mod.rs
crates/astria-core/src/protocol/bridge/v1alpha1/mod.rs
crates/astria-core/src/protocol/transaction/v1alpha1/action/mod.rs
crates/astria-core/src/sequencerblock/v1alpha1/block.rs
crates/astria-core/src/sequencerblock/v1alpha1/celestia.rs
crates/astria-sequencer/src/grpc/sequencer.rs
proto/composerapis/astria/composer/v1alpha1/grpc_collector.proto
proto/sequencerblockapis/astria/sequencerblock/v1alpha1/block.proto

Replaces `bytes` with `astria.primitive.v1.RollupId` in all protobuf types that were still outstanding.
When we introduced the `astria.primitive.v1.RollupId` type the goal was to use it in all places where previously we had bare `bytes`. Some places were overlooked, this patch fixes that.
- Update `astria.composer.v1alpha1.SubmitRollupTransactionRequest.rollup_id` and `astria.sequencerblock.v1alpha1.FilteredSequencerBlock.all_rollup_ids` to be `astria.primitive.v1.RollupId` rather than bytes.
All tests still pass which shows that smoke tests and blackbox tests understand the new format.
This is a breaking change because all downstream users of filtered sequencer blocks must understand the new format.
The author of this patch believes that it is not consensus breaking.
Closes …

chore(proto)!: prefer astria.primitive.v1.RollupId over bytes

---

crates/astria-cli/src/sequencer/ics20_withdrawal.rs
crates/astria-cli/src/sequencer/mod.rs
crates/astria-cli/src/utils.rs

Adds Ics20Withdrawal command to the cli for [Ics20Withdrawal](https://buf.build/astria/protocol-apis/docs/main:astria.protocol.transactions.v1alpha1#astria.protocol.transactions.v1alpha1.Ics20Withdrawal) action
part of adding all sequencer actions as cli commands.
- adds `astria-cli sequencer ics20-withdrawal` command
- There will be a follow-up PR to add CLI test after the ongoing test refactor is completed.
- Tested by performing a manual withdrawal to an IBC chain. Refunds the sender address on failure, which was tested by sending an Ics20Withdrawal with an invalid asset.
part of #1474 
closes #1623

feat(cli): add command to perform ics20 withdrawals

---

charts/ibc-test.just
crates/astria-sequencer/src/ibc/ics20_transfer.rs

Support ics20 transfer from a counterparty to the astria sequencer.
Currently, when performing an ics20 transfer to the Sequencer, the transfer only accepts bech32m address formats. This is inconsistent with refunding failed ics20 from Sequencer to the counterparty, where both compat (bech32) and normal (bech32m) addresses are accepted. Sequencer should accept both.
The main use case is when receiving assets from Noble (such as USDC). While Noble only enforces bech32 when handling failed ics20 transfers, this still requires ics20 transfers from Astria Sequencer to Noble to be bech32 (and not bech32m) encoded. The bech32 compatible address is hence the sender address that will be known by the counterparty/Noble, and we must allow transfers of funds back to it.
- sequencer now accepts …

fix(sequencer)!: allow compat prefixed addresses when receiving ics20 transfers

---

charts/sequencer/Chart.yaml
charts/sequencer/templates/configmaps.yaml
crates/astria-sequencer/src/config.rs

remove unused enable mint env. We removed the mint module in https://github.com/astriaorg/astria/pull/1134, the config var was unused but left in.

chore(sequencer): remove unused enable mint env

---

crates/astria-sequencer/local.env.example

removes `ASTRIA_SEQUENCER_ENABLE_MINT` variable from example env config
Did not remove from example config in previous PR

fix: remove enable mint entry from example env config

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/hermes/Chart.yaml
charts/hermes/values.yaml
dev/values/hermes/local.yaml

We merged major proto updates, dependent charts have been updated in latest and releases to use those.

chore(charts): update back to latest after proto merge

---

crates/astria-sequencer/src/accounts/storage/values.rs
crates/astria-sequencer/src/assets/storage/values.rs

Removes an unused variant of the internal storage implementation of sequencer asset component.t
As part of https://github.com/astriaorg/astria/pull/1647 fees were moved from the assets to the fees component. The present variant was overlooked.
- Remove a storage variant from the assets component.
Not applicable. Dead code.
This is not a breaking change because a) the variant was never used (there was not even a theoretic way to write it after https://github.com/astriaorg/astria/pull/1647) and b) no variants existed after the variant. If they had, this change would lead to a shift in the variants, causing breakage.

refactor(sequencer): remove unused asset storage variant

---

crates/astria-cli/src/sequencer/account.rs

Create account command was returning a hexadecimal address, leading to a less user-friendly experience.
- Now returns a Bech32m prefixed address
Locally executing the command
closes #1619

chore(cli): return Bech32m Prefixed Address

---

crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-cli/Cargo.toml
crates/astria-composer/Cargo.toml
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer/Cargo.toml

Removes redundant `[[bin]]` entries in all crates' `Cargo.toml`.
Rust crates with a `main.rs` default to the name of the crate when naming it binaries. An extra entry that uses the same name is redundant and confusing.
Remove all `[[bin]]` entries from all crates' `Cargo.toml`.
Docker builds still run. In practice nothing has changed.

chore: remove redundant bin entries from all crates' Cargo.toml

---

.github/workflows/docker-build.yml
charts/ibc-test.just
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
dev/values/validators/all-without-native.yml

This PR adds an ibc-test to CI, Testing the functionality of sequencer network initialized without a native aset.
- adds smoke test for non native asset case
locally against a cluster, running the new ibc-test just commands

feat(ci): add non native asset Ibc test 

---

crates/astria-bridge-contracts/src/lib.rs
crates/astria-bridge-withdrawer/tests/blackbox/helpers/test_bridge_withdrawer.rs

Use the full hex encoded sender of the smart contract event as the rollup return address in the ics20 withdrawal event memo.
Before this patch, the `astria.protocol.memos::v1::Ics20WithdrawalFromRollup` memo used the abbreviated form of the ethers contract event sender, making it impossible to return funds if necessary. Specifically, the field was set as `rollupReturnAddress":"0xc59a…2d94"`
After this patch, the full address is used, making it possible to identify the sender.
- change the event conversion logic to use `AbiEncode::encode_hex()` instead of `H160::to_string()`
- update the black box test mock to also do this
- This is a breaking change because two differerent versions of bridge-withdrawer will produce different sequencer transactions.
Original issue where this was first …

fix(bridge-withdrawer)!: correctly identify rollup return address in ics20 withdrawal actions

---

.github/workflows/docker-build.yml
charts/ibc-test.just

Adds a test for case in which there is an IBC timeout after rollup withdrawal to ensure that the funds are returned to the rollup.  This is done by using the `astria-cli` withdrawal functionality, after collecting withdrawals we manually override the revision height to one which is after the current sequencer chain consensus height but below the destination chains current height. This triggers an automatic instant timeout. 
We previously had no e2e testing to ensure withdrawals were refunded appropriately.
Run against binaries which were known to have issues, as well as update that should fix.

ci: add test for rollup refund

---

Cargo.lock
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/fees/action.rs
crates/astria-sequencer/src/fees/query.rs
crates/astria-sequencer/src/fees/state_ext.rs

Uses a stream to fetch all allowed assets.
Prior to this patch fetching all allowed assets from state was done using a future that was itself a loop over a (rocksbd) prefix key stream. This future always resulted in a vector of assets.. This patch instead replaces it by a stream, moving the decision for how to consume the items to the call site.
- Replaces `fees::StateReadExt::get_allowed_assets` by `fees::StateReadExt::allowed_assets` and a typed stream implementation.
- Rewrites the ABCI query for allowed fee assets in terms of this stream. If reading a fee asset from state failed this query will now return an empty collection rather than an internal server error.
- Update the fee asset change action removal subcommand to check if the allowed asset stream contains at least 1 fee asset …

refactor(sequencer): use stream for allowed assets, fix query

---

crates/astria-sequencer/src/accounts/component.rs
crates/astria-sequencer/src/accounts/state_ext.rs
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/tests_app/mod.rs
crates/astria-sequencer/src/assets/state_ext.rs
crates/astria-sequencer/src/fees/component.rs
crates/astria-sequencer/src/mempool/mempool_state.rs

Moves the initialization of allowed assets from the overall app to the fees component.
https://github.com/astriaorg/astria/pull/1647 moved fee asset state handling to the new `fees` component. It was overlooked that writing allowed fee assets should also happen in its init chain logic.
- Move initialization of app init state to the fees component.
Nothing has changed in terms of how the state is represented. Tests that rely on init chain still work.
This is not a breaking change because the state after this change looks the same.

chore(sequencer): init allowed assets in fees component

---

charts/composer/Chart.yaml
charts/composer/templates/_helpers.tpl
charts/composer/templates/deployment.yaml
charts/composer/templates/prometheusrule.yaml
charts/composer/templates/service.yaml
charts/composer/templates/servicemonitor.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

adds prometheusrule object to composer chart
Prometheus rule object file was overlooked in prior #1601 
- add prometheusRule object to enable alerts on monitoring stack
- also fixes issue with composer metric port violating targetPort length

fix(charts): composer PrometheusRule

---

.github/workflows/lint.yml
proto/protocolapis/astria/protocol/transaction/v1/action.proto
proto/protocolapis/astria/protocol/transaction/v1alpha1/action.proto

We have been using reserved to highlight gaps, but reserved should ideally only be utilized for reserving previously used identifiers. 
- removes reserved numbers that using were not actual breaking change
- updates workflow to allow override and to always run all breaking checks even if previous fails
This has no real breaking changes, hence allowing override. The removal of the reserved makes it so that we don't have to do this in the future when adding new fields.

chore(proto): reserved only for what would be breaking change

---

charts/deploy.just
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/templates/_helpers.tpl
charts/evm-bridge-withdrawer/templates/configmaps.yaml
charts/evm-bridge-withdrawer/templates/deployment.yaml
charts/evm-bridge-withdrawer/templates/prometheusrule.yaml
charts/evm-bridge-withdrawer/templates/secretproviderclass.yaml
charts/evm-bridge-withdrawer/templates/service.yaml
charts/evm-bridge-withdrawer/templates/servicemonitor.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Templates `evm-bridge-withdrawer` objects names.
The `evm-bridge-withdrawer` chart has hard coded name for objects in it, causing resource sharing conflicts for same namespace deployments. With this PR, objects will now be configurable with a `serviceName` variable to avoid resource sharing.
- adds new serviceName configarble value
- templated all objects names with `serviceName`
- small fixes to labels
Changes were initially done to support multiple bridge-withdrawer on devnet and testnet. Thus, changes were tested against `dusk-11` & `dawn-1 ` as well as local testing.

fix(charts): template evm-bridge-withdrawer objects names

---

charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/genesis.json
charts/sequencer/values.yaml

changes genesis to allow configuring each fee component, also make `nativeAssetBaseDenomination ` an optional field
Fees can now be added after genesis, meaning we no longer have to define them all in it. 
Also in case `nativeAssetBaseDenomination` is unset, it will not be used when initiating the state and thus should not appear in `genesis.json.
- added an if statement to remove the field in case it is nil
- can now set / unset all fees except `feeChange` in genesis
locally with helm template command

fix(charts): genesis template

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/Cargo.toml

bump penumbra to tag v0.80.7 (latest release).

chore(sequencer): bump penumbra tag

---

.github/pull_request_template.md
.github/workflows/lint.yml
.markdownlint-cli2.jsonc
README.md
crates/astria-bridge-contracts/CHANGELOG.md
crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-cli/CHANGELOG.md
crates/astria-composer/CHANGELOG.md
crates/astria-conductor/CHANGELOG.md
crates/astria-config/CHANGELOG.md
crates/astria-core/CHANGELOG.md
crates/astria-eyre/CHANGELOG.md
crates/astria-grpc-mock/CHANGELOG.md
crates/astria-merkle/CHANGELOG.md
crates/astria-sequencer-relayer/CHANGELOG.md
crates/astria-sequencer/CHANGELOG.md
crates/astria-telemetry/CHANGELOG.md
justfile

Provided changelogs.
Changelogs are good to have.
- Added changelogs to all crates for which we have GH releases.  Their release notes were ported into the changelogs.
- Added changelogs to all remaining public-facing crates.  Only `astria-merkle` has been version bumped from 0.1.0, so except for this one, all of these changelogs are initialised with only an `Unreleased` section.
- Updated the PR template to remind authors to update relevant changelogs when opening PRs.
- ~Excluded the changelog files from the markdown linter, since the format is defined by [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).~
- Added a markdownlint config file to specify the globs and removed duplicated globs lists from various places.
N/A
Closes #1687.

chore(all): add changelogs

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Updates default geth deployement to disable locals pricing
Treating txs as local is really intended for a truly local instance, where the source is the person running the node but in our case treats every tx coming through RPC as local. We don't want this.

chore(charts): disable locals in geth

---

crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs

The metric `batch_total_settled_value` was not being set to zero when blocks where empty, resulting in maintaining previous value and resetting incorrectly when no txs processed.
- Updated metric to be set to 0 when block is empty
- `batch_total_settled_value` improved

fix(bridge-withdrawer): also set metric when value 0

---

Cargo.lock
charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-bridge-withdrawer/Cargo.toml

- Set `batch_total_settled_value` metric to 0 when no withdrawals are settled [#1778](https://github.com/astriaorg/astria/pull/1768)
- Fixed ICS20 withdrawal source when using channel with more than one
port/channel combo.[#1768](https://github.com/astriaorg/astria/pull/1768)

release(bridge-withdrawer): 1.0.1 patch release

---

crates/astria-bridge-withdrawer/src/metrics.rs
crates/astria-sequencer-relayer/src/metrics.rs
crates/astria-sequencer-relayer/src/relayer/celestia_client/mod.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/metrics/into_f64.rs

This adds three new gauges to the relayer metrics to record the Celestia fees incurred in the latest submission: total fees, cost per uncompressed byte and cost per compressed byte.
The new metrics could provide useful information.
- Added three new metrics.
- Provided `IntoF64` for `u64` (for one of the new metrics) and for `u128` (for a recently-added bridge-withdrawer metric)
- Added warnings to `IntoF64` impls which have the potential for precision loss
Tests for metrics are generally still pending.  Checked the new metrics were being populated in a relayer on a local testnet.
Example output:
```
astria_sequencer_relayer_celestia_fees_total_utia{service="astria-sequencer-relayer"} 186
astria_sequencer_relayer_celestia_fees_utia_per_uncompressed_blob_byte{service="astria-sequencer-relay …
```

chore(sequencer-relayer): add metrics for recording Celestia fees

---

crates/astria-cli/src/sequencer/sudo/ibc_sudo_address_change.rs
crates/astria-cli/src/sequencer/sudo/ibc_sudo_change.rs
crates/astria-cli/src/sequencer/sudo/mod.rs

adds ibc sudo address change command
Cli currently does not support the `IbcSudoChange` action
- added `IbcSudoChange` command to the cli as sudo command
tested manually against dusk-11 network
part of #1474

feat(cli): add ibc sudo address change command

---

charts/deploy.just
crates/astria-cli/src/sequencer/bridge_account.rs
crates/astria-cli/src/sequencer/bridge_sudo_change.rs
crates/astria-cli/src/sequencer/mod.rs

Summary
Adds bridge-sudo-change command for changing bridge privileges addresses
Background
Part of adding more actions to the cli
Changes
- adds `bridge-sudo-change`  command setting bridge account privileges addresses
- adds `bridge-account get` command querying bridge account information
Testing
Locally against a cluster
Related Issues
Part of https://github.com/astriaorg/astria/issues/1474
closes https://github.com/astriaorg/astria/issues/1547

feat(cli): bridge sudo change command

---

charts/hermes/templates/servicemonitor.yaml

makes hermes chart service monitor name based on chart name or override value instead of constant value
While deploying multiple hermes instances on the same namespace there is an issue where the serviceMonitor name is identical for all instances, making the resource to be shared across apps
- serviceMonitor name now configurable
- fixes service monitor template which allows monitoring

fix: hermes service monitor 

---

charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/evm-stack/values.yaml
dev/values/rollup/dev.yaml

fixes error in local rollup deployment through the cluster
On running `just deploy-dev-rollup` helm throws an ingress pathType error. This PR fixes the error other warnings.
- bump blockscout app version
- changes sitemap.xml pathType to `ImplementationSpecific`
locally against the cluster with smoke tests.

fix(charts): local blockscout

---

charts/celestia-local/Chart.yaml
charts/celestia-local/files/scripts/init-celestia-appd.sh
charts/celestia-local/templates/configmap.yaml
charts/celestia-local/values.yaml
charts/ibc-test.just

adds a configurable value to set celestia timeout_commit to `1s` speeding bridge-tests
setting up hermes channels in CI bridge-test is slow, speeding up celestia blocktime will help reduce setup time.
added a `fast` flag to `celestia-local`, when set to true will configure celestia with a block time of `1s`. Configured `ibc-test` in CI to use the new flag.
against a local cluster

feat(charts): faster celestia blocktime In ibc-test

---

charts/celestia-local/Chart.yaml
charts/celestia-local/values.yaml
charts/celestia-node/Chart.yaml
charts/celestia-node/files/config.toml
charts/celestia-node/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

updates celestia-node and celestia-local charts to support the new versions.
Celestia mocha-4 testnet went through an upgrade, nodes should upgrade by nov 7th
- celestia-app `v2.0.0 -> v2.3.1`
- celestia-node `v0.16.0-rc -> v0.18.3-mocha`
- adjusts celestia-node` config.toml` env variables
- adds pruner service to configs
celestia-local tested locally running smoke-tests, celestia-node sync tested locally & against flame.
- celestia environment variable changes

chore(charts): celestia versions bump

---

crates/astria-core/src/protocol/test_utils.rs
crates/astria-core/src/sequencerblock/v1/block.rs
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/test_utils.rs
crates/astria-sequencer/src/service/consensus.rs

make extended commit info third injected tx, and update `SequencerBlock::try_from_block_info_and_data` to handle whether the extended commit info is in the block or not.
it makes more sense to append to the existing list of injected txs which are the two commitments at the start of the block. 
- make extended commit info the third injected tx instead of the first
- update `SequencerBlock::try_from_block_info_and_data` to handle whether the extended commit info is in the block or not
- cleanup of related unit tests
unit tests
- unbreaks `SequencerBlock::try_from_block_info_and_data`

refactor: make extended commit info third injected tx

---

.cargo/audit.toml

Ignore two new RustSec warnings.
We get two non-critical warnings when running `cargo audit`: [RUSTSEC-2024-0384](https://rustsec.org/advisories/RUSTSEC-2024-0384) and [RUSTSEC-2024-0388](https://rustsec.org/advisories/RUSTSEC-2024-0388).
<details><summary>RUSTSEC-2024-0384</summary><p>
```
Crate:     instant
Version:   0.1.13
Warning:   unmaintained
Title:     `instant` is unmaintained
Date:      2024-09-01
ID:        RUSTSEC-2024-0384
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0384
Dependency tree:
instant 0.1.13
├── fastrand 1.9.0
│   └── futures-lite 1.13.0
│       ├── isahc 1.7.2
│       │   └── astria-sequencer-relayer 1.0.0
│       └── http-types 2.12.0
│           └── wiremock 0.5.22
│               ├── astria-sequencer-relayer 1.0.0
│               ├── …
```

fix: update audit ignore list

---

charts/ibc-test.just

removes immediate celestia balance check after performing ibc-transfer **from** celestia 
Current ibc-tests checks celestia wallet balance immediately after permorming an ibc transfer, this is redundant as we check the bablance change on the sequencer side. In addition to currently being broken duo to outdated expected value, the test currently passes randomly, most likely duo to latency. 
- remove celestia balance checks from ibc transfer from celestia
- moves ibc-transfer check in `run-without-native` above fee-asset change, avoiding latency issues.
- locally tested bad behavior by adding a 1s sleep prior to the first balance check

fix(ci): remove unnecessary checks from ibc-tests

---

crates/astria-cli/CHANGELOG.md
crates/astria-cli/src/sequencer/fee_assets.rs
crates/astria-cli/src/sequencer/mod.rs

Adds `astria-cli sequencer fee-assets get` query command, getting all allowed fee-assets
The astria CLI should have a query command for all abci query paths, the PR is part of an effort to accomplish this. It also enables more robust smoke-tests.
- Adds allowed fee assets query subcommand.
Manually runs the command against local, Dawn and mainnet.
Link any issues that are related, prefer full GitHub links.
closes #1815

feat(cli): allowed fee-assets query

---

charts/hermes/Chart.yaml
charts/hermes/files/config.toml
charts/hermes/templates/configmaps.yaml
charts/hermes/templates/servicemonitor.yaml

The hermes config didn't work when path filters were used because some standard config properties were below the seperated path filter section.
Allow use of path filters on deployed hermes instances.

fix(charts): fix hermes config

---

crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/bridge/bridge_lock_action.rs

Ensures deposits created within bridge lock actions use only trace-prefixed assets.
Currently, deposits created within a bridge lock action include whichever asset is used in the action, which can be either IBC- or trace-prefixed. This poses a problem, since our EVM has no concept of IBC-prefixed assets, and we shouldn't expect others using our network to, either. One solution discussed was to enforce all `BridgeLock` actions to use trace prefixed assets, but this would be a consensus breaking change. This aims to remedy the bug whilst making no breaking changes.
- Map any IBC-prefixed assets included in a `BridgeLock` action to trace-prefixed when constructing the `Deposit`.
- Added unit test to ensure an IBC-prefixed asset included in a bridge lock action is correctly mapped to a …

fix(sequencer)!: ensure deposits use trace-prefixed assets

---

Cargo.lock
crates/astria-core/src/connect/types.rs
crates/astria-sequencer/Cargo.toml
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/app/vote_extension.rs

Increase test coverage of the `app::vote_extensions` module and fixes issues discovered while implementing these tests.
This was work spun out of previous PRs to this feature branch to allow parallelizing efforts to complete the feature.
- Provided comprehensive unit test coverage of the `app::vote_extensions` module.
- Fixed a handful of issues uncovered.
These are tests.
No updates required - the changelogs will be updated right before the feature merges to `main`.

fix(sequencer): provide unit tests and fixes for vote extensions

---

crates/astria-sequencer/src/fees/mod.rs
crates/astria-sequencer/src/fees/state_ext.rs

Removed an unnecessary return of a `Result` from the `fees` state extension trait.
The method is infallible.
- Removed the return type from `add_fee_to_block_fees()`
Passing all tests.
closes #1845

chore(sequencer): remove unnecessary result return

---

Cargo.lock
crates/astria-bridge-contracts/CHANGELOG.md
crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-cli/CHANGELOG.md
crates/astria-composer/CHANGELOG.md
crates/astria-conductor/CHANGELOG.md
crates/astria-core/CHANGELOG.md
crates/astria-sequencer-relayer/CHANGELOG.md
crates/astria-sequencer/CHANGELOG.md

Updated the version of  `url`.
Running `cargo audit` yields a warning of a vulnerability in `idna` (see [RUSTSEC-2024-0421](https://rustsec.org/advisories/RUSTSEC-2024-0421)).  The suggested fix is to upgrade `idna` to >= v1.0.0.
`idna` is only a dependency in our tree of `url`, and we cannot upgrade `idna` to >= v1.0.0 without upgrading `url`.  However, upgrading `url` from v2.5.2 to v2.5.4 causes the `idna` dependency to upgrade to v1.0.3, hence fixing the issue.
- Ran `cargo update -p url` to increase the version of `idna` to v1.0.3.
Ran normal test suite.

chore: update `url` dependency

---

.github/workflows/scheduled.yml

Adds a regularly scheduled action to mark PRs and issues as stale, and then autoclose with a message if no action taken. 
Sometimes issues & pull requests stay around without action or cleanup. By tagging stale items and checking them we can make sure the list of PRs and issues we have is actually actionable. Closing does not impact ability to find and use in future, but makes sure that pertinent issues are easy to find.

chore(ci): action to autoclose stale issues and prs

---

charts/celestia-local/Chart.yaml
charts/celestia-local/files/scripts/init-celestia-appd.sh
charts/celestia-local/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/configmap.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml

Configurable block time environment variables for conductor and sequencer-relayer components
Currently, `ASTRIA_CONDUCTOR_CELESTIA_BLOCK_TIME_MS` and `ASTRIA_SEQUENCER_RELAYER_BLOCK_TIME` environment  variables are hard coded in the charts, the variables determines polling frequency and thus should be easily configurable. 
- configurable blocktime variables for conductor and sequencer relayer components.
locally templating the chart with new default values.

fix(charts): configurable components block times variables

---

charts/evm-faucet/Chart.yaml
charts/evm-faucet/templates/configmap.yaml
charts/evm-faucet/templates/deployment.yaml
charts/evm-faucet/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Current `evm-faucet` chart deployment does not support configuring request rate limit interval. 
Configurable request limit for production deployments
- fix secretProvider template 
- configurable request interval limit
Locally against a cluster

fix(charts, evm-faucet): configurable interval, secretProvider template fix

---

.github/workflows/lint.yml
.github/workflows/test.yml
justfile

Moved rust lints to just recipes, added all to lint rust recipe.
Discrepancies between the just recipe and GH workflow made it so that the lint command might succeed but then fail when a PR is opened. This is meant to make it easier to match the GH workflow locally and test to ensure this status check will pass.
- Moved all rust lints to just recipes.
- Changed `_lint-rust` to call all of the above recipes.
Manually tested

chore(ci): update rust lint workflows and `just` recipes

---

crates/astria-sequencer/src/action_handler/impls/ics20_withdrawal.rs

Restored original `FungibleTokenPacketData` import.
#1759 imported a slightly differing version of `FungibleTokenPacketData`, whose `serde` implementation did not exclude empty fields, breaking consensus.
- Restored original `FungibleTokenPacketData` import.
@joroshiba has successfully fully synced with this change.
- Technically a breaking change, but unbreaking a previous mistake.

fix(sequencer)!: fix fungible token packet data import

---

crates/astria-conductor/src/celestia/mod.rs

Removed empty tuple member in return type.
We shouldn't be returning a tuple with an empty member.
- Removed empty member from tuple return.
Passing all tests.
Noting that this requires overriding the Conductor code freeze, but due to the very small nature of this change I believe this will be okay since it should not have any bearing on auditing of the service.
closes #1879

chore(conductor): don't return empty tuple

---

crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/executor/builder.rs
crates/astria-conductor/src/executor/mod.rs

Changed firm block channel to use boxed `ReconstructedBlock`.
A large error variant lint was triggered when running clippy with Rust 1.83.0 in #1857 due to send errors returning the whole block. Large enum variants should be avoided because enums are only as small as their largest variant: https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant. Changing the channel to consist of a boxed block instead solves this problem at its source.
- Changed firm block channel to use boxed `ReconstructedBlock` instead of it being unboxed.
Passing all tests.
No updates needed.
Overridden code freeze since this is a very small, non breaking change that shouldn't have any bearing since our previous audit.
closes #1858

chore(conductor): send boxed objects over channels

---

crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/reconstruct.rs
crates/astria-conductor/src/celestia/reporting.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/tests/blackbox/helpers/mod.rs
crates/astria-core/CHANGELOG.md
crates/astria-core/src/sequencerblock/v1/block.rs
crates/astria-core/src/sequencerblock/v1/celestia.rs
crates/astria-sequencer-utils/src/blob_parser.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/grpc/state_ext.rs
crates/astria-sequencer/src/grpc/storage/values/block_hash.rs

Adds a newtype `astria_core::sequencerblock::v1::block::Hash` to represent Sequencer block hash (an array of 32 bytes).
The standard formatting of the newtype's `std::format:Display` implementation uses lower case hex, while its alternative selector uses standard base64. Note that the latter was introduced to provide a way to format the hash using the same conventions as pbjson for the protobuf wire types.
```rust
use astria_core::sequencerblock::v1::block;
let block_hash = block::Hash::new([42; 32]);
assert_eq!(
"2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a",
format!("{block_hash}"),
);
assert_eq!(
"KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio=",
format!("{block_hash:#}"),
};
```
During work on the Astria Auctioneer it was discovered that representing Sequencer Block …

feat(core)!: use newtype sequencer block hashes

---

charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

Update the postgresql chart dependency for evm-stack
The existing charts no longer work due to VMWare requiring a paid subscription
- Update chart URL to point to the OSS oci:// repo
Github's smoke-tests

Switch to OSS bitnami postgresql chart

---

crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/sequencer.rs

Remove events from `Sequencer::run_until_stopped`
that report on whether whether a state DB will be
opened or created.
Cnidarium already reports which paths it will read.
More egregious however is that
`Sequencer::run_until_stopped` is the wrong place
to emit these events because it does not have
authority over which actions cnidarium will take.
Should the constructor ever change, then the events
will be immediately out of whack, which will lead
to confusion.
- Remove state storage creation events from `Sequencer::run_until_stopped`.
No testing necessary. These are just some limited events.

chore(sequencer): remove misplaced logs

---

charts/auctioneer/Chart.yaml
charts/auctioneer/templates/_helpers.tpl
charts/auctioneer/templates/configmap.yaml
charts/auctioneer/templates/deployment.yaml
charts/auctioneer/templates/prometheusrule.yaml
charts/auctioneer/templates/secretproviderclass.yaml
charts/auctioneer/templates/service.yaml
charts/auctioneer/templates/servicemonitor.yaml
charts/auctioneer/values.yaml
charts/deploy.just
dev/values/auctioneer/values.yaml

Adds a Helm chart for deploying the Auctioneer.
[PR #1556](https://github.com/astriaorg/astria/pull/1556) adds the auctioneer binary. This binary has clients to both rollup  and sequencer nodes.
- Add the `charts/auctioneer` directory for the auctioneer binary
- Add commands to `charts/deploy.just` for deploying/deleting the auctioneer chart in our k8s cluster
- Add `dev/auctioneer/values.yaml` for dev values for the auctioneer.
- Add the auctioneer's dev wallet to the genesis allocations in `dev/validators/all.yaml` so that the auctioneer has a balance while testing against the dev cluster.
- Expose the bundle grpc service from the rollup chart so that the auctioneer can talk to it from within the cluster
How are these changes tested?
- Bulleted list of breaking changes, any notes on …

feat(chart): add auctioneer chart and just commands

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
dev/values/rollup/dev.yaml

Update the evm-rollup genesis charts to include `astriaAuctioneerAddresses` which is a map of block height to auctioneer addresses. We also add a new flag to geth called `auctioneer` which enables auctioneer functionality in the flame node.
The auctioneer binary submits a signed bundle to the sequencer which the flame side of the auctioneer unbundles and verifies. To verify the bundle signature, the flame side requires the bech32 address of the sequencer key which signed bundle. We pass the bech32 address of the sequencer key to the flame side by adding it as a field in the genesis file of the flame EVM rollup.
We also add a new flag in geth `auctioneer` which enables the auctioneer funcationality in a geth node.
- Add a field `astriaAuctioneerAddresses` to the …

feat(charts): update evm-rollup charts for auctioneer

---

charts/evm-rollup/templates/service.yaml

The grpc port of the evm-rollup needs to exposed in order for the auctioneer node to send optimistic blocks to be executed.
- exposed the grpc port in the `evm-rollup/templates/service.yaml` file
Deployed the auctioneer setup locally and sent a bundle

chore(charts): Auctioneer: Expose grpc port of the evm-rollup

---

crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/transaction/checks.rs

Changed bridge unlock cost calculation to use bridge address instead of signer address.
Previously, the `get_total_transaction_cost` attempted to retrieve the bridge account asset by the tx signer instead of by the bridge address. This works fine if the sender is a bridge account, but if it is the authorized bridge withdrawer, it will fail.
- Change `BridgeUnlock` cost calculation to retrieve asset based on the action's bridge address instead of the transaction signer.
Added unit test to ensure function works correctly when submitting a `BridgeUnlock` from the bridge withdrawer address.
Synced to mainnet from genesis to ensure this would not be a network breaking change.
Changelog updates.
- This change is breaking since previous `BridgeUnlock` submitted from the withdrawer address would …

fix(sequencer)!: use bridge address to determine asset in bridge unlock cost estimation instead of signer

---

clippy.toml

Allows writing CometBFT without backticks in Rust doc comments.
Clippy's pedantic settings consider CometBFT a Rust identifier because of its CamelCase. That's annoying, because it's actually the name of the consensus implementation we are using.
- Create a `clippy.toml` in the root of the repository.
- Add `doc-allowed-idents = ["CometBFT"]` to it.
Writing `CometBFT` in a Rust doc no longer triggers a clippy warning (no lines in this PR).

chore(clippy): ignore CometBFT as an identifier

---

crates/astria-sequencer/src/transaction/checks.rs

Refactored calculation of total transfers made in a transaction to helper function for clarity.
See here: https://github.com/astriaorg/astria/pull/1905#pullrequestreview-2542728784
> I think we should remove this function entirely in favor of two functions, `calculate_fees_for_transaction` (already exists) and `calculate_funds_moved_by_transaction` (essentially move the loop over the actions to it). The check for enough funds would then take the result of both methods.
- Moved calculation of all transfers made in a transaction to helper function, and called this helper function in `get_total_transaction_cost()`.
Passing all tests, no additional tests needed.
closes #1907

refactor(sequencer): clarify transaction cost estimation

---

charts/sequencer/Chart.yaml
charts/sequencer/files/scripts/init-cometbft.sh
charts/sequencer/templates/statefulsets.yaml
charts/sequencer/values.yaml

Adds the ability to start a sequencer node with a snapshot load, speeding up the startup time of a new node.
Starting a new node within k8s requires either manual intervention on the PVC right now, or syncing from genesis. Doing a sync from genesis can be correct but not ideal for scaling infrastructure.
- Changes sequencer chart `initContainer` for to use rclone
- Pull `snapshot` if `snapshotLoad` enabled during `initContainer` script run.
Ran locally, and confirmed startup and syncs.
closes https://github.com/astriaorg/astria/issues/1912

feat(charts): snapshot startup for sequencer

---

CODEOWNERS

Update CODEOWNERS allocate by project.
The previous CODEOWNERS file assigned reviews mainly by language (which is rust), which is no longer workable for a growing project leading to a) review bottlenecks, and b) unclear responsibilities over project-local styles and cognitive models on how to evolve the codebase.
The present changes have a BDFL model in mind, where the CODEOWNERS get the final vote over modifications to their crates.
- Remove any `@astriaorg/rust-reviewers` from the CODEOWNERS file
- Allocate crate ownership by project to @Fraser999, @noot, @SuperFluffy, and @joroshiba.
- Remove the `*.rs` catchall
- Assign rust-specific config files (`Cargo.toml`, and `Cargo.lock`, `rustfmt.toml`, `nextest.toml`, `rust-toolchain`, `.cargo/`) relative to CODEWONERS at the repository root …

chore(ci): update CODEOWNERS

---

crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/src/conductor/inner.rs
crates/astria-conductor/src/conductor/mod.rs

Removes a panic source in the conductor frontend by moving around the restart logic.
`Conductor::run_until_stopped` contains a loop to allow restarting its backend business logic. This loop delegates to a `Conductor::restart_or_shutdown` method to execute the restart of the backend, and then immediately reenters the loop no matter a restart happened or not.
While refactoring the inner conductor business logic (which lead to slightly different return values in turn affecting the blackbox test assertions) it was found that behavior can lead to the conductor backend panicking because it's being polled again even after running to completion.
- Rename `Conductor::shutdown_or_restart` to `Conductor::restart_or_shutdown` to match the enum it's branching on.
- Execute the restart inside the …

fix(conductor): remove panic source on shutdown

---

crates/astria-grpc-mock/CHANGELOG.md
crates/astria-grpc-mock/src/lib.rs

Makes the `astria_grpc_mock::mock::Times` part of the public API.
Having `Times` (which itself is wrapper around `u64` or one of the Rust `Range*` types) part of the public API is useful when writing abstraction tests.
- Export `astria_grpc_mock::mock::Times` at the root of the crate.
Not applicable. The type is now available.

chore(grpc-mock): make Times part of public API

---

crates/astria-sequencer/src/grpc/connect.rs
crates/astria-sequencer/src/sequencer.rs

This is a small PR to address a couple of minor omissions: implementing a query endpoint, and removing a needless RPC call.
These are likely just small omissions from previous work/discussions.
- Updated `MarketMapQueryService::market` to not always return a "not implemented" error response.
- Changed initial connection attempts to oracle sidecar to not actually send a request.
Manually tested both changes locally.  The former would ideally have unit tests, but this entire module is not unit tested.  The latter is harder to create a meaningful unit test for, but new smoke tests using the sidecar will make it apparent if this function is broken.

chore(sequencer): implement market endpoint

---

.github/workflows/reusable-docker-build.yml

Adds an additional tag to docker images corresponding to the full commit hash.  
Manually running github actions to build a docker image was not setting the full sha hash, which argocd uses to pull images. This should always set at least the full hash to the merge commit of a PR. 
Updated the docker metadata step to include an additional tag
Manually with PR commit and triggering GH action. 
"No updates required."

fix(ci): tag images with full commit sha

---

crates/astria-telemetry/CHANGELOG.md
crates/astria-telemetry/src/lib.rs

Instructs the tracing formatting subscriber to emit span events for event construction and deletion.
Developers frequently add an event at the beginning of a function to get information on whether a function is invoked. In tracing telemetry this is strictly speaking superfluous because the existence of a span already implies this information. If Astriia's services were primarily observed via an opentelemetry platform, then this issue wouldn't arise in the first place. But since events/logs are still consumed as plain text, we should mimick this behavior by emitting events when a particular unit of processing is started or finished.
Note that this will lead to noisier logs, but that is a justifiable tradeoff because this information is frequently needed when debugging services.
- Change …

feat(telemetry): emit span events for span construction, deletion

---

crates/astria-auctioneer/CHANGELOG.md
crates/astria-auctioneer/Cargo.toml
crates/astria-auctioneer/src/auctioneer/auction/allocation_rule.rs
crates/astria-auctioneer/src/auctioneer/auction/factory.rs
crates/astria-auctioneer/src/auctioneer/auction/mod.rs
crates/astria-auctioneer/src/auctioneer/auction/worker.rs
crates/astria-auctioneer/src/auctioneer/mod.rs
crates/astria-auctioneer/src/lib.rs
crates/astria-auctioneer/src/main.rs
crates/astria-auctioneer/src/metrics.rs

Extend Auctioneer by a first set of metrics.
Astria services must be observable, metrics are low hanging fruit.
- Added metrics (see metrics section below for a list).
This needs to be observed on a telemetry platform.
- astria_auctioneer_executed_blocks_received: counter
- astria_auctioneer_optimistic_blocks_received: coubter
- astria_auctioneer_auctions_cancelled: coubter
- astria_auctioneer_auctions_submitted: counter
- astria_auctioneer_auction_bids_processed: gauge (labels "processed" and "dropped")
- astria_auctioneer_auction_bids_received: counter
closes #1915

feat(auctioneer): add metrics

---

crates/astria-sequencer/src/app/vote_extension.rs
crates/astria-sequencer/src/connect/oracle/state_ext.rs

update `put_price_for_currency_pair` to error if state is not found. this is correct as the function is only called from `apply_prices_from_vote_extensions`, which only contains currency pairs that are already in the app state, as an invariant of the `id_to_currency_pair` validation done inside `validate_id_to_currency_pair_mapping`. thus, the previous `else` case where the state didn't exist would never be hit.
resolves oracle audit issue 3.1.
- update `put_price_for_currency_pair` to error if state is not found. 
existing unit tests

fix(sequencer): update `put_price_for_currency_pair`

---

crates/astria-core/CHANGELOG.md

Added the link for the bridge transfer action PR to the PR. https://github.com/astriaorg/astria/pull/1934
We want links to all changes to keep track of what was changed.
The PR in question: https://github.com/astriaorg/astria/pull/1934

chore(core): add missing link to changelog for bridge transfer impl

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/scripts/init-geth.sh
charts/evm-rollup/templates/statefulsets.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

changes to how flags condition is evaluated and used.
Our current evm-rollup charts has a bug, the condition which helps configuring geth flags is not being evaluated and always acts as `true`. This PR changes the condition templating. 
- conditions are now being templated based on the key value. Also makes sure this value is `true` if the condition exists.
- locally running smoke test against a cluster 
- using the helm command for templating: ` helm template my-chart ./charts/evm-stack -f ./dev/values/rollup/dev.yaml`

fix(charts): geth flags

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/geth-genesis.json
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/flame-rollup/Chart.yaml
charts/flame-rollup/files/genesis/geth-genesis.json

prague and verkle heights in genesis are now configured based on the appropriate values.
we have a bug in our charts where if we set an enable Cancun height, we will end up printing out a height for prague and verkle heights.
- prague and verkle heights are now set based on their values instead of cancun's.
locally by running helm template command

fix(charts): prague and verkle heights templating

---

charts/hermes/Chart.yaml
charts/hermes/values.yaml
charts/sequencer/Chart.yaml
charts/sequencer/values.yaml
dev/values/hermes/local.yaml

upgrades cometbft version from `v0.38.8 -> v0.38.17 `
cometbft [v0.38.17](https://github.com/cometbft/cometbft/blob/v0.38.17/CHANGELOG.md#v03817) includes two security fixes. 
- bumps cometbft version to v0.38.17
- hermes now uses serde patched image ( but in the `block_result` response)
- hermes now uses pull instead of push method for events.
locally running smoke tests against a local cluster.
closes #1980

chore(charts, cometbft): upgrade cometbft version to v0.38.17 and hermes usage

---

charts/auctioneer/Chart.yaml
charts/auctioneer/templates/service.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

auctioneer metric port name update to match `serviceMonitor` port
The port name tracked by auctioneer `serviceMonitor` does not match the metric service.
- change metrics port name (`metrics -> auct-metrics`) 
Tested while resolving auctioneer grafana dashboards on testnet.
Note: Bumping the auctioneer chart version may also resolve an issue with our initial auctioneer chart release.

fix(charts): auctioneer metrics port

---

crates/astria-sequencer/src/fees/storage/keys.rs
crates/astria-sequencer/src/fees/storage/snapshots/astria_sequencer__fees__storage__keys__tests__bridge_transfer_fees_key.snap

Added missing `BridgeTransfer` fee storage key tests
These tests were a minor oversight in the implementation of `BridgeTransfer`, but an easy fix to get in. As a followup, we should get together some documentation for adding new actions such that there's a quantitative list of items like this which are easy to miss.
- Added storage key snapshot and fee component prefix test for `BridgeTransfer` fees
Passing tests
- Not breaking, just noting that this added a snapshot
closes #1988

chore(sequencer): add missing storage key tests

---

crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/executor/mod.rs
crates/astria-conductor/src/executor/state.rs
crates/astria-conductor/src/executor/tests.rs
crates/astria-conductor/tests/blackbox/helpers/macros.rs
crates/astria-core/src/execution/v1/mod.rs
crates/astria-core/src/generated/astria.execution.v1.rs
crates/astria-core/src/generated/astria.execution.v1.serde.rs
crates/astria-core/src/generated/astria.execution.v2.rs
crates/astria-core/src/generated/astria.execution.v2.serde.rs
dev/values/rollup/dev.yaml
dev/values/rollup/flame-dev.yaml
proto/executionapis/astria/execution/v1/execution.proto
proto/executionapis/astria/execution/v2/execute_block_request.proto
proto/executionapis/astria/execution/v2/executed_block_metadata.proto
specs/execution-api.md

Adds a `sequencer_block_hash` to Execution API `Block` and `ExecuteBlock` shapes such that an execution can include it in their block space.
This is an addition but is backwards compatible. Old rollups can run the new binary, rollups that don't use the sequencer hash can utilize the old binary. Rollup forks which rely on the sequencer hash must utilize the new binary. 
We are upgrading Flame to the `Cancun` upgrade which includes `BeaconRoot` in the block hash. This is a natural time to add the sequencer block, as it is a similar concept. 
- Add new hash field to execution v1 protos and `astria-core`
- Added the field to in development execution v2 protos
- Update conductor to include the new data in `ExecuteBlock` requests
- Added information to the execute API spec.
CI/CD testing has …

feat(conductor): include sequencer block hash

---

crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/app/mod.rs
crates/astria-sequencer/src/grpc/sequencer.rs
crates/astria-sequencer/src/mempool/mod.rs
crates/astria-sequencer/src/mempool/transactions_container.rs
crates/astria-sequencer/src/service/consensus.rs

Updates when the mempool is rebalanced in order to solve for race condition in which call falls through to state before it has been written, by rebalancing after commit and updates the mempool methods to return the pending account nonce instead of the highest nonce in the pending mempool. 
Nonce is defined as the number of transactions which have been executed on the account. The pending nonce should then be the number of transactions executed + the number of transactions sitting in pending. Our API was not doing this correctly. Pending nonce on the mempool was being defined as the transaction with the highest nonce as opposed to what the account nonce will be after all pending transactions.
Additionally, our mempool was being rebalanced before state was committed, this can result in a …

fix(sequencer): mempool pending nonce calcuations

---

.cargo/audit.toml
Cargo.lock

Fixes for two new `cargo audit` warnings.
We get two warnings when running `cargo audit`, both for [RUSTSEC-2025-0009](https://rustsec.org/advisories/RUSTSEC-2025-0009).  One is for `ring@0.16.20` and the other `ring@0.17.11`.
<details><summary>cargo audit output</summary><p>
```
Crate:     ring
Version:   0.16.20
Title:     Some AES functions may panic when overflow checking is enabled.
Date:      2025-03-06
ID:        RUSTSEC-2025-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0009
Solution:  Upgrade to >=0.17.12
Dependency tree:
ring 0.16.20
└── jsonwebtoken 8.3.0
└── ethers-providers 2.0.14
├── ethers-middleware 2.0.14
│   └── ethers 2.0.14
│       ├── astria-test-utils 0.1.0
│       │   └── astria-composer 1.0.0
│       ├── astria-composer 1.0.0
│       ├── astria-cli …
```

fix: update `ring` dependency and update audit ignore list

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/flame-rollup/Chart.yaml
charts/flame-rollup/values.yaml
dev/values/rollup/dev.yaml
dev/values/rollup/flame-dev.yaml

Updates the evm charts to use latest releases of `astria-geth` and `flame` images
New releases of geth and flame cut. 
- Update the dev charts to use latest
- Utilize the newest release images for core charts
CI/CD tests

chore(charts): update for latest geth releases

---

crates/astria-core/src/connect/market_map.rs
crates/astria-core/src/protocol/connect.rs
crates/astria-core/src/sequencerblock/v1/block.rs
crates/astria-sequencer-utils/src/blob_parser.rs
crates/astria-sequencer/src/connect/market_map/storage/values/market_map.rs
crates/astria-sequencer/src/grpc/connect.rs

change decimals to be represented as u8 instead of u64 in native types. this is because geth uses u8 for decimals, so u64 could have resulted in truncation issues. decimals shouldn't be larger than u8 anyways.
fixes zellic audit issue 3.1 "Truncation and precision-loss issue between Astria and Geth during data transfer".
- change decimals to be represented as u8 instead of u64 in native types
code logic is unchanged.

fix(core): change decimals to be u8 natively

---

.github/code-freeze-filter.yaml

This removes the code-freeze on conductor and sequencer-relayer.
They were frozen for an audit, which is now complete.
- Removed conductor and relayer entries from the freeze filter file.
N/A

(chore): unfreeze conductor and relayer

---

.github/code-freeze-filter.yaml
.github/workflows/code-freeze.yml

We don't have anything under code freeze right now but this breaks the freeze test. Instead we should consider the freeze file itself frozen and require override to update.

ci: freeze test fix

---

charts/deploy.just
charts/ibc-test.just
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/_helpers.tpl
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer-relayer/values.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/cometbft/config/config.toml
charts/sequencer/files/cometbft/config/custom.genesis.json
charts/sequencer/files/cometbft/config/dawn-1.genesis.json
charts/sequencer/files/cometbft/config/dusk-11.genesis.json
charts/sequencer/files/cometbft/config/mainnet.genesis.json
charts/sequencer/templates/_helpers.tpl
charts/sequencer/templates/configmaps.yaml
charts/sequencer/values.yaml
dev/argocd/pr-preview-envs/sequencer-appset.yaml
dev/values/validators/mainnet.yml

Moves settings which should not change for various sequencer networks into top level global field. When deploying to different networks, this makes it such that values files will only need to unique configuration for a given node set as opposed to many values being unable to be changed. Makes it more difficult to misconfigure a node setting. 
- Add global setting of `network` to sequencer & sequencer-relayer charts.
- Configure the genesis & block timing parameters to defaults w/o override options for core networks
- Configure default images for individual networks, with optional overrides in "dev" mode. 
CI/CD testing, and syncing of a mainnet node. 
The default here is still custom to ensure backwards …

feat(charts)!: sequencer defaults for networks

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Create a new release of sequencer & supporting charts utilizing new release.

release(sequencer, charts): cut sequencer v2.0.0-rc.2 release

---

Cargo.lock
charts/sequencer/Chart.yaml
charts/sequencer/templates/_helpers.tpl
charts/sequencer/templates/configmaps.yaml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Cuts official 2.0 release of Sequencer, and chart update to ship it.

release(sequencer): v2.0.0 major release

---

Cargo.lock
Cargo.toml
crates/astria-auctioneer/Cargo.toml
crates/astria-auctioneer/src/auctioneer/auction/worker.rs
crates/astria-auctioneer/src/auctioneer/mod.rs
crates/astria-bridge-withdrawer/Cargo.toml
crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs
crates/astria-cli/Cargo.toml
crates/astria-cli/src/bridge/collect.rs
crates/astria-composer/Cargo.toml
crates/astria-composer/src/collectors/geth.rs
crates/astria-composer/src/executor/mod.rs
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/celestia/fetch.rs
crates/astria-conductor/src/celestia/mod.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/src/conductor/inner.rs
crates/astria-conductor/src/executor/client.rs
crates/astria-conductor/src/sequencer/client.rs
crates/astria-conductor/src/sequencer/mod.rs
crates/astria-sequencer-client/Cargo.toml
crates/astria-sequencer-relayer/Cargo.toml
crates/astria-sequencer-relayer/src/relayer/mod.rs
crates/astria-sequencer-relayer/src/relayer/read.rs
crates/astria-sequencer-relayer/src/relayer/submission.rs
crates/astria-sequencer-relayer/src/relayer/write/mod.rs
crates/astria-telemetry/Cargo.toml
crates/astria-telemetry/src/display.rs

Fix for a new cargo audit warning advising that `humantime` is unmaintained.
This was triggered by the warning [RUSTSEC-2025-0014](https://rustsec.org/advisories/RUSTSEC-2025-0014.html).
- Replaced our direct usage of `humantime` with the compatible functionality provided by [`jiff`](https://github.com/BurntSushi/jiff) as mentioned as a possible alternative in the advisory.
- Ran `cargo update env_logger` to remove the final dependency on `humantime`.
No new tests required.
No updates required - these changes are invisible to consumers.
Closes #2029.

(chore): replace `humantime` crate with `jiff`

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/templates/_helpers.tpl
charts/evm-rollup/templates/statefulsets.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/flame-rollup/Chart.yaml
charts/flame-rollup/templates/_helpers.tpl
charts/flame-rollup/templates/statefulsets.yaml

adds verbosity flag to geth statefulset. The log level is set based on config.logLevel entry.
alternative approaches:
- Setting config.logLevel to a numeric value (as expected by Geth) with documentation for users. This keeps the configuration simple and consistent with other flags but diverges from our other charts.
- Templating the config value directly in values.yaml, which works but is not an ideal approach for maintainability.
- adds a new flag configuring geth log level.
Tested against a local cluster

fix(charts): geth logLevel

---

charts/hermes/Chart.yaml
charts/hermes/values.yaml

bumps hermes image to use [pr-31 ](https://github.com/astriaorg/hermes/pull/31)
- bumps default hermes image
against a local cluster

chore(charts,hermes): bump hermes version

---

charts/just/deploy.just

Awaits  components' readiness in `deploy smoke-cli`.
CI for `run smoke-cli` is currently failing with 503 (service unavailable) due to the smoke test not being ready yet.
- Awaits Celestia's and rollup's readiness in `just deploy smoke-cli`
Tested locally.

fix(ci): wait for readiness in smoke CLI deployment

---

.cargo/audit.toml

Fixes for two new `cargo audit` warnings.
We get two non-critical warnings when running `cargo audit`: [RUSTSEC-2024-0436](https://rustsec.org/advisories/RUSTSEC-2024-0436) and [RUSTSEC-2025-0010](https://rustsec.org/advisories/RUSTSEC-2025-0010).
<details><summary>cargo audit output</summary><p>
```
Crate:     paste
Version:   1.0.15
Warning:   unmaintained
Title:     paste - no longer maintained
Date:      2024-10-07
ID:        RUSTSEC-2024-0436
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0436
Dependency tree:
paste 1.0.15
├── flex-error 0.4.4
│   ├── tendermint-rpc 0.34.1
│   │   ├── astria-sequencer-relayer 1.0.1
│   │   ├── astria-sequencer-client 0.1.0
│   │   │   ├── astria-sequencer-relayer 1.0.1
│   │   │   ├── astria-conductor 1.1.0
│   │   │   ├── astria-composer …
```

fix: update cargo audit ignore list

---

crates/astria-sequencer/src/app/test_utils.rs

Fixes incorrect comments related to signing keys in the sequencer app test utils.
These changes were moved from #1960 into a separate PR.
- Corrects which addresses signing keys correspond to in `sequencer::app::test_utils`.
No testing required.

chore(sequencer): fix signing key comments

---

dev/argocd/pr-preview-envs/evm-appset.yaml
dev/argocd/pr-preview-envs/sequencer-appset.yaml

Updates argo manifests to utilize github app credentials instead of a personal access token. 
Personal access tokens have an expiry and are set on user accounts. We have since updated things to use org-level github apps for everything else. This brings our preview-env configuration in line with the rest.
Switched reference to k8s secret containing github PAT to a different secret containing github app credentials
These were tested against dev environment

chore(ci): update argo manifests to use github app creds

---

Cargo.lock
Cargo.toml
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/Cargo.toml

Updates tendermint-rs to 0.40.3 and all penumbra dependencies to 1.40.0.
Light client verification patch fix made in tendermint-rs for [ISA-2025-003](https://github.com/informalsystems/tendermint-rs/security/advisories/GHSA-6jrf-4jv4-r9mw).
Penumbra has cut new releases that update their dependency on tendermint-rs.

fix: tendermint-rs 0.40.3

---

Cargo.lock
crates/astria-conductor/CHANGELOG.md

Fixes for a new `cargo audit` warning.
We get a warning when running `cargo audit` for [RUSTSEC-2025-0024](https://rustsec.org/advisories/RUSTSEC-2025-0024).  This is for `crossbeam-channel@0.5.14`.
<details><summary>cargo audit output</summary><p>
```
Crate:     crossbeam-channel
Version:   0.5.14
Title:     crossbeam-channel: double free on Drop
Date:      2025-04-08
ID:        RUSTSEC-2025-0024
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0024
Solution:  Upgrade to >=0.5.15
Dependency tree:
crossbeam-channel 0.5.14
└── moka 0.12.10
└── astria-conductor 1.1.0
Crate:     crossbeam-channel
Version:   0.5.14
Warning:   yanked
error: 1 vulnerability found!
warning: 1 allowed warning found
```
</p></details>
- Ran `cargo update -p crossbeam-channel`.
Ran `cargo audit` locally. …

fix: update crossbeam-channel dependency

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/startup.rs
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs

Fixes various typos in bridge withdrawer.
The changes were moved from #1960 into a separate PR.
- Changes various instances of "sequencing" to "sequencer".
No testing required.

chore(bridge-withdrawer): typo fixes

---

crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs
crates/astria-composer/src/executor/mod.rs

Changed submission logic to only encode retried transaction submissions to bytes once.
Previously, Bridge Withdrawer and Composer utilized `SequencerClientExt::submit_transaction_sync()`, which encodes the transaction to bytes within the method. Within a retry configuration, this unnecessarily performs the conversion each time. These changes eliminate these superfluous encodings in favor of retrying with the same bytes each time.
- Changed `submit_transaction_sync()` calls to `broadcast_tx_sync()` calls.
- Moved Tx encoding to outside the retry logic.
Passing all tests, no additional ones needed since the functionality is the same.
closes #2050

chore(bridge-withdrawer, composer): encode submission payload only once

---

Cargo.lock
crates/astria-sequencer-utils/Cargo.toml
crates/astria-sequencer-utils/README.md
crates/astria-sequencer-utils/src/activation_point_estimator.rs
crates/astria-sequencer-utils/src/cli.rs
crates/astria-sequencer-utils/src/lib.rs
crates/astria-sequencer-utils/src/main.rs

This adds a new subcommand to the sequencer-utils tool to help estimating activation points (i.e. future block heights) for scheduling sequencer upgrades.
This should be useful for setting upgrade activation points and also for monitoring scheduled activation points.
- Added `estimate-activation-point` subcommand.
Manual ad-hoc tests only.
Closes #2104.

chore(sequencer-utils): add upgrade activation height calculator to sequencer-utils

---

charts/sequencer/Chart.yaml
charts/sequencer/templates/service.yaml
charts/sequencer/templates/servicemonitor.yaml
dev/values/validators/all-without-native.yml
dev/values/validators/all.yml

Minor change to sequencer charts to flatten the yaml slightly.
We don't need a separate value to enable/disable metrics for the price feed sidecar.  We can use the existing value of `sequencer.metrcis.enabled && sequencer.priceFeed.enabled` for this.
- Changed `sequencer.priceFeed.metrics.enabled` to `sequencer.priceFeed.enabled` inside a block where `sequencer.metrcis.enabled` is already true.
Ran `helm template` locally.  Will be testing via argocd later.
Part of [ZenHub issue 121](https://github.com/astriaorg/astria/issues#workspaces/astria-6792bd6513d9f600312d8b6f/issues/zh/121).

chore(charts): update sequencer chart

---

charts/evm-bridge-withdrawer/Chart.yaml
charts/evm-bridge-withdrawer/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/external-ingress/Chart.yaml
charts/external-ingress/templates/ingress.yaml

Fixes two issues found while deploying the evm-cluster test app. The version in the current evm-withdrawer application is non existent, and the support for paths does not fully exist in the external ingress app.
- Rollback the version image tag on bridge withdrawer chart
- External ingress now supports full paths setup with same default.
Tested the external ingress chart using values generated from evm-cluster app.

fix(charts): incorrect image version, path support

---

charts/sequencer/Chart.yaml
charts/sequencer/templates/statefulsets.yaml

disable sidecar if priceFeed is disabled
Currently the price-feed sidecar runs by default, we should allow configuring this behavior.
- sidecar runs only if price feed is enabled
locally templating the chart with `helm template my-chart ./charts/sequencer -f ./dev/values/validators/single.yml`

chore(charts): disable sidecar if priceFeed is disabled

---

crates/astria-bridge-withdrawer/CHANGELOG.md
crates/astria-bridge-withdrawer/src/bridge_withdrawer/submitter/mod.rs
crates/astria-bridge-withdrawer/src/metrics.rs

Adds the `last_observed_rollup_height` gauge metric
The existing metrics does not provide an easy way to monitor withdrawer last rollup height. This is helpful to construct alerts based on last observed rollup height which should be much faster then submission checks.
- Added `last_observed_rollup_height` gauge metric
Tested locally against a k8 cluster with metrics enabled.
Changelogs Updated.
- `last_observed_rollup_height` gauge metric
closes #2110

chore(bridge-withdrawer): add metric for recording last observed rollup height

---

Cargo.lock
crates/astria-auctioneer/Cargo.toml
crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml

Cuts release candidate of conductor 2.0.0

release(conductor): 2.0.0-rc.1 with execution api v2

---

crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml
crates/astria-conductor/src/sequencer/client.rs

Add explicit TLS config for conductor when the sequencer url is https
Tonic [removed implicit TLS configs](https://github.com/hyperium/tonic/pull/1731) in v0.12.0 which now causes TLS errors when conductor tries to connect to a remote sequencer network over TLS.

fix(conductor): add explicit TLS config

---

charts/evm-rollup/Chart.yaml
charts/evm-rollup/files/genesis/flame-devnet.genesis.json
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml

- Adds a cancun time for `dusk-11` genesis
- This time is already configured on running nodes to activate, updating charts to keep inline with deployment

chore(chart): update genesis for dusk-11 cancun

---

crates/astria-composer/tests/blackbox/executor.rs

Fixed flaky test `composer::executor::two_rollup_data_submissions_single_bundle`.
This test previously failed semi-frequently for me locally. The issue first stemmed from the submission timeout period elapsing, but after increasing the time to span multiple blocks, it appeared that the submissions were ending up in different transactions. This seemed that it was likely due to the block timer ticking in between when the two submissions were made. As such, spinning them up concurrently appears to fix the problem.
- Change rollup transaction submission to be concurrent as opposed to in series to avoid the block timer ticking in between submissions.
No failures after testing >100 times.
closes #2041

chore(composer): fix flaky test

---

proto/executionapis/LICENSE
proto/signerapis/LICENSE
proto/upgrades/LICENSE

Adds MIT license files to the `signerapis` and `upgrades` packages.
All of our other packages contain an MIT license, but these packages were missing them.
- Adds MIT license files to the `signerapis` and `upgrades` packages.
- Updates year of the `executionapis` package, since we have had a large-scale update this year.
No testing required
closes #2167

chore(proto): add licenses to signer API and upgrades

---

.github/workflows/lint.yml
.github/workflows/reusable-run-checker.yml

Adds the `mempool-apis` and `upgrades` proto packages to the `proto` job in the `lint` workflow. 
The `mempool-apis` and `upgrades` packages were added recently, but neither have been added to the lint since they were not yet added in BUF. Now that they are, this adds these packages to the breaking changes lint.
- Adds `mempoolapis` and `upgrades` to the `lint/proto` job.
CI passing.
Closes #2145

chore(ci): add `mempool-apis` and `upgrades` to proto lint

---

.github/workflows/test.yml

Updating the ci tool version removes the warning from rust-cache: `Warning: Unsupported Cargo.lock format, fallback to caching entire file` as the new version supports newest Cargo.lock formats.
CI/CD, ran job twice on this to ensure cache worked.

ci: update rust cache tool

---

crates/astria-sequencer/src/checked_actions/checked_action.rs
crates/astria-sequencer/src/grpc/mod.rs
crates/astria-sequencer/src/sequencer.rs

Refactors `serve()` arguments into helper struct.
The `serve()` function which created the gRPC server for the sequencer and ran it had too many arguments, so a refactor was needed.
- Created helper struct `SequencerServerArgs` to cut down arg count.
- No additional tests required.
closes  #2134

chore(sequencer): refactor sequencer `serve()` function

---

crates/astria-core/CHANGELOG.md
crates/astria-core/src/protocol/transaction/v1/action/group/tests.rs
crates/astria-core/src/protocol/transaction/v1/action/mod.rs
crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/app/tests_breaking_changes.rs
crates/astria-sequencer/src/checked_actions/checked_action.rs
crates/astria-sequencer/src/checked_actions/currency_pairs_change.rs
crates/astria-sequencer/src/checked_actions/fee_asset_change.rs
crates/astria-sequencer/src/checked_actions/ibc_relayer_change.rs
crates/astria-sequencer/src/checked_actions/markets_change.rs
crates/astria-sequencer/src/mempool/transactions_container.rs
crates/astria-sequencer/src/oracles/price_feed/oracle/state_ext.rs
crates/astria-sequencer/src/test_utils/mod.rs

This changes how actions involving addition or removal of data are handled.
In some cases currently, we silently ignore additions where the data already exists, or removals where the data does not exist.  We want to always treat these as error conditions.
- Changed `CurrencyPairsChange::Addition` action to fail if any currency pair to be added is already stored.
- Changed `CurrencyPairsChange::Removal` action to fail if any currency pair to be removed is not currently stored.
- Changed `FeeAssetChange::Addition` action to fail if the fee asset to be added is already stored.
- Changed `FeeAssetChange::Removal` action to fail if the fee asset to be removed is not currently stored.
- Changed `IbcRelayerChange::Addition` action to fail if the address to be added is already stored.
- Changed …

chore(sequencer): update handling of addition and removal actions

---

Cargo.lock
crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml

Tag Conductor with v2.0.0-rc.2 that contains TLS fixes.
Contains https://github.com/astriaorg/astria/pull/2140

chore(conductor): v2.0.0-rc.2

---

crates/astria-sequencer/CHANGELOG.md
crates/astria-sequencer/src/app/mod.rs

This is a bugfix for `App::prepare_proposal`.
In `prepare_proposal`, while iterating the txs to be executed, we append the rollup data bytes to the collection of these _before_ checking and executing the tx.
This is an issue if the given tx fails the size checks or fails execution.  The end result is that the proposer later returns an error in finalize_block as the rest of the validators have a different (correct) view of the sequencer block and its included Merkle roots.
- Changed the type stored by the `App` under `EXECUTION_RESULTS_KEY` in the ephemeral store from `(rollup_data_bytes, tx_results, tx_ids)` to a `Vec<ExecutedTransaction>` where the `ExecutedTransaction` holds the checked tx and the corresponding execution result.  This avoids the possibility of a mismatch between the …

fix(sequencer): avoid including unexecuted rollup data

---

crates/astria-sequencer/src/app/tests_app/mempool.rs
crates/astria-sequencer/src/checked_actions/checked_action.rs

Added app-level mempool tests to ensure that transactions are successfully removed from the mempool with an "included" status in regular execution.
#2133 added support for `TransactionStatus`es, namely creating a new `RemovalReason::IncludedInBlock`. Tests were added to ensure that transaction IDs which were passed to the mempool in `App::commit` were successfully marked as "included", but no tests were added at a higher level to ensure that transactions are successfully conveyed between the different app methods and then to mempool. This led to a silent failure when the PR was first drafted, and the tests were deemed best suited for a followup.
These changes aim to address the three possible execution flows within the app to ensure executed transaction IDs are successfully passed to the …

chore(sequencer): add app-level mempool tests for transaction inclusion

---

charts/sequencer/Chart.yaml
charts/sequencer/files/upgrades/dawn-1.upgrades.json
charts/sequencer/files/upgrades/mainnet.upgrades.json

Updates chart release to include mainnet and dawn-1 blackburn upgrade files.
Estimated release times:
```
❯ cargo run -- estimate-activation-point -u https://rpc.sequencer.dawn-1.astria.org -t 10560000 -v
current height on `dawn-1`: 10519438
estimated instant on `dawn-1` for block 10560000: 2025-08-01T16:17:59.631550947Z
❯ cargo run -- estimate-activation-point -u https://rpc.astria.org -t 10600000 -v              
current height on `astria`: 10389959
estimated instant on `astria` for block 10600000: 2025-08-06T20:33:38.811249501Z
```
- Set upgrade in charts for blackburn testnet and mainnet.
- Release new chart version with files.

release(charts): blackburn upgrade

---

.github/workflows/reusable-docker-build.yml

Fixes an issue w/ missing api token when using depot builds
Changes were made due to failing docker builds
- oidc set to true in setup step
Manually

fix(ci): use oidc for depot setup step

---

.github/workflows/docker-build.yml
charts/celestia-local/Chart.yaml
charts/celestia-local/values.yaml
charts/evm-rollup/Chart.yaml
charts/evm-rollup/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
dev/values/rollup/evm-restart-test.yaml
system-tests/aspen_upgrade_checks.py
system-tests/helpers/evm_controller.py
system-tests/helpers/sequencer_controller.py
system-tests/sequencer_upgrade_test.py

Fixes upgrade tests for celestia v5 type changes
Celestia new types introduces in v5 breaks CI upgrade test. This PR removes sequencer-relayer and firm conditions to allow the tests to pass.
locally by running the tests

fix(CI): blackburn upgrade test with celestia v5

---

crates/astria-conductor/src/celestia/block_verifier.rs
crates/astria-conductor/src/celestia/verify.rs
crates/astria-conductor/tests/blackbox/firm_only.rs
crates/astria-conductor/tests/blackbox/soft_and_firm.rs

Updates Conductor to use the validator set at same height as a given commit.
We were previously using the previous commit, which worked when validator didn't change quickly enough to affect quorum, and allowed the use the proposer priorities to determine the correct validating node. We no longer use this priority, and quick changes to the validator set have caused the quorum to be unreachable from previously blocks proposer set.
- Use commit height instead of previous height for validator set.
CI/CD updates + manual testing.

feat(conductor): use latest validator height

---

Cargo.lock
charts/celestia-local/Chart.yaml
charts/celestia-local/values.yaml
charts/celestia-node/Chart.yaml
charts/celestia-node/values.yaml
charts/composer/Chart.yaml
charts/composer/templates/configmap.yaml
charts/composer/values.yaml
charts/evm-stack/Chart.lock
charts/evm-stack/Chart.yaml
charts/sequencer-relayer/Chart.yaml
charts/sequencer-relayer/templates/configmaps.yaml
charts/sequencer/Chart.lock
charts/sequencer/Chart.yaml
charts/sequencer/files/upgrades/dawn-1.upgrades.json
charts/sequencer/files/upgrades/mainnet.upgrades.json
crates/astria-conductor/CHANGELOG.md
crates/astria-conductor/Cargo.toml
crates/astria-sequencer-relayer/CHANGELOG.md
crates/astria-sequencer-relayer/Cargo.toml

Celestia v6 includes breaking changes to celestia apis. This has rolled out to mocha, these chart updates support rolling out to our networks with these new changes.
Additionally rolled back the dawn and mainnet blackburn upgrade information as these have not been activated yet.

release: image cuts to support celestia v6
